#!/usr/bin/env python3
"""Patch April devotionals in devotionals.json with full rewrite."""

import json

DEVOTIONAL_FILE = "SpeakLife/Preview Content/AffirmationData/devotionals.json"

# ─────────────────────────────────────────────────────────────────────────────
# All 28 rewritten devotionals (01-04 through 28-04)
# Apr 29-30 are preserved as-is (already excellent quality)
# ─────────────────────────────────────────────────────────────────────────────

new_texts = {

"01-04": (
"God's heart toward you is this — He wants your company. He designed prayer not as a religious duty "
"but as a direct line to Himself, and He built it so it is always open.\n\n"
"He is a God who hears. Not a distant force waiting for you to get your act together before He listens. "
"He is a Father who leans in when you speak. Colossians 4:2 calls you to devote yourself to prayer — not "
"because God needs convincing, but because He wants to be with you. Watchfulness and thankfulness aren't "
"conditions for entry. They're the posture of someone who already knows they have access.\n\n"
"Real life is loud. Mondays don't feel spiritual. Deadlines push out quiet moments. But God doesn't wait "
"for perfect conditions to meet with you. The same God who opens doors for His gospel opens His ears the "
"moment you come. You don't need a streak of good days. You don't need the right words. You just need to come.\n\n"
"This means you carry something powerful right now — direct, unfiltered access to the God who holds "
"everything together. That access doesn't expire when you fail. It doesn't close when you feel far away. "
"Jesus opened it, and Jesus keeps it open.\n\n"
"You can trust Him because He would never invite you to devote yourself to prayer if He wasn't ready to "
"listen every single time. His faithfulness doesn't depend on how consistent your prayer life has been. "
"It depends on who He is.\n\n"
"Come to Him today — watchful, thankful, and expectant. Not because you earned an audience. Because He already said yes.\n\n"
"Father, I come to You with full confidence right now. Thank You that prayer isn't a performance — it's "
"a conversation with a God who hears me every time. You open doors for Your gospel, and You open Your "
"heart when I call. I am devoted to seeking You because You are always worth finding. Amen."
),

"02-04": (
"God's heart toward you is so saturated with grace that He intends for it to overflow out of your mouth "
"and into the lives of every person you talk to today.\n\n"
"He is a God of grace — and grace changes everything it touches, including how you speak. Colossians 4:6 "
"says to let your words be full of grace, seasoned with salt. Salt preserves and gives flavor. Grace in "
"your words doesn't mean watered-down, avoid-all-conflict niceness. It means truth delivered with love — "
"words that season a conversation the way salt seasons a meal.\n\n"
"Think about someone who is struggling today. The right word at the right moment can shift everything "
"for them. Not a lecture. Not a correction. Just grace — the kind that makes a person feel seen, valued, "
"and not alone. That is what God puts in your mouth when His Word lives in your heart.\n\n"
"This means the way you talk to your kids, your coworkers, your friends — even how you talk to yourself — "
"is an expression of who God is. You don't have to perform grace. You carry it. He put it in you.\n\n"
"You can trust Him because He doesn't just command gracious speech — He models it. Every word He has ever "
"spoken to you has been seasoned with grace. He is the source of the very thing He's pouring through you.\n\n"
"Your words have the power to build, to heal, and to open hearts. That power comes from Him. Speak today "
"like someone who has been loved extravagantly.\n\n"
"Father, thank You that Your grace doesn't stop at my salvation — it flows into my speech. Fill my mouth "
"today with words that build up and give life. Let every conversation I have be seasoned with Your goodness. "
"I carry Your grace, and I will use it well. Amen."
),

"03-04": (
"God's heart toward you is the heart of a Father who chose you — not after seeing your best, but before "
"you could offer anything at all.\n\n"
"He is a God who selects. Before you tried to earn His favor, before you got anything right, God marked "
"you as His own. Colossians 3:12 calls you His chosen one, holy and beloved — and those aren't titles "
"you work toward. They are what you already are. Chosen. Set apart. Deeply loved. That is your identity, "
"handed to you by the God who saw you fully and wanted you anyway.\n\n"
"This changes how you live in a messy world. When you're impatient with someone who keeps letting you "
"down, God isn't asking you to muster up kindness from empty reserves. He's reminding you that you "
"received compassion and patience when you didn't deserve it — and now it flows from you because it "
"already lives in you.\n\n"
"You are clothed in His character. Compassion, kindness, humility, gentleness, patience — these aren't "
"requirements you're failing at. They're the wardrobe of someone who knows they are chosen. You put "
"them on because of who you ARE, not to become someone you're not.\n\n"
"You can trust Him because He didn't choose you conditionally. He chose you in Christ, fully, finally, "
"and forever. His love for you isn't on trial. It's already been decided.\n\n"
"You are God's chosen one, holy and beloved. Walk through today like someone who knows it.\n\n"
"Father, thank You for choosing me before I could earn it. I am holy and beloved because of You. "
"Today I put on compassion, kindness, and patience — not to impress You, but because I carry Your "
"nature in me. I walk in who You made me to be. Amen."
),

"04-04": (
"God's heart toward you is fiercely FOR you — not neutral, not waiting to see how you perform, but "
"actively, fully, completely on your side.\n\n"
"He proved it before you could earn it. Romans 8:32 says He did not spare His own Son — He gave Him "
"up for you. That is the most extravagant proof of loyalty ever given. If God was willing to surrender "
"His greatest treasure for you, do you think He's going to hold back anything else? The logic is "
"undeniable: He gave the best He had. Everything else follows.\n\n"
"So when something in life feels like it's working against you — a diagnosis, a relationship falling "
"apart, a door that won't open — remember this: none of it changes God's position. He is still FOR you. "
"Opposition doesn't override God's advocacy. People who disappoint you, systems that fail you, "
"circumstances that press hard on you — none of them have the final word.\n\n"
"Because God is for you, every resource of heaven is available to help you. Because He gave Jesus, "
"He will freely give you everything you need. That's not wishful thinking. That's the logic of the cross.\n\n"
"You can trust Him because the cross was the ultimate declaration of where God stands — and He stands "
"for you. Nothing that has happened today has changed that.\n\n"
"God is for you. Let that settle into your chest and drive out every fear.\n\n"
"Father, You are for me — and that changes everything. Thank You for not sparing Your Son but giving "
"Him for me. If You gave Jesus, I trust You to give me everything else I need. I live today from "
"the security of knowing You are on my side. Amen."
),

"05-04": (
"God's heart toward you is so fierce that Paul dared to ask — who or what could possibly cut you off "
"from Christ's love — and then answered his own question: absolutely nothing.\n\n"
"He is a God whose love is not fragile. Romans 8:35 lists the worst things life can throw at you — "
"trouble, hardship, danger, the threat of death — and declares that none of it separates you from "
"Christ. Not even one. That love isn't breakable. It doesn't depend on your good days. It doesn't "
"waver when your faith does. It holds because Christ holds, and He does not let go.\n\n"
"You may be in the middle of something that feels impossible right now. The pressure is real. The "
"pain is real. But here is what is also real: you are more than a conqueror through Him who loves "
"you. Not when the storm is over. Right now, in the middle of it, you are on the winning side "
"because the victory belongs to the One who loves you.\n\n"
"More than a conqueror doesn't mean you never struggle. It means the struggle cannot define your "
"outcome. Your outcome is defined by His love — and His love never loses.\n\n"
"You can trust Him because He loved you at your worst, at your weakest, and in your most broken "
"moment — and He never wavered. That love is the same today.\n\n"
"No trial has the authority to separate you from Christ. You are held, loved, and undefeatable in Him.\n\n"
"Father, nothing can separate me from Your love — not today's pressure, not my failures, not anything "
"in this world. I am more than a conqueror through You. I receive that truth right now and let it "
"strengthen me to face whatever is ahead. Your love holds me. Amen."
),

"06-04": (
"God's heart toward you is permanent. He looked at every force in the universe — death, life, angels, "
"demons, the present, the future, every power — and declared that not one of them could pull you out of His love.\n\n"
"Romans 8:38-39 is not a small promise. Paul was being exhaustive. He went through every category of "
"existence and checked it off. Death? No. Life? No. Things above? No. Things below? No. Things that "
"exist right now? No. Things that haven't happened yet? No. Nothing. That's the word that stands at the "
"end of the list — nothing in all creation can separate you from the love of God in Christ Jesus.\n\n"
"That means your worst day doesn't separate you. Your biggest failure doesn't separate you. The things "
"you're most ashamed of don't separate you. God's love for you isn't a feeling that can fade or a "
"contract that can be broken. It is a decision He made in Christ — and it is final.\n\n"
"This is your permanent address: the love of God in Christ Jesus. You cannot be evicted. You cannot "
"be driven out. You are held inside a love that is stronger than death itself.\n\n"
"You can trust Him because He wrote the list in Romans 8 knowing your exact situation — and He still "
"said nothing. He knew what you'd face, and He called it insufficient to separate you from Him.\n\n"
"You are inseparable from the love of God. Live today from that unshakeable place.\n\n"
"Father, nothing can separate me from Your love — and I receive that fully today. Not my past, not "
"my present, not anything that's coming. I am held in a love that nothing in creation can break. "
"I live from that security, and I am grateful. Amen."
),

"07-04": (
"God's heart toward you is purposeful — He called you to something real, and the call itself carries "
"everything you need to walk it out.\n\n"
"He is a God who calls. And Ephesians 4:1 says the life He's asking you to walk is simply one that "
"matches the calling He already gave you. This isn't about striving to reach some impossible standard. "
"It's about living from the inside out — from the identity He placed in you, not toward a title you "
"have to earn. Humility, gentleness, patience, unity — these aren't the price of the calling. "
"They're the fruit of someone who knows they've been called.\n\n"
"Everyday life tests this. A coworker who irritates you. A friend who disappoints you. A conversation "
"where your first instinct is anything but gentle. That's exactly where this calling lives — not "
"in theory, but in the friction of real relationships. And in those moments, God is not asking you "
"to perform patience. He is asking you to draw from what He already put inside you.\n\n"
"You were called to be a peacemaker. You were called to carry unity wherever you go. That calling "
"is not a burden — it's a privilege. You carry something the world desperately needs.\n\n"
"You can trust Him because He wouldn't call you to walk with humility and gentleness without giving "
"you His own Spirit to make it possible. He never sends without equipping.\n\n"
"Walk today in the fullness of who He called you to be. The world needs what you carry.\n\n"
"Father, thank You for calling me — not to perform, but to live from who You made me. I choose "
"humility, gentleness, and patience today — not to earn anything, but because Your Spirit in me "
"makes it possible. I walk worthy of Your calling because You walk with me. Amen."
),

"08-04": (
"God's heart toward you is extravagant — He didn't give you the minimum amount of grace needed "
"to get by. He measured your grace by the fullness of Christ's own gift.\n\n"
"Ephesians 4:7 says grace was given to each one of us according to the measure of Christ's gift. "
"That's personal. That's deliberate. The King of all grace looked at you specifically and said, "
"'Here — I'm giving you grace sized by what Jesus gave.' Not a generic portion for the masses. "
"A personal allotment, measured by the most generous gift in history.\n\n"
"This means you have been equipped for what God has called you to. You are not running on empty. "
"You are not underpowered for the life He has placed in front of you. The grace you have received "
"is Christ-sized — which means it is more than enough for your weakness, your season, and your calling.\n\n"
"Whatever you've been holding back because you didn't think you had enough — enough strength, "
"enough gifting, enough faith — this verse says otherwise. You have been given grace according "
"to Christ. That is not a small supply.\n\n"
"You can trust Him because the One who measured out your grace is the same One who gave everything "
"at the cross. He is not stingy. He is not running low. He gave generously, and He gave it to you.\n\n"
"You are not lacking. You are graced — personally, specifically, and lavishly by the King.\n\n"
"Father, thank You that the grace You gave me is measured by Christ's gift — and that means it's "
"enough for everything I face. I am not running low on what I need. I receive Your generosity "
"today and step into my calling from a place of abundance, not lack. Amen."
),

"09-04": (
"God's heart toward you is purposeful — He didn't place you in His family as a filler. He built "
"you into the body of Christ with intention, and the body is incomplete without what He put in you.\n\n"
"He is a God who builds. Ephesians 4:12-13 says you were made to build up the body of Christ — "
"to contribute to its growth until we all reach the fullness of who Christ is. You are not a "
"spectator in God's family. You are a builder. The gifts He placed in you aren't decorations. "
"They are tools that the whole body needs.\n\n"
"You may not feel qualified. You may feel invisible in a crowd, or like your contribution is too "
"small to matter. But God doesn't measure impact the way the world does. He looks at faithfulness. "
"He looks at love. The encouragement you give someone this week, the prayer you pray, the truth "
"you speak in season — these are acts of construction in God's kingdom.\n\n"
"The body of Christ grows toward maturity because of what you bring. You are not optional. "
"You are essential. The measure of God's plan in this world includes you, specifically.\n\n"
"You can trust Him because He is the architect of His own body — and He designed you to fit "
"exactly where He placed you. Nothing about your role in His family is accidental.\n\n"
"You were made to build. Every act of faithfulness today is a brick in something eternal.\n\n"
"Father, thank You that I am not an afterthought in Your family. You placed me here with purpose. "
"I commit today to building up the people around me with what You've put in me. Use my gifts, "
"my words, and my presence to help Your body grow strong. Amen."
),

"10-04": (
"God's heart toward you is that you would grow — not in isolation, struggling alone, but "
"connected to His body, rooted in truth, and surrounded by love.\n\n"
"He is a God who connects. Ephesians 4:15-16 paints a picture of the whole body joined together, "
"every part working properly, growing in love. Christ is the head — and everything flows from Him "
"through the body. When you speak truth in love, when you stay in real relationship with other "
"believers, you are not just being a good person. You are participating in the design of God.\n\n"
"Growth doesn't happen in a vacuum. You need real people around you — people who speak truth "
"when you need it, who love you through the hard parts, and who help you see Christ more clearly. "
"That's not optional. That's how the body works. And God made you to both give and receive that.\n\n"
"This means your community matters more than you might think. The church isn't a place you visit. "
"It's the body you belong to. And when you show up — honest, humble, willing to speak and "
"listen — everyone grows, including you.\n\n"
"You can trust Him because He himself is the one holding the whole body together. You don't have "
"to hold it all. You just have to stay connected to the Head and do your part.\n\n"
"Speak truth today. Stay connected. Grow into the full measure of who Christ is in you.\n\n"
"Father, thank You for placing me in a body that grows together in You. I choose to speak truth "
"in love and stay connected to the people You've given me. Use me to help others grow, and use "
"them to help me grow into the full measure of Christ. Amen."
),

"11-04": (
"God's heart toward you is a renewed mind — He never intended for you to keep thinking the way "
"the world thinks, and He made a way out of that darkness.\n\n"
"He is a God of light and truth. Ephesians 4:17-18 describes what life without God looks like — "
"futile thinking, darkened understanding, a mind cut off from the life of God. That was your old "
"address. But you moved. You are no longer living in the dark. The moment Christ came in, the "
"lights came on — and you now have access to a mind shaped by the truth of who God is.\n\n"
"This matters on an ordinary Tuesday. The way you think determines how you live. If your mind "
"tells you you're not enough, you'll live small. If your mind tells you God is not trustworthy, "
"you'll live in anxiety. But when your mind is renewed by His Word, you see yourself and your "
"circumstances the way He does — and that changes everything.\n\n"
"You don't have to keep entertaining the old thoughts. You don't have to accept every idea that "
"shows up in your head. You have a renewed mind in Christ, and you can choose what you dwell on.\n\n"
"You can trust Him because His Word is the tool He uses to renew your mind — and it never fails "
"to do what He sends it to do. Lean into it. Let it reshape how you think.\n\n"
"Your mind is not a battlefield you're losing. It's a mind being renewed by the most powerful "
"truth in the universe.\n\n"
"Father, thank You that I no longer have to think the way the world thinks. My mind is being "
"renewed by Your truth. Today I choose to think the way You see — and I trust that those thoughts "
"will produce a life that honors You. I am not in the dark anymore. I am in Your light. Amen."
),

"12-04": (
"God's heart toward you is entirely new life — He didn't repair the old version of you. He "
"created someone brand new, and that new self is who you truly are.\n\n"
"He is a God who makes things new. Ephesians 4:22-24 says the old self belonged to a former way "
"of life — corrupt, driven by deceitful desires, destined to decay. But that is not you anymore. "
"You put off the old self like a worn-out coat, and you have put on a new self — created after "
"the likeness of God in true righteousness and holiness. That is not who you're trying to become. "
"That is who you already are in Christ.\n\n"
"This matters when old patterns try to resurface. When a familiar sin whispers your name, it is "
"calling to someone who no longer lives here. You don't have to negotiate with the old self. You "
"don't have to keep pulling from a dead source. The old is gone. What is in front of you is new.\n\n"
"You were made in the likeness of God — righteous and holy. Not as a goal to achieve, but as "
"the reality you step into. When you live from that truth, the old patterns lose their power.\n\n"
"You can trust Him because He is the author of new creation. He did not partially renovate you. "
"He made you new — and what God makes, He makes completely.\n\n"
"You are new. Let that truth be louder today than every old pattern trying to pull you back.\n\n"
"Father, thank You that I am not the old me. You made me new — created in Your likeness, "
"righteous and holy. Today I walk in that truth. I put off every old way of living and step "
"fully into who You made me to be. The new self is who I am. Amen."
),

"13-04": (
"God's heart toward you is wisdom and peace — He made room for your emotions and then gave you "
"a way to not let them run your life.\n\n"
"He is a God who understands anger. Ephesians 4:26 doesn't say 'never be angry.' It says be angry "
"and do not sin. God created you with emotions, and anger is one of them. There are things worth "
"being angry about — injustice, cruelty, harm done to people you love. God is angry at those "
"things too. The call here isn't to suppress what you feel. It's to feel it without letting it "
"become a foothold for the enemy.\n\n"
"The sun going down on your anger matters because unresolved anger festers. What starts as "
"righteous frustration can harden into bitterness if you don't bring it to God. The enemy loves "
"an open wound. He'll pour poison into any anger left alone overnight. But when you bring it "
"to God before the day ends, you cut off that access point.\n\n"
"You don't have to have everything resolved by sundown. You just need to release it to Him. "
"Let Him hold what you can't fix. Let His peace stand guard over what your anger wanted to control.\n\n"
"You can trust Him because He is slow to anger and rich in love — and He will meet you in your "
"anger without shaming you for having it. He just doesn't want it to stay unchecked.\n\n"
"Feel what you feel. Bring it to God. Don't let the sun go down with a foothold open in your heart.\n\n"
"Father, thank You that You understand my emotions and don't shame me for them. I bring my anger "
"to You right now — every frustration, every wound. I won't let it sit and harden. I release it "
"to You and receive Your peace in its place. No foothold for the enemy today. Amen."
),

"14-04": (
"God's heart toward you is that your words would carry the same grace He poured into you — "
"building people up, not tearing them down.\n\n"
"He is a God who speaks life. Ephesians 4:29 says to let no corrupting talk come out of your "
"mouth — only words that are good for building up, fitting for the moment, that give grace to "
"those who hear. This is not about policing every word. It's about recognizing that the Holy "
"Spirit lives in you, and your words are one of the primary ways He works through you. What "
"you say has the power to shift someone's entire day.\n\n"
"You know how it feels when someone speaks the right word at the right time. It lands deep. "
"It lifts something heavy. That is what you carry — the ability to give grace through your "
"voice. And the Holy Spirit, who sealed you for the day of redemption, wants to guide your "
"tongue toward what builds and heals.\n\n"
"This also means that when you're tempted to speak in anger, to tear someone down, to use "
"your words as a weapon — that grieves the Spirit of God who lives inside you. Not because "
"you've lost your salvation, but because He loves both you and the person you're tempted to hurt.\n\n"
"You can trust Him because the same Spirit that filled the disciples on Pentecost is the one "
"living in you right now. He knows exactly the word someone needs. Ask Him.\n\n"
"Let your words today be a gift. Someone is waiting to hear what God wants to say through you.\n\n"
"Father, thank You for sealing me with Your Spirit. I want my words to give grace — today and "
"every day. Help me speak what builds up and hold back what tears down. Let my mouth be a "
"tool in Your hands, giving life to everyone I talk to. Amen."
),

"15-04": (
"God's heart toward you is tenderness — and He wants that tenderness to become the atmosphere "
"you carry into every relationship you have.\n\n"
"He is a tenderhearted God. Ephesians 4:32 says be kind, tenderhearted, forgiving — as God in "
"Christ forgave you. Notice the order. First it says what God is like. Then it says become "
"what He is. You are not manufacturing kindness from nothing. You are passing on what you "
"already received. The forgiveness that flows from you is fueled by the forgiveness poured "
"into you — and that well never runs dry.\n\n"
"Forgiveness is hard. Especially when the hurt is real and the apology never came. But the "
"power to forgive doesn't come from your emotional reserves. It comes from remembering what God "
"absorbed on your behalf. He took the debt you owed and cancelled it completely. What He asks "
"you to extend to others is simply a portion of what He already gave to you in full.\n\n"
"Kindness and tenderheartedness don't mean you have no boundaries. They mean you choose not "
"to carry the weight of bitterness when forgiveness is possible. They mean you see people "
"the way God sees you — as someone worth choosing grace for.\n\n"
"You can trust Him because He forgave you at your worst, with nothing to offer in return. "
"His forgiveness was not reluctant. It was generous. And His nature in you makes you capable "
"of the same.\n\n"
"Let forgiveness flow today. Not because they deserve it — because you already received more "
"than you deserved.\n\n"
"Father, thank You for forgiving me completely and making me tenderhearted. I choose to "
"extend kindness and forgiveness today because You filled me with it first. Your grace in "
"me is enough to cover every hard moment. I walk in that grace right now. Amen."
),

"16-04": (
"God's heart toward you is this — He didn't just bring you near the light. He made you light itself. "
"And light doesn't try to shine. It just does.\n\n"
"He is light, and He shared His nature with you. Ephesians 5:8 draws the starkest possible "
"contrast — at one time you WERE darkness. Not in darkness. You were darkness. And now you ARE "
"light in the Lord. Not have a little light. Not trying to be good enough to shine. You are "
"light. That transformation is total, and it happened because of who He is in you.\n\n"
"Walking as a child of light means living in alignment with your true nature. When you choose "
"honesty, when you act with integrity, when you do what's right even when no one is watching — "
"you are not performing for God's approval. You are being who you already are. Light exposes "
"what is hidden. Your presence in a room changes the atmosphere. Not because you try hard enough, "
"but because you carry Him.\n\n"
"The fruit of light is goodness, righteousness, and truth. That fruit doesn't grow because you "
"strain after it. It grows because you stay connected to the source — the One who IS light and "
"made you like Himself.\n\n"
"You can trust Him because He declared you light in the same breath that He called Himself light. "
"Your identity is rooted in His nature. That doesn't change with your mood or your morning.\n\n"
"You are light. Walk today like someone who believes it.\n\n"
"Father, thank You that I am light in You — not trying to be, but already am. I walk today in "
"alignment with who You made me. Let goodness, righteousness, and truth mark everything I do. "
"I carry Your nature, and I am grateful to shine because of You. Amen."
),

"17-04": (
"God's heart toward you is a call to come alive — because Christ's light is already shining "
"on your face, and He is not waiting for you to get it together first.\n\n"
"He is a God who wakes the dead. Ephesians 5:14 says 'Awake, O sleeper, and arise from the "
"dead, and Christ will shine on you.' This is a resurrection call. Christ doesn't shine His "
"light on people who have cleaned themselves up enough to deserve it. He shines on those who "
"were dead — and His light is what makes them alive. You don't wake up and then get light. "
"The light wakes you up.\n\n"
"Maybe today you feel spiritually asleep — going through motions, numb, disconnected, or just "
"plain tired of trying. That is exactly who this verse is for. The call is not 'try harder.' "
"The call is 'wake up' — because the One who raises the dead is right in front of you, and "
"His light is already on you.\n\n"
"Make the most of your time. Walk wisely. The days are short and the opportunities are real. "
"But you don't do that by striving — you do it by waking up to what's already true. Christ "
"has already shone on you. Your job is to walk in that light.\n\n"
"You can trust Him because He never commanded anyone to wake up without also providing the "
"power to do it. He calls you awake and gives you His Spirit to make that possible.\n\n"
"Wake up today. Open your eyes to the light that's already on you. Christ is shining, and you are alive.\n\n"
"Father, I wake up to You today. Thank You that Your light is already on me — I don't have to "
"earn it or reach for it. I receive it right now. Make me wise with my time and alive to Your "
"purposes today. You shine on me, and I am grateful. Amen."
),

"18-04": (
"God's heart toward you is fullness — He is not rationing His Spirit, not reserving it for "
"the spiritual elite. He wants to fill you completely, and He offers it freely.\n\n"
"He is a God who fills. Ephesians 5:18 says be filled with the Spirit — and the verb is "
"continuous. Keep being filled. Stay filled. This isn't a one-time event that happened at "
"your conversion and is now complete. It is an ongoing reality God makes available to you "
"every single day. He doesn't want you running on fumes. He doesn't want you living off "
"yesterday's filling when today's is available right now.\n\n"
"Understanding His will starts with being filled with His Spirit. You don't figure out God's "
"direction through sheer intellectual effort. You receive it through a Spirit-filled life — "
"through worship, through His Word, through staying connected to Him. The Spirit in you "
"leads, guides, and illuminates the path when you make room for Him.\n\n"
"Being filled with the Spirit is not weird or reserved for a particular kind of Christian. "
"It is simply living in open, ongoing dependence on the God who wants to be your source. "
"It means singing. It means giving thanks. It means letting Him be the loudest voice in your life.\n\n"
"You can trust Him because He gave His Spirit as a gift — not as a reward for performance. "
"He freely poured out His Spirit, and He is still pouring today.\n\n"
"Come open-handed. Let Him fill what is empty and overflow what He has already given.\n\n"
"Father, I come to You open-handed today. Fill me with Your Spirit — completely, continuously, "
"lavishly. I don't want to live below what You've offered. I choose today to be Spirit-filled, "
"Spirit-led, and Spirit-overflowing. Thank You for this gift that never runs out. Amen."
),

"19-04": (
"God's heart toward you is protective — He never sent you into a battle without equipping you "
"for it first, and He has given you everything you need to stand.\n\n"
"He is a warrior-God who arms His people. Ephesians 6:11-12 tells us to put on the whole armor "
"of God — because the real battle is not against people or circumstances. It is against spiritual "
"powers, against darkness that works behind the scenes. You need more than a good attitude to "
"stand against that. You need armor — and God supplied every piece of it.\n\n"
"The enemy's strategy is schemes — deception, accusation, discouragement, and doubt. He works "
"in the unseen. But God didn't leave you unprepared for an unseen enemy. He gave you truth as "
"your foundation, righteousness as your guard, faith as your shield, and His Word as your sword. "
"You are not fighting to win — you are fighting from a position of victory already secured by Christ.\n\n"
"This changes how you face your day. When discouragement hits, you don't just feel it — you "
"recognize it as a scheme and reach for what God gave you to stand against it. When lies come "
"at you, you answer them with the truth of His Word. You have the armor. Put it on.\n\n"
"You can trust Him because He is the God of angel armies, and He has assigned His own authority "
"to your life. You are never facing the darkness alone.\n\n"
"You are not a victim of spiritual warfare. You are an armed soldier in Christ.\n\n"
"Father, thank You for arming me for every battle I face. I put on Your full armor today — "
"truth, righteousness, faith, and Your Word. I stand firm, not in my own strength, but in "
"Yours. The schemes of the enemy have no power over the child of God who is fully dressed "
"in what You provided. I stand. Amen."
),

"20-04": (
"God's heart toward you is that you would stand — not white-knuckling it, not just surviving, "
"but standing firm and strong in the truth of who He is and who He made you.\n\n"
"He is the God of truth and righteousness. Ephesians 6:14-15 describes the first pieces of "
"armor: the belt of truth buckled tight, the breastplate of righteousness in place, and feet "
"ready to move with the gospel of peace. The belt holds everything together. And the truth "
"that holds you together is not a set of rules — it is the truth about God's character, His "
"Word, and your identity in Christ. When you know who He is and who you are, the lies of the "
"enemy have nothing to grab onto.\n\n"
"The breastplate covers your heart. Righteousness guards the most vulnerable part of you — "
"not righteousness you earned, but the righteousness Christ gave you. When the enemy accuses "
"you, when shame tries to convince you that you don't belong to God, the breastplate says "
"otherwise. You are righteous because He is righteous and He gave it to you.\n\n"
"And your feet are ready — ready to go with the gospel of peace. You're not standing still "
"waiting for the battle to end. You are positioned to move, to carry good news, to bring peace "
"wherever you step.\n\n"
"You can trust Him because He is the source of every piece of armor He gave you. Truth. "
"Righteousness. Peace. All of it flows from who He is.\n\n"
"Stand today. Dressed in truth, guarded by righteousness, and ready to move in peace.\n\n"
"Father, I put on the armor You gave me today. I buckle truth around me. I wear righteousness "
"as my protection. I stand firm not in my own strength but in Yours. Every step I take today "
"carries the gospel of peace. I am equipped, and I am standing. Amen."
),

"21-04": (
"God's heart toward you is open access — He is never unavailable, never too busy, never tired "
"of hearing your voice. He is always ready when you come.\n\n"
"He is a God who is present. Ephesians 6:18 calls you to pray at all times in the Spirit — "
"not just in church, not just in crisis, not only when you feel spiritual enough. At all times. "
"In the Spirit. This is the invitation to a life where prayer isn't a scheduled event but a "
"continuous conversation with a God who is always there. You don't need a quiet room and a "
"specific posture. You need a heart turned toward Him.\n\n"
"In the Spirit means you're not doing this alone. The Holy Spirit prays with you and through "
"you — even when you don't know what to say, even when the words don't come, even when all "
"you have is a groan and a need. He takes what you bring and lifts it before the Father. "
"Your prayers are never wasted and never ignored.\n\n"
"Praying for all the saints is part of this. You are not just praying for your own life. "
"You are participating in something much larger — interceding for the body of Christ, for "
"people you'll never meet, for needs you don't even know about yet. Your prayers move things.\n\n"
"You can trust Him because He commanded you to pray at all times knowing He would meet you "
"every time. He does not give invitations He won't honor.\n\n"
"You have constant access to the God who holds everything. Use it freely.\n\n"
"Father, thank You that I can come to You at any moment and You are always there. I pray "
"in the Spirit today — for my own needs and for everyone around me. My prayers are powerful "
"because they reach You, and You always respond. I'm grateful for this access that never closes. Amen."
),

"22-04": (
"God's heart toward you is boldness — He can use you powerfully even from the most constrained, "
"limited, or difficult place in your life right now.\n\n"
"He is a God who is never chained. Paul was in physical chains when he wrote Ephesians 6:20, "
"asking for prayer to declare the gospel boldly as he ought. Paul didn't ask to be released. "
"He asked to be bold where he was. And he was. The gospel he preached from prison reached "
"emperors, guards, and generations of believers who came after him. His chains didn't limit "
"what God was doing — they were the stage God chose.\n\n"
"Your circumstances may feel limiting. There may be places in your life where you feel stuck — "
"a job you didn't choose, a diagnosis you didn't expect, a relationship that's hard to leave. "
"But God specializes in using people in difficult positions. He doesn't need you to have "
"everything together before He can work through you. He needs you to be willing to be bold "
"right where you are.\n\n"
"You are an ambassador. That title doesn't require freedom from hard circumstances. It requires "
"a message, a mouth, and a willingness to speak. The ambassador's power comes from who sent "
"them — and you were sent by the King of Kings.\n\n"
"You can trust Him because He gave Paul words in prison and He will give you words in yours. "
"His power is not limited by your location.\n\n"
"Be bold right where you are. God is doing something through you that you can't see yet.\n\n"
"Father, thank You that my circumstances don't limit Your power. I am Your ambassador — "
"right here, right now, in whatever I'm facing. Give me boldness to speak and courage to "
"declare who You are in every space I occupy. You work through willing people, and I am willing. Amen."
),

"23-04": (
"God's heart toward you is peace — deep, settled, unshakeable peace that comes straight from "
"the Father and cannot be manufactured by any other source.\n\n"
"He is the God of peace. Ephesians 6:23-24 is Paul's closing blessing over a church he loved — "
"and what he gives them is peace, love with faith, and grace. These aren't nice sentiments. "
"They are the substance of everything Christ won for you. Peace with God — the hostility is "
"over. Love with faith — the relationship is real and it holds. Grace incorruptible — a love "
"that does not decay, does not fade, and is not diminished by time or failure.\n\n"
"On hard days, when peace feels far away, the problem is never that God ran out of it. "
"Peace from God the Father and the Lord Jesus Christ is available to you right now — the same "
"peace that Paul wrote about from a Roman prison, the same peace that passed through every "
"generation of believers who faced impossible things and stood firm.\n\n"
"Grace incorruptible means it cannot be contaminated. It cannot be ruined by what you did "
"last week or what you're struggling with today. His grace toward you is pure, permanent, "
"and personally yours.\n\n"
"You can trust Him because He IS peace. He doesn't give you something He doesn't possess. "
"When He offers peace, He is offering Himself.\n\n"
"Receive His peace today. It's not something you earn — it's something you open your hands to.\n\n"
"Father, I receive Your peace right now. The peace that passes understanding, that guards my "
"heart and my mind in Christ Jesus. I receive Your love and faith and grace that never decays. "
"You are the source of everything I need, and I rest in that today. Amen."
),

"24-04": (
"God's heart toward you is that you would know this — Christ isn't just a part of your life. "
"He IS your life. And because He is your life, your best days are still ahead.\n\n"
"He is the source of everything you are. Colossians 3:4 says when Christ who is YOUR life "
"appears, then you will also appear with Him in glory. Paul doesn't say Christ is a part of "
"your life or a helper in your life. He says Christ IS your life. You are not a self-contained "
"person who added Jesus to the mix. You are someone who is alive because He is alive in you.\n\n"
"This reframes everything. Your purpose isn't something you're chasing — it's carried in the "
"One who carries you. Your security isn't built on your performance — it's rooted in the One "
"who never fails. When your life is hidden with Christ in God, you are protected by the "
"greatest force in existence.\n\n"
"And there is a day coming when He appears — and on that day, you appear with Him. In glory. "
"Not just forgiven. Not just barely scraped through. Fully revealed, fully known, fully glorious "
"because the glory of Christ covers you. That is your future. That is where you're headed.\n\n"
"You can trust Him because He who is your life is unchanging. He doesn't run out, doesn't "
"falter, and cannot be taken from you. Your life is safe because He is.\n\n"
"Christ is your life. Let that truth be the ground you stand on today.\n\n"
"Father, thank You that Christ is my life — not just a part of it. My identity, my security, "
"my future are all wrapped up in Him. I set my heart on what is above today, knowing my life "
"is hidden in You. When He appears, I appear. I live from that unshakeable reality. Amen."
),

"25-04": (
"God's heart toward you is transformation — He is actively, daily renewing you into His own "
"image, and every day you are more fully becoming who He made you to be.\n\n"
"He is a God who renews. Colossians 3:10-11 says you have put on the new self, which is being "
"renewed in knowledge after the image of its creator. The renewal is continuous. You are not "
"finished yet — and that is not a failure, it's a promise. God is still working on you. He "
"hasn't stepped back and left you to finish the project alone. He is actively renewing, "
"reshaping, and revealing more of Christ in you every single day.\n\n"
"And in that new self, every dividing line falls away. Greek, Jew, slave, free — all the "
"categories the world uses to sort and rank people mean nothing in Christ. Here, Christ is "
"all, and in all. You are not defined by your background, your nationality, your failures, "
"or your past. You are defined by the One who created you and is now renewing you.\n\n"
"This means you can stop trying to recover the old you. There is no better version hiding "
"behind your history. There is a new self being made in the image of God — and that is "
"who you truly are. Let Him complete the work.\n\n"
"You can trust Him because He who began a good work in you will carry it to completion. "
"He is not tired of renewing you. He is faithful to finish.\n\n"
"You are being made new. That work is underway right now.\n\n"
"Father, thank You that You are still renewing me — that I'm not finished and neither are You. "
"I put on the new self today and let go of every old label that tries to define me. I am "
"being made in Your image, and I trust You to complete what You started. Amen."
),

"26-04": (
"God's heart toward you is this — He doesn't want His Word to be something you visit occasionally. "
"He wants it to live in you, move through you, and overflow into everything you do.\n\n"
"He is a God who speaks, and His Word is alive. Colossians 3:16 says let the word of Christ "
"dwell in you richly. Not briefly. Not just on Sunday morning. Richly — deep and full, like "
"a river that fills every room it enters. When the Word dwells richly in you, it does not "
"just inform your mind. It shapes your conversations. It flows into how you teach your kids, "
"encourage your friends, and handle the hard moments in your week.\n\n"
"A life soaked in Scripture sounds like something. It sounds like songs of gratitude. It "
"sounds like wisdom offered at the right moment. It sounds like truth spoken with grace "
"into a conversation that needed it. The overflow of a Word-filled life touches every person "
"around you — not through performance, but through presence.\n\n"
"This is what God is building in you. Not just knowledge about Him, but His living voice "
"taking up residence in your heart and coming out in your life. Let His Word move in. "
"Give it room. Feed on it. Sing it. Teach it. Live it.\n\n"
"You can trust Him because His Word has never returned empty. Every promise He has made "
"through it has been kept. It is alive, and it is powerful, and it is working in you.\n\n"
"Let His Word be at home in you today. Let it fill and overflow.\n\n"
"Father, I invite Your Word to dwell in me richly. Fill me with the voice of Christ — "
"in my mind, my heart, my conversations, and my songs. Let every part of my life overflow "
"with what You've spoken. Your Word is alive in me, and I am grateful. Amen."
),

"27-04": (
"God's heart toward you is this — your real life is not what the world sees. It is hidden "
"safely in God, raised with Christ, and secure in a place nothing can touch.\n\n"
"He is a God who raises the dead — and He raised you with Christ. Colossians 3:1-3 says if "
"you have been raised with Christ, seek what is above, where Christ is. Not because earthly "
"things don't matter, but because where your life is kept matters most. You died with Christ. "
"Your old life ended at the cross. And now you are raised with Him — which means your real "
"home, your real source, and your real identity are seated with Him at the right hand of God.\n\n"
"This world will try to pull your attention down. Financial pressure, comparison, fear about "
"the future — all of it competes for the focus of your mind. Seek things above means you "
"don't let those things be your deepest reality. You anchor yourself to what is unshakeable "
"— to Christ, enthroned and victorious — and you live from that place.\n\n"
"Your life is hidden with Christ in God. Hidden. Protected. Secure. The enemy cannot get "
"to your real life because it is locked away in the safest place in existence. What he sees "
"is the surface. What you truly are is hidden in God.\n\n"
"You can trust Him because He is the one who holds your life hidden in Himself. Nothing "
"that happens today can reach what is kept in God.\n\n"
"Set your mind on things above. Your life is there, and it is safe.\n\n"
"Father, thank You that my real life is hidden with Christ in God. I am raised with Him and "
"my heart is set on what is above. Nothing the world throws at me can touch what You hold "
"for me. I live today from that secure and risen place — in You, with You, because of You. Amen."
),

"28-04": (
"God's heart toward you has no fine print. No small letters at the bottom that say 'only if "
"you're good enough.' His love was written in full before you could earn a single word of it.\n\n"
"He is a God who moves first. Romans 5:8 says God demonstrates His love for us in this — while "
"we were still sinners, Christ died for us. Not after you got it together. Not after you "
"cleaned up your act or proved you were worth the effort. While you were still in the middle "
"of the mess. That word 'while' is everything. It means He didn't wait. He didn't hold His "
"love in reserve until you showed up worthy. He gave it all before you could qualify.\n\n"
"That kind of love doesn't make sense by human logic. We give love when it's returned. We "
"invest in people who show potential. But God demonstrated His love for people who were "
"actively turned away from Him — and He did it through the most costly gift imaginable. "
"This is not love that grades on a curve. This is love that threw out the grading system entirely.\n\n"
"You cannot out-sin the love that was given before your worst sin was committed. You cannot "
"wander far enough to outrun arms that were already stretched out on a cross for you. "
"Today — whatever you carry, whatever you've done, wherever you've been — you are loved "
"with a love that moved before you could.\n\n"
"You can trust Him because He proved it at the cross before you could prove anything to Him. "
"The evidence of His love is not in how you feel today. It is in what He already did.\n\n"
"His love is not waiting for you to deserve it. It is waiting for you to receive it.\n\n"
"Father, I receive Your love today — fully, without conditions. Thank You for loving me while "
"I was still a mess, before I could earn it or deserve it. Your love moved first, and it "
"covers everything. I rest in the love that proved itself at the cross. I am Yours. Amen."
),

}  # end of new_texts dict


def main():
    with open(DEVOTIONAL_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    devs = data["devotionals"]

    patched = 0
    for i, entry in enumerate(devs):
        date = entry.get("date", "")
        if date in new_texts:
            devs[i]["devotionalText"] = new_texts[date]
            patched += 1

    data["devotionals"] = devs

    with open(DEVOTIONAL_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Patched {patched} entries.")

    # Validate + report character counts
    print("\nCharacter counts for April entries:")
    for entry in devs:
        date = entry.get("date", "")
        if date.endswith("-04"):
            n = len(entry.get("devotionalText", ""))
            flag = "✓" if 1000 <= n else "⚠ SHORT"
            print(f"  {date}: {n} chars {flag}")


if __name__ == "__main__":
    main()
