#!/usr/bin/env python3
import json

DECEMBER_REWRITES = {
    "01-12": {
        "title": "The Upgrade Jesus Gave You",
        "devotionalText": "God's heart toward you was so committed to your transformation that He engineered His own departure as the supreme gift. When Jesus said it is for your good that I go away, He wasn't abandoning the people who loved Him. He was trading one kind of presence for a better one.\n\nThe Greek word allos — another of the exact same kind. Not a substitute. Not a downgrade. The same quality of help, the same power that calmed seas and raised the dead, but with one world-changing difference: the Spirit would live inside every believer simultaneously, without limit, without distance.\n\nJesus was external — with them. The Spirit is internal — in you. Jesus was present for three years. The Spirit is present forever. Every decision you face today has a divine Counselor already present inside you. Every fear that whispers at 3am has the Spirit of truth already active to counter it.\n\nThis means you are never spiritually unequipped for what you're walking into. You have an Advocate — the same word used for a legal defender, someone who stands in your corner without condition.\n\nYou can trust this because Jesus staked His departure on the Spirit's arrival. He said it was better for you. The One who loved you to the cross gets to define better, and He called this better.\n\nStop operating like someone figuring it out alone. You have been inhabited by God Himself. That's not religious language — that's the most practical fact about your entire day.\n\nHoly Spirit, I receive You — not as a concept but as a Person alive within me. Today I stop striving in my own strength and lean into Yours. You are my Advocate, my truth, my ever-present companion. I am never alone. Amen. 💜"
    },
    "02-12": {
        "title": "Your Personal Master Class",
        "devotionalText": "God's heart toward you is so thoughtful that He didn't just save you and leave you to figure out the rest — He installed a Teacher inside you before you knew what questions to ask.\n\nThe Holy Spirit will teach you all things. Not some things. Not only the spiritual things. Not just the crises. All things — your calling, your marriage, the conversation you've been dreading, the decision that's been paralyzing you. He is qualified for every subject and never runs out of time for your specific situation.\n\nBut here's what most people overlook: the Spirit also promises to remind you. That means everything you've ever read, heard, or received from God is archived — stored with perfect precision, ready to be surfaced at exactly the moment you need it. The verse you memorized and forgot? Still filed. The truth that shifted something in you years ago? Still accessible. When you need it most, the Spirit pulls it up.\n\nThis is your advantage on the worst day. When you don't know what to do, you have a Teacher who does. When you've run out of wisdom, you have a Counselor with infinite supply. When circumstances are screaming, the Spirit is still speaking.\n\nYou can trust this because Jesus said plainly: I will not leave you as orphans. Orphans fend for themselves. You don't. You have a divine tutor present in every moment.\n\nToday is a classroom. The Teacher is already in session. He's not waiting for you to be more spiritual to begin.\n\nHoly Spirit, I come as Your student today. Teach me what I need to know and remind me of Your promises when I forget. I'm listening. Bring truth at exactly the right moment. Amen. 💜"
    },
    "03-12": {
        "title": "He Will Guide You Into All Truth",
        "devotionalText": "God's heart toward you is so generous that He didn't simply hand you a map — He sent a Guide to walk you personally into truth, step by step, for the rest of your life.\n\nThe Spirit of truth doesn't lecture from a distance. He guides. That word carries the image of someone walking beside you on a path — pointing out what you would have missed, steering you gently from what would have hurt you, making sure you don't get lost in the dark. This is not impersonal instruction. This is a Person walking with you.\n\nAnd notice what He guides you into: all truth. Not fragments. Not selective revelation for the spiritually advanced. Everything you need — for your relationships, your calling, your confusion, your grief, the area of your life that feels completely murky right now. Nothing is withheld from you.\n\nHe speaks only what He hears from the Father. Your Guide isn't improvising. He carries direct intelligence from the throne room of heaven and delivers it to you in plain language, at the right moment. When He speaks, you are hearing what God Himself says about your situation.\n\nYou can trust this because Jesus promised it before He left — not as an afterthought but as the central reason His departure would be worth it. The Spirit's guidance is your inheritance, fully purchased.\n\nYou are not wandering. You are not guessing. You have a Guide who doesn't get tired, doesn't miss details, and never loses the way.\n\nSpirit of truth, guide me today. Lead me into what I need to know. When I'm confused, I trust You to bring clarity. When the path isn't clear, I trust You to light it. You know the way — I'll follow. Amen. 💜"
    },
    "04-12": {
        "title": "Clothed With Power From on High",
        "devotionalText": "The disciples in Acts 1 had everything that human preparation could offer — three years of Jesus' teaching, personal miracles, the resurrection itself — and Jesus still told them to wait. The power that would make the mission possible had not yet arrived.\n\nBut you will receive power when the Holy Spirit comes on you. The word power is dunamis — the same root as dynamite, explosive capability, force that produces visible, tangible results. Not just inner peace or private spiritual experience. Power. The kind that moves things.\n\nAnd you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth. The scope is total. The witness begins where you are — Jerusalem, the city you live in — and moves outward to every boundary. Not a witness confined to religious spaces or religious conversations. A witness in the full movement of your life, in every place your feet carry you.\n\nThe word witnesses is martus — from which we get the word martyr. A witness in the ancient world was someone who testified to what they personally saw. Not what they were told. Not what they inferred. What they saw. The disciples had seen things that the world needed to hear about.\n\nYou have too. The power is not given for private use — it is given for witness. The Spirit who comes on you comes with a purpose larger than your personal spiritual life.\n\nWhere is your Jerusalem? Who in your immediate circle needs to hear what you've seen and what it has done in your life?\n\nHoly Spirit, come on me with power — not for my comfort only, but for witness. Let what I've seen and experienced in You become testimony that reaches the people around me. Empower me to be Your witness today. Amen. 💜"
    },
    "05-12": {
        "title": "The Power That Raised the Dead Lives in You",
        "devotionalText": "The most dramatic act of divine power in human history is not stored in a museum or restricted to a past age — the same power is alive inside you.\n\nRomans 8:11 makes a claim so large that the mind wants to deflect it: if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies because of his Spirit who lives in you.\n\nThe argument moves from the greater to the lesser. God accomplished the maximum demonstration of resurrection power — raising a body that had been dead for three days, restoring life to what was fully and completely over. If that was possible, what is the logic of the Spirit being insufficient for what is lesser than resurrection?\n\nYour weariness is lesser than death. Your sickness is lesser than death. Your discouragement, your depleted capacity, your sense that you have nothing left — all of it is lesser than what the Spirit has already overcome. The same power that defeated the final enemy is resident in your body, available in the present tense, giving life to your mortal frame.\n\nThis is not a metaphor for emotional encouragement. The Spirit gives life — actual, physical, tangible vitality — to your mortal body. Not eventually, not only at the final resurrection (though that too), but now. In this body. In this season.\n\nYou carry more power than you are accessing. The Spirit is not holding back. The question is whether you are living as though you have access to what He is.\n\nHoly Spirit, who raised Jesus from the dead — give life to my mortal body. I receive the resurrection power that is already present in me. What was sufficient to raise the dead is sufficient for what I'm facing. Amen. 💜"
    },
    "06-12": {
        "title": "Strengthened From the Inside Out",
        "devotionalText": "Most of what the world offers strengthens the outside — more knowledge, more resources, more connections, more influence. Paul prays for something that goes deeper than any of that.\n\nI pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being, so that Christ may dwell in your hearts through faith. The location is everything: the inner being. Not the outer performance. Not the visible presentation. The center — the deep place from which everything else flows.\n\nOut of his glorious riches — the supply that the prayer draws from is not modest. God's riches are glorious. The kind of inner strengthening Paul is asking for is not a small supplemental gift; it is drawn from an overflow. The inner person can be strengthened by power that goes so far beyond ordinary human resources that the comparison is almost embarrassing.\n\nSo that Christ may dwell — the strength and the dwelling are connected. As the inner being is strengthened, there is more room for Christ to take up real residence rather than nominal occupancy. Dwell is katoikeo — permanent settling in, furniture moved in, not visiting. The prayer is that Christ would make Himself fully at home in you.\n\nAnd as He does, you are rooted and established in love. The roots go down into a soil that cannot be shaken. The structure built on love can bear weight. The person who is rooted in Christ's love has a stability that circumstances cannot take away.\n\nYou are not built from the outside in. You are built from the inside out.\n\nFather, strengthen my inner person from Your glorious riches. Let Christ dwell fully in me, not just visit. Root me in love so deeply that no storm can uproot what You've established. Build from the inside. Amen. 💜"
    },
    "07-12": {
        "title": "More Than You Dare to Ask",
        "devotionalText": "You may think you are praying boldly — and God's capacity still exceeds it by a margin that cannot be measured.\n\nPaul closes the first half of Ephesians with a statement about God's ability that permanently reframes how you should approach prayer: now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us — to him be glory in the church and in Christ Jesus throughout all generations, for ever and ever! Amen.\n\nImmeasurably more than all we ask or imagine. The Greek here is hyperekperissou — beyond, over, above, the intensifier of an intensifier. Not just more than you ask. Not just more than you imagine. Beyond what you can ask or imagine, by a magnitude that escapes measurement.\n\nYour biggest prayer — the one you're almost afraid to pray because it feels too large — is still inside the category of things God can exceed. Your grandest vision — the one you hold privately because it seems absurd to say out loud — God's ability goes beyond it.\n\nAccording to his power that is at work within us. The resource is not external — it is the Spirit who is already inside you, already active, already working. The immeasurable capacity is not distant; it is resident. It operates from within.\n\nThis is why prayer is not primarily about changing God's mind or convincing a reluctant deity. It is about aligning yourself with what His power is already doing inside you and releasing it into your specific situations.\n\nPray bigger. Dream more audaciously. And then hold everything loosely, knowing His imagination for your life exceeds even your boldest version.\n\nFather, Your ability exceeds everything I ask or imagine. I ask bigger today — and I hold it loosely, trusting that what You have in mind is better than what I can conceive. Let Your power work within me and beyond everything I know to ask for. Amen. 💜"
    },
    "08-12": {
        "title": "A Word That Never Fails Its Errand",
        "devotionalText": "When God speaks, something always happens — and the word He has spoken over your life has not returned to Him without accomplishing its purpose.\n\nIsaiah 55:11 establishes a principle about the divine word that should reshape how you read Scripture: so is my word that goes out from my mouth: it will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it.\n\nNot return empty. The image is military — a messenger sent to deliver a message, authorized to execute whatever is required to complete the delivery. God's word doesn't come back and report: I tried, but conditions weren't right. It goes out with purpose and returns only when the purpose is accomplished.\n\nAs the rain and snow come down from heaven and do not return to it without watering the earth — the comparison is to a natural law. Rain does not hesitate over whether the ground deserves to be watered. It falls, it saturates, it produces the growth that the season requires. God's word operates with the same certainty as natural law, except with a purposefulness that natural law doesn't have. The rain falls. God's word accomplishes.\n\nThis has an immediate application to prayer. When you pray Scripture — when you take a promise and bring it into the specific situation you're facing — you are releasing a word that God has already committed to accomplishing. You are not trying to convince Him. You are partnering with a word that is already on its way.\n\nThe word God has spoken over your life has a destination. It will arrive.\n\nFather, Your word has gone out over my life and will not return empty. I speak it, I trust it, I stand on it — knowing it always accomplishes what You send it to do. What You have promised is on its way. Amen. 💜"
    },
    "09-12": {
        "title": "The Word Already In Your Mouth",
        "devotionalText": "Moses made it sound like obedience was impossible — a thing too far away, too high up, too deep down. And God's response was one of the most immediate corrections in all of Scripture.\n\nDeuteronomy 30:14 disrupts the human tendency to place spiritual life at an unreachable distance: the word is very near you; it is in your mouth and in your heart so you may obey it.\n\nVery near. Not requiring a climb, not requiring a descent, not needing you to cross a sea to retrieve it. The word that commands your obedience and enables your flourishing is already in you. In your mouth — accessible, ready to be spoken, present at the edge of your tongue. In your heart — not locked in an archive, but alive in the place from which your life flows.\n\nThis is the covenant logic of Deuteronomy. God was not building a religion of difficult, esoteric access. He was forming a people for whom the word of God would be so integrated into their lives — recited at meals, written on doorframes, spoken in the morning and the evening — that it would become part of the texture of their existence.\n\nThe apostle Paul quotes this verse in Romans 10 and applies it directly to the gospel: the word of faith is near you, in your mouth and in your heart. The nearness of the word is the nearness of salvation, the nearness of the God who speaks it.\n\nYou don't have to perform an elaborate search for the word you need today. It is very near you — in the Scripture you carry, in the Spirit who inhabits you, in the words of life that are already in your heart and at the edge of your tongue.\n\nFather, Your word is very near me — in my heart, in my mouth. I receive that nearness. I speak what is already in me. Your word is not far away, and neither are You. Amen. 💜"
    },
    "10-12": {
        "title": "Life and Death Are in the Choice Before You",
        "devotionalText": "God sets two things before every generation and asks every generation to choose — and the choosing has consequences that extend far beyond the individual.\n\nMoses, at the end of his life and the edge of the promised land, is making his final appeal to Israel. He has repeated the law, rehearsed the covenant, recounted what God has done. And now he names what it has always been about: I have set before you today life and prosperity, death and destruction. Now choose life.\n\nThe choice is presented as genuinely open. God does not predetermine what His people will choose — He presents the options with their outcomes and asks them to choose. This is the dignity He gives. Not puppets executing a pre-written script, but people invited into real moral agency with real consequences.\n\nChoose life so that you and your children may live and that you may love the Lord your God, listen to his voice, and hold fast to him. The life choice is not a single dramatic decision. It is the orientation of love, listening, and holding fast. Life is a relational direction, not a momentary act.\n\nThe blessing has a scope: you and your children. The choices you make about how you live toward God ripple outward. They create an atmosphere, a heritage, a way of life that children grow up inside. This is not guilt about failing your children — it is invitation to build something worth inheriting.\n\nFor the Lord is your life. Not a contributor to your life. Your life. He is the source, the sustainer, the content. Choosing life means choosing the One who is life.\n\nFather, I choose life — and I choose You who are life. I orient myself in love toward You, listening for Your voice, holding fast to You. Let the choice I make today be something worth passing on. Amen. 💜"
    },
    "11-12": {
        "title": "He Goes Before You Into the Fight",
        "devotionalText": "You are not the first person to walk into an impossible situation — and the One who went before every person before you is going before you too.\n\nMoses is speaking to Israel about the nations they are about to face. The people ahead of them are described as larger, stronger, and more powerful. The cities have walls up to the sky. By every rational military calculation, Israel should not win.\n\nAnd Moses says: the Lord your God, who is going before you, will fight for you, as he did for you in Egypt, before your very eyes.\n\nAs he did in Egypt — the instruction is backward-looking before it is forward-leaning. Before you face what is in front of you, look at what is behind you. The God who split the sea, who sent the plagues, who led with fire by night and cloud by day, who brought an entire nation out of the most powerful empire in the world — that God is the same God going before you now.\n\nHe goes before. Not beside only. Before — into the situation you are about to enter, ahead of your arrival, dealing with things that would be too much for you to walk into cold. By the time you arrive, the One who goes before you has already been working.\n\nYou saw how the Lord your God carried you, as a father carries his son, all the way you went until you reached this place. The wilderness years were not merely surviving — they were being carried. The same carrying is available at every new threshold.\n\nYou are about to enter something that feels too large. Go anyway. He has gone before you.\n\nFather, You go before me into what lies ahead. You fight for me the way You fought for Israel — not because I deserve it, but because You have committed to it. I go forward confidently, knowing You've been there already. Amen. 💜"
    },
    "12-12": {
        "title": "Never Alone in the Battle",
        "devotionalText": "The instruction God gives before the crossing of Jordan is not be brave — it is be strong and courageous, because I am with you. The presence is the basis of the courage.\n\nBe strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.\n\nMoses speaks this over Joshua before the entire assembly of Israel. Every person in the crowd knows the weight of what is being commissioned — they are about to enter Canaan, a land populated by nations who did not want them there, defended by cities with walls to the sky. The fear would have been completely rational.\n\nDo not be afraid or terrified because of them. The them is specific — the people on the other side of the Jordan. The forces visible, organized, and formidable. You are not commanded to pretend the threat isn't real. You are commanded not to let the real threat become the primary reality in your perception. The Lord your God goes with you — that reality is larger.\n\nHe will never leave you nor forsake you — five negatives in the Hebrew, stacked on each other for emphasis. Never, not ever, in any circumstance, will I abandon you or leave you to face this alone. The strongest possible grammatical construction in the Hebrew language, used to communicate the most personal possible promise.\n\nJoshua took the Jordan at flood stage. He marched around Jericho. He faced armies. Every time, the one who goes with never left. Every time, the courage commanded in this verse was sufficient because the promise behind it was real.\n\nYou are facing something. He is with you. That has not changed.\n\nFather, You never leave me or forsake me — the promise is absolute. I am strong and courageous not because the threats aren't real, but because You are with me, and You are larger than everything I face. Amen. 💜"
    },
    "13-12": {
        "title": "The Hope That Doesn't Embarrass",
        "devotionalText": "There is one promise in all of Scripture explicitly described as the anchor for your soul — and the anchor holds because of who is holding the other end.\n\nHebrews 10:23 is a command embedded in an explanation: let us hold unswervingly to the hope we profess, for he who promised is faithful. The holding is active — you participate in it. Unswervingly — without veering, without compromise, without letting circumstances create exceptions to the hope you have declared. The hope is not something you hold when conditions are favorable. It is something you hold when conditions are working against it.\n\nFor he who promised is faithful. This is the weight-bearing structure of the entire instruction. You can hold unswervingly not because of how strong your grip is, but because of who made the promise. Your hope is not based on your optimism or your spiritual determination. It is based on the character of the One who made the promise — and His character is described as faithful.\n\nFaithful — the Greek is pistos, reliable, trustworthy, the one who always delivers on what they say. God's faithfulness is not occasional. It is a permanent attribute. He cannot be unfaithful in the way that He cannot be unloving — it would require Him to stop being Himself.\n\nHope that is held unswerving, rooted in the faithfulness of God, is what Hebrews elsewhere describes as an anchor for the soul, firm and secure. Anchors don't prevent you from being in a storm — they keep you from being moved by it. The storm can rage. The anchor holds.\n\nYour hope is anchored in Someone who has never failed a promise in the history of the universe.\n\nFather, I hold unswervingly to the hope I profess — not because I'm strong, but because You are faithful. You have never failed a promise. My anchor holds, not because of my grip, but because of Yours. Amen. 💜"
    },
    "14-12": {
        "title": "The Assurance That Sees What Eyes Cannot",
        "devotionalText": "Faith is not the refusal to acknowledge what is difficult — it is the capacity to also see what is true beyond what is difficult.\n\nHebrews 11:1 has been translated many ways, but each translation points to the same core reality: now faith is confidence in what we hope for and assurance about what we do not see. Two dimensions. Confidence in what is hoped for — the forward dimension, the things that have not yet arrived, the promises still pending. And assurance about what is unseen — the present dimension, the realities that are operating right now but are invisible to physical sight.\n\nConfidence and assurance — these are not passive sentiments. They are active orientations. The person of faith doesn't simply feel hopeful; they reckon with the unseen as real. They factor the promises into their calculations alongside the visible facts. They live from a more complete picture of reality than what their eyes alone can provide.\n\nThis is what the elders were commended for — the heroes of faith listed in the chapter that follows. Abel, Enoch, Noah, Abraham, Sarah — each one is described as acting on something that wasn't visible yet. Building an ark when there was no rain. Leaving a homeland without knowing the destination. Looking for the city whose builder and maker is God.\n\nBy faith we understand that the universe was formed at God's command, so that what is seen was not made out of what was visible. The visible world was spoken out of invisible reality. Which means the invisible is the more fundamental of the two categories. Faith is not wishful thinking — it is alignment with what is ultimately most real.\n\nWhat does faith see in your situation that your eyes are missing?\n\nFather, give me the faith that sees what eyes cannot — the confidence in what is hoped for, the assurance about what is unseen. I align my perception with what is ultimately real. Your promises are more solid than what I see. Amen. 💜"
    },
    "15-12": {
        "title": "Without Faith, the Distance Stays",
        "devotionalText": "There is a prerequisite to every genuine encounter with God — and it is not moral perfection or spiritual achievement. It is faith.\n\nWithout faith it is impossible to please God. This is not a statement about legalism. It is a statement about the nature of relationship. A relationship cannot be real between two parties if one party is not convinced the other exists or is worth approaching. God is not honored by interaction that doesn't take Him seriously as a Person who is actually present and actually responsive.\n\nBecause anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him. Two objects of faith: His existence and His character as a rewarder. You must believe He is there — not just as an intellectual hypothesis but as a present reality you are actually addressing. And you must believe that what He does with those who seek Him is reward them — that the seeking is not futile, that the door you're knocking on will open, that the God you're coming to is genuinely good and genuinely responsive.\n\nEnoch walked with God — and God took him. This is the example Hebrews uses in context: a man whose life was such an uninterrupted exercise of faith that even his death was different. By faith he did not see death. The intimacy of the walk produced the intimacy of the transition. The pattern is the same: faith sustains the relationship, and the relationship produces its own rewards.\n\nThe distance between you and God is never on His side. It is always on the side of faith — whether it is there, and how far it reaches.\n\nFather, I believe You exist — not abstractly, but as the present, living God I am speaking to right now. And I believe You reward those who seek You. I come to You in that faith, expecting to be met. Amen. 💜"
    },
    "16-12": {
        "title": "The Same Yesterday, Today, Forever",
        "devotionalText": "The most stable thing in the universe is not the laws of physics — it is the character of God, and specifically the character He revealed in Jesus Christ.\n\nJesus Christ is the same yesterday and today and forever. This is the anchor of Hebrews 13:8 — and its context matters. The verse is nestled in a passage about the deaths of faithful leaders and the instruction not to be led astray by strange teachings. The point is this: leaders change, teachings vary, doctrines come and go, voices rise and fade — but Jesus Christ remains unchanged.\n\nYesterday — everything He ever was, every promise He ever made, every act of mercy He ever performed, every demonstration of power in history. All of it. Unchanged.\n\nToday — the Jesus who walked on water is the same Jesus at the right hand of the Father right now, interceding for you. The Jesus who healed the blind man is the same Jesus to whom you prayed this morning. His power, His compassion, His willingness, His love — exactly the same today as in the pages of the Gospels.\n\nForever — the Jesus of tomorrow is the same. Whatever you face in the future, whatever the circumstances of that day, the same Jesus will meet you there. He will not have changed. He will not have become less powerful, less willing, less compassionate, less present. Forever is the guarantee.\n\nThis is the most disruptive possible claim in a world of constant change. Everything shifts — your health, your relationships, your financial circumstances, your emotional state, your culture, your confidence. Everything. But the one Person who matters most is the one fixed point in the universe.\n\nJesus, You are the same — yesterday, today, forever. I anchor myself in Your unchanging character. What You were, You are. What You did, You can do. I trust the same Jesus today that every believer before me has trusted. Amen. 💜"
    },
    "17-12": {
        "title": "The Near One",
        "devotionalText": "James 4 describes two movements — yours and God's — and they are perfectly matched: one step toward Him produces one step from Him.\n\nCome near to God and he will come near to you. This is one of the simplest and most extraordinary promises in the letter of James. The asymmetry you might expect — God waiting for you to prove you're serious, God requiring an extended track record of faithfulness before He moves — is absent. One movement toward Him produces His movement toward you.\n\nThe verse is surrounded by humility language because James understands the root cause of distance from God: pride, self-sufficiency, the belief that you can manage without genuine dependence. God opposes the proud but gives grace to the humble. The person who believes they have no need of God's nearness is already in the posture that creates distance. The person who admits the need — wash your hands, purify your hearts, mourn and weep — is already beginning the movement.\n\nGrieve, mourn and wail. Change your laughter to mourning — this is not a call to permanent sadness. It is a call to genuine, not superficial, repentance. The kind that actually acknowledges what has happened and what it cost. And then: humble yourselves before the Lord, and he will lift you up.\n\nThe lifting is God's response to the humbling. You go down; He lifts. You draw near; He draws near. You take one honest step toward Him; He takes one toward you.\n\nThe distance between you and God is always shorter than it feels. One step is all it takes.\n\nFather, I draw near to You — honestly, humbly, without pretense. I trust that as I take this step, You take one toward me. Lift me up from every low place. I am coming near. Amen. 💜"
    },
    "18-12": {
        "title": "The Power Available in Ordinary Prayer",
        "devotionalText": "Elijah is offered as the proof that powerful prayer is not limited to extraordinary people — because Elijah was neither extraordinary nor spiritual by disposition.\n\nThe prayer of a righteous person is powerful and effective. Before you dismiss this because you don't feel righteous, James provides the clarification: Elijah was a human being, even as we are. That phrase — even as we are — is the entire point. The prophet who prayed and stopped rain for three and a half years, who then prayed again and the rain came — that man had the same emotional struggles you do.\n\n1 Kings shows us Elijah in the aftermath of his greatest victory, collapsed under a broom tree, asking to die, running from one woman's threat. He is described as a fugitive and a failure in his own estimation. This is the man James holds up as the example of powerful, effective prayer.\n\nRighteous in James's framework is not sinlessly perfect — it is the person who has been made right with God through faith, who is genuinely aligned with His purposes, who brings their real self to prayer rather than a managed performance. The prayer that is powerful is not the prayer that sounds most impressive. It is the prayer that is prayed in genuine trust by a person who actually believes they are talking to someone.\n\nElijah prayed earnestly that it would not rain, and it did not rain. He prayed again, and the heaven gave rain. The earnestness is the posture: genuine, engaged, believing prayer from a very human person.\n\nYour prayers are powerful. Not because of your spiritual credentials. Because of who you are praying to.\n\nFather, I pray as Elijah prayed — earnestly, honestly, as a human being who knows I'm talking to You. Let my prayers be powerful and effective. I believe You hear and You respond. Amen. 💜"
    },
    "19-12": {
        "title": "Born From Seed That Cannot Die",
        "devotionalText": "The life you have in Christ was not generated by a perishable seed — which is why it cannot end like a perishable thing.\n\nPeter draws one of the most clarifying contrasts in his first letter: for you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God. Two kinds of seed. Two kinds of life. Two very different outcomes.\n\nPerishable seed produces perishable life — human ancestry, biological generation, the kind of life that has a beginning and an end. Beautiful, significant, capable of extraordinary things — but ultimately bounded by time. Everything born of perishable seed will eventually perish. That is the nature of the category.\n\nBut the word of God is living and enduring. It is imperishable — aphthartou, incorruptible, immune to decay. When you were born again, you were born of this seed. The life generated in you at your new birth came from a source that cannot die. Which means the life it produced cannot die.\n\nFor all people are like grass, and all their glory is like the flowers of the field; the grass withers and the flowers fall, but the word of the Lord endures forever. Everything perishable fades — human achievement, human strength, human beauty. But the word stands. And the life produced by the word stands with it.\n\nThis is not just a promise about heaven. It has immediate implications for how you see yourself today. You carry an imperishable life inside your perishable body. What is most essential about you — the new creation, the born-again nature, the life that came from the living word — that is immune to what is destroying everything else.\n\nFather, I was born of imperishable seed — Your living and enduring word. The life You generated in me cannot die. I live from the imperishable today, not from what is fading. Amen. 💜"
    },
    "20-12": {
        "title": "What Royalty Looks Like in Ordinary Clothes",
        "devotionalText": "The most remarkable thing about 1 Peter 2:9 is not just what it says about who you are — it is that it was written to people who looked nothing like royalty from the outside.\n\nBut you are a chosen people, a royal priesthood, a holy nation, God's special possession. The recipients of this letter were scattered exiles, social outsiders, people for whom belonging was uncertain and status was precarious. And Peter says: let me tell you what you actually are.\n\nChosen — not accepted after evaluation, not approved after meeting a threshold. Chosen — selected before you qualified, called because of His will, not yours. A royal priesthood — two roles that were kept strictly separate in Israel, now fused in the people of Christ. You have the dignity of royalty and the access of a priest: authority and intimacy combined.\n\nA holy nation — in a world of competing national identities, you belong to a nation whose borders are invisible but real, whose King is the only King without a challenger, whose citizenship outlasts every empire.\n\nGod's special possession — peripoiesis, a treasured acquisition, something valued above all else and kept close. You are not a burden God tolerates. You are a possession He treasures.\n\nThe purpose: that you may declare the praises of him who called you out of darkness into his wonderful light. Once you were not a people, but now you are the people of God; once you had not received mercy, but now you have received mercy.\n\nThe darkness is behind you. The wonderful light is where you live. Declare it.\n\nFather, I receive who You say I am — chosen, royal, holy, Yours. I came out of darkness into Your wonderful light. Let me declare that today with everything I am. Amen. 💜"
    },
    "21-12": {
        "title": "From No People to God's People",
        "devotionalText": "Peter quotes Hosea to the scattered exiles who received his letter — and the move he makes collapses the distance between ancient promise and present reality.\n\nOnce you were not a people, but now you are the people of God; once you had not received mercy, but now you have received mercy. Hosea originally spoke these words over Israel during a season of devastating unfaithfulness — the nation had gone so far from God that the prophet was told to name his children Not-My-People and No-Mercy. The covenant seemed broken. The relationship seemed over.\n\nAnd then came the reversal. The same God who named them Not-My-People promised: I will call them 'my people' who are not my people, and I will call her 'my loved one' who is not my loved one. And in the very place where it was said to them, 'You are not my people,' they will be called 'children of the living God.'\n\nPeter applies this to Gentile believers — people who were categorically outside the covenant, who had no prior claim, who had never been included in the people of God. And he says: that reversal is your story. You were not a people. Now you are the people of God. You had not received mercy. Now you have received it.\n\nThe mercy that named Hosea's children is the mercy that named you. The same reversal that was promised over unfaithful Israel was enacted over the whole world in Christ. No-Mercy became Mercy. Not-My-People became My People.\n\nYou were not a people. Now you belong. That is the whole gospel in a sentence.\n\nFather, I am Your people — not by birth, not by achievement, but by mercy. The reversal Hosea promised is my story. I was Not-Your-People and now I am. I receive that mercy with wonder and gratitude. Amen. 💜"
    },
    "22-12": {
        "title": "Everything You Need, Already Given",
        "devotionalText": "Peter opens with a declaration that most Christians never fully inhabit: you already have everything you need for the life God has called you to.\n\nHis divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness. Given — past tense, completed. Not will give when you reach a certain level of spiritual maturity. Not is giving in proportion to your faithfulness. Given. The provision preceded the need.\n\nEverything needed — not most things, not the big important things. Everything. Every circumstance you face today has a corresponding provision already given through the knowledge of Him. The wisdom you need, the strength you need, the grace you need — these are not being held in reserve pending your qualification. They were given at your new birth.\n\nThrough your knowledge of him — which is why growing in the knowledge of Jesus is not an academic exercise. It is access to the provision. The more fully you know Him, the more completely you inhabit what has already been given. The provision doesn't increase — your access to it does.\n\nWho called us by his own glory and goodness. The calling was not neutral. It was motivated by His glory — the splendor of who He is — and His goodness — His determined orientation toward your flourishing. The same glory and goodness that called you are the same glory and goodness that provided everything needed for the life He called you to.\n\nYou are not lacking what the calling requires. You have been given what it requires. Receive it.\n\nFather, You have given me everything I need for godly life through knowing You. I stop reaching for external resources and receive what was already given. The provision is inside the knowledge. I want to know You more. Amen. 💜"
    },
    "23-12": {
        "title": "Partakers in the Divine Nature",
        "devotionalText": "Peter makes a claim in 2 Peter 1 that sounds almost too large to be Christian — and yet it is Scripture's own statement about what God has made you into.\n\nThrough these he has given us his very great and precious promises, so that through them you may participate in the divine nature, having escaped the corruption in the world caused by evil desires.\n\nParticipate in the divine nature — the Greek is koinonoi phuseos theias, literally a sharer in God's nature. Not a worshipper of God from a safe distance. Not a person whom God has agreed to help. A partaker — someone who shares in the actual nature of the divine.\n\nThis is the most intimate possible description of what the new birth produces. When the Spirit moved into you, He didn't just bring influence. He brought nature. The life of God — the holy, loving, righteous, faithful nature that is God's own essential character — was shared with you. Not all of it in the sense of omniscience or omnipotence. But the quality of it: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control — these are not behaviors you manufacture. They are expressions of a shared nature.\n\nHaving escaped the corruption — the nature you share is not the nature of the fallen world. The world's nature is characterized by corruption, by the relentless process of decay that sin set in motion. But the divine nature is incorruptible. You have been translated out of the decaying category into the eternal category.\n\nYou are not just improved. You are differently natured. That is what grace did.\n\nFather, I participate in Your divine nature — not just Your favor, but Your nature. I am differently natured now. Let that nature be evident in everything I do today. Amen. 💜"
    },
    "24-12": {
        "title": "What the Manger Proves About the Heart of God",
        "devotionalText": "The mystery of Christmas is not that God became man — it is that He did it this way: with nowhere to be born except a feeding trough, to parents no one important was watching, announced to shepherds who counted for nothing in the social order.\n\nJohn says it with staggering simplicity in his first letter: God is love. This is how God showed his love among us: He sent his one and only Son into the world that we might live through him. The love of God is not a theological abstraction. It is a historical event. It has a specific date and a specific address — Bethlehem, the reign of Herod, during a census.\n\nHe sent. The Father initiated. This is always the direction of the love — outward from God toward the world before the world turned toward Him. Not in response to your seeking. The sending preceded your awakening. Before you knew you needed to be found, God was already sending the One who would find you.\n\nHis one and only Son. Not a representative. Not a prophet. The Son — the One who was with God in the beginning, through whom all things were made, in whom was life and the light of all people. That is who was sent. That is the magnitude of what was given.\n\nThis is love: not that we loved God, but that he loved us and sent his Son as an atoning sacrifice for our sins. The origin is on His side. You didn't love first. He did. The manger before the mission. The birth before the baptism. The love before the response.\n\nGod went first. That is Christmas.\n\nFather, You loved first — before I was aware, before I could respond, before I deserved it. You sent Your Son into a manger to reach me. That love is the foundation of everything. Amen. 💜"
    },
    "25-12": {
        "title": "Love Made Complete in You",
        "devotionalText": "God has not just loved you — He has arranged for His love to be made complete inside of you, so that what He is becomes visible in what you are.\n\nIn this way, love is made complete among us so that we will have confidence on the day of judgment. John makes a striking claim about the mechanism of perfect love: it is completed in us. Not just received and stored. Not just believed as a doctrine. Completed — brought to its full expression — in the lives of people who receive it and let it flow through them.\n\nAs He is, so are we in this world. This phrase is one of the most audacious in the New Testament. As He is — meaning Jesus, at the right hand of the Father, perfectly loved and perfectly loving — so are we in this world. Not eventually. Not in the age to come. In this world. The quality of His being is the quality of our being in Christ, right now.\n\nThere is no fear in love. But perfect love drives out fear. The fear John has in mind is specifically the fear of judgment — the fear that on the day of reckoning, you will be found wanting. The person who is living in the love of God and expressing that love outward has nothing to fear on that day, because the love they have received and shared is itself the evidence of what God has done in them.\n\nWe love because he first loved us. The loving we do is not self-generated. It is an echo of what was first spoken over us. You love because love was first done to you.\n\nChristmas is the day God made the first move. Every act of love you have expressed since is a ripple from that stone thrown into the water.\n\nFather, Your love is made complete in me. I receive it fully and let it flow outward. There is no fear in love — and I live in the love that cast out fear. I love because You loved first. Amen. 💜"
    },
    "26-12": {
        "title": "Convinced Against All Contradiction",
        "devotionalText": "Romans 8:38-39 is not a comforting possibility — it is a conviction forged in the fires of real suffering by someone who had tested it.\n\nFor I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.\n\nI am convinced — the word is pepeismai, perfect passive, meaning I have been persuaded and the persuasion is still operating. Not: I hope. Not: I believe in theory. I am convinced. Past tense but still in force, the persuasion is settled and ongoing.\n\nWhat persuaded Paul? His biography: beatings, imprisonments, stonings, shipwrecks, hunger, nakedness, danger from rivers and robbers and religious authorities. He tested the promise under conditions designed to disprove it. And the love held. Every time. Across decades of costly ministry, the love of God that is in Christ Jesus continued to hold.\n\nNothing in all creation — the list he gives is comprehensive on purpose. He moves through categories of possible separators: death, life, angels, demons, present, future, powers, height, depth. Every category that might hold some separating force is named and dismissed. Will not be able — future tense, future certitude. The love will still hold in the future the way it has held in the past.\n\nYou are loved with a love that has been tested across the full range of human suffering and never found insufficient. Paul was not speculating. He was reporting.\n\nFather, I am convinced — as Paul was convinced — that nothing can separate me from Your love. The love You placed in Christ Jesus is the most durable force in existence, and I am inside it. Amen. 💜"
    },
    "27-12": {
        "title": "Every Perfect Gift Has the Same Address",
        "devotionalText": "James 1:17 is one of the most generous things Scripture says about every good thing that has ever happened to you.\n\nEvery good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.\n\nEvery. The scope is total. Not just the obviously miraculous gifts — healings, breakthroughs, answered prayers so specific they're hard to explain. Every good thing. The sunset that stopped you in your tracks. The unexpected kindness from a stranger. The relationship that has lasted for decades. The morning when you woke up and felt inexplicably at peace. The small thing that made a hard day bearable. Every single good thing has the same origin: the Father of lights.\n\nDoes not change like shifting shadows. The contrast is with the physical lights — sun, moon, stars — whose brightness shifts as the earth rotates and the seasons change. The Father of the heavenly lights is the source of all light, but unlike the sources themselves, He does not vary. His light does not dim. His goodness does not fluctuate with seasons or positions.\n\nHe chose to give us birth through the word of truth, that we might be a kind of firstfruits of all he created. The same God who gives every good gift also chose to give you new birth — not randomly, not reluctantly, but as the expression of His determined will. You are His firstfruits: the beginning of a new creation, a sample of what the whole restored creation will look like when it is finally redeemed.\n\nThe good things in your life are not coincidences. They have an address: the Father of lights.\n\nFather of lights, every good thing in my life came from You. I receive Your gifts with gratitude, knowing each one is evidence of Your goodness. You don't change — the goodness that gave me all this is the same goodness available today. Amen. 💜"
    },
    "28-12": {
        "title": "Lavished — The Word That Changes Everything",
        "devotionalText": "John does not say God offered love or gave love or made love available to us. He uses a different word entirely: lavished.\n\nSee what great love the Father has lavished on us, that we should be called children of God! And that is what we are!\n\nLavished — the Greek is dédoken, to give, but the word great in front of it and the context around it establishes the extravagance. Not measured love. Not proportional love. Lavished — the image of an overflowing outpouring, more than is strictly necessary, more than can be contained in a careful allocation.\n\nThe result of this lavished love is an identity: we should be called children of God. Not servants. Not citizens. Children — the intimate, organic, belonging relationship. And then John doubles down with an emphasis that is almost surprised-sounding: and that is what we are! He can't quite get over it. The designation is not just a title — it is a reality. You are actually, genuinely, in fact, truly the child of God.\n\nThe reason the world does not know us is that it did not know him. The world misread Jesus, missed who He was, failed to recognize the Father in the Son. It will do the same with you — fail to recognize in your redeemed life the evidence of the Father's lavished love. But that does not change what you are.\n\nDear friends, now we are children of God, and what we will be has not yet been made known. The now is secure. The future is open and glorious — but the now is sufficient. You are a child of God right now, in this ordinary December, with all your limitations and failures and uncertainties still intact.\n\nFather, You lavished love on me. I receive it — not measured, not proportional, but lavished. I am Your child. That is what I am. Amen. 💜"
    },
    "29-12": {
        "title": "What We Are Becoming Has Not Yet Been Shown",
        "devotionalText": "The child of God who reads this today is already extraordinary — and the extraordinary is not yet fully visible.\n\nDear friends, now we are children of God, and what we will be has not yet been made known. But we know that when Christ appears, we shall be like him, for we shall see him as he is. Everyone who has this hope in him purifies himself, just as he is pure.\n\nNow we are children of God — the present reality is established. The new birth happened. The Spirit moved in. The adoption was completed. You are a child of God right now, not eventually.\n\nWhat we will be has not yet been made known — which means the full expression of what you are is still coming. The new creation nature you carry in a mortal body is not yet fully visible. The glory that belongs to the children of God has not yet been fully revealed. You are, in a very real sense, a future thing living in the present — the fullness of what you are is still ahead.\n\nWe shall be like him — the transformation into Christ's image that began at your new birth will be completed when you see Him as He is. The seeing produces the being. Face to face with the One whose image you have been being conformed to, you will become fully what you have been becoming.\n\nEveryone who has this hope purifies himself. Hope has a present effect. The person who genuinely believes they are being made like Christ cannot remain comfortable with what contradicts Christ's character. The hope pulls forward. The future reality shapes present behavior.\n\nYou are not a finished product. You are an anticipated one. And the anticipation is glorious.\n\nFather, I am Your child now — and what I will be is more than I can imagine. I hold this hope and let it purify me today. I am becoming what I will be fully revealed as when I see Jesus face to face. Amen. 💜"
    },
    "30-12": {
        "title": "The Victory That Already Happened",
        "devotionalText": "The overcoming described in 1 John 5 is not a possibility waiting to be achieved — it is a fact waiting to be inhabited.\n\nFor everyone born of God overcomes the world. This is the victory that has overcome the world, even our faith. Who is it that overcomes the world? Only the one who believes that Jesus is the Son of God.\n\nOvercomes the world — in the present tense. This is not aspirational language about what may eventually happen if you persist in faith. It is a declaration about the nature of the life produced by new birth. The one born of God overcomes. The verb is present active indicative — happening now, characteristic of the one described.\n\nThe world in John's usage is the system organized in opposition to God — the patterns, the values, the powers that operate in resistance to the kingdom. The world has a way of pressing in, of asserting its authority, of convincing you that its categories are ultimate. Faith says otherwise.\n\nThis is the victory that has overcome the world, even our faith. Faith is not the mechanism by which you earn victory — it is the vehicle through which you inhabit the victory that Christ already won. Jesus said: I have overcome the world. He said it as a completed fact. Your faith connects you to His overcoming.\n\nWho is it that overcomes the world? Only the one who believes that Jesus is the Son of God. The overcomer's only qualification is faith in the identity of Jesus. Not impressive performance. Not accumulated spiritual victories. Belief — specifically, that Jesus is who He said He is.\n\nYou are born of God. You overcome. The world has no final claim on you.\n\nFather, I am born of You, and I overcome the world — not by my power but by the faith that connects me to Christ's victory. The world does not have the final word in my life. You do. Amen. 💜"
    },
    "31-12": {
        "title": "This Is Eternal Life — Right Now",
        "devotionalText": "John 17:3 is one of the most clarifying definitions of eternal life ever offered — and it makes eternal life available today, not only after death.\n\nNow this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent. Jesus is praying on the night before His crucifixion. He knows what is coming. And in the final night before the cross, He opens His prayer by defining the thing He is about to die to make possible: eternal life.\n\nAnd the definition is not heaven. Not immortality. Not the absence of death. Eternal life is that they know you. The knowing is the life. Relationship with God is not the means to eternal life — it is eternal life itself.\n\nKnow — the Greek is ginosko, the deeply personal knowledge that comes from direct encounter, from relationship, from experience over time. Not the knowledge of a textbook about God. The knowledge of a person who has been with God, who has been known by God, who carries in their own experience the accumulated weight of encounters with the living One.\n\nThe only true God — which establishes the uniqueness and the exclusivity of the source. Eternal life is not generally available through religious sincerity. It flows from knowing the specific God who is actually there, the one Jesus identifies as the One who sent Him.\n\nYou already have eternal life if you know Him. Not someday — now. The life that lasts forever is not something you begin at death. You began it the day you began to know Him.\n\nWhat if the goal of every remaining day was simply to know Him more?\n\nFather, this is eternal life — and I have it, because I know You. Not information about You, but You. I bring this year's end to the only thing that matters: knowing You more. Amen. 💜"
    }
}

# Load the JSON
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'r') as f:
    data = json.load(f)

# Apply rewrites
updated = 0
for i, d in enumerate(data['devotionals']):
    if d['date'] in DECEMBER_REWRITES:
        data['devotionals'][i]['title'] = DECEMBER_REWRITES[d['date']]['title']
        data['devotionals'][i]['devotionalText'] = DECEMBER_REWRITES[d['date']]['devotionalText']
        updated += 1

print(f"Updated {updated} December devotionals")

# Save back
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved successfully")
