#!/usr/bin/env python3
import json

FEBRUARY_REWRITES = {
    "01-02": {
        "title": "The Wall That Came Down From Inside",
        "devotionalText": "The hostility between human beings and God — and between human beings and each other — was not patched over by Jesus. It was demolished from the inside.\n\nIn the Jerusalem Temple, there was a literal stone wall — the soreg — that divided the Court of the Gentiles from the inner courts where Jews could enter. Inscriptions on the wall warned that any Gentile who crossed it would be responsible for their own death. The divide was architectural, legal, and religious all at once. This is the context behind Paul's words in Ephesians 2: Christ has made the two groups one and has destroyed the barrier, the dividing wall of hostility.\n\nBut He didn't destroy it by negotiation or compromise. He destroyed it in His flesh — by taking the law with all its condemnations and satisfying it completely on the cross. The thing that divided wasn't bigotry or misunderstanding — it was the legal weight of a covenant that created insiders and outsiders. Jesus fulfilled the covenant. The wall had no foundation left to stand on.\n\nHe himself is our peace. Not He gives peace. Not He teaches peace. He is it. The reconciliation between former enemies is not a policy He implemented — it's a reality that exists inside His own person. When you are in Christ, you are in the place where the war already ended.\n\nThis has profound implications for how you see people who seem separated from you — by culture, by background, by history, by present conflict. The hostility does not have the final word. Jesus already settled it. What remains is for those who are in Him to live from the peace He has become.\n\nYou carry the end of every war in your chest. Live that way.\n\nJesus, You are my peace — not a principle I aspire to, but a Person I am in. Every wall of hostility has been demolished in You. Help me live from the reconciliation You already accomplished, seeing every person through the eyes of what You made possible. Amen. 💜"
    },
    "02-02": {
        "title": "You Are Not a Visitor Here",
        "devotionalText": "You were not invited as a guest to something that belongs to someone else — you were made a full citizen of a kingdom that is now yours.\n\nIn the ancient world, the distinction between a citizen and a foreigner was enormous. A foreigner in a Roman city had no legal rights unless they were explicitly granted them. They couldn't own property, couldn't participate in civic life, couldn't claim the protections the city offered its citizens. To be a foreigner was to be permanently on the outside — present but not belonging.\n\nPaul writes to Gentile believers in Ephesus and tells them something that would have been almost incomprehensible: you are no longer foreigners and strangers, but fellow citizens with God's people and also members of his household. Two different images stacked on top of each other — not just citizenship rights, but family. Not just legal standing, but belonging.\n\nThe chief cornerstone that holds this structure together is Christ Himself. The apostles and prophets form the foundation — the testimonies and records through which God's purposes were revealed. But Jesus is the stone on which the whole thing aligns. Every other stone is positioned in relation to Him.\n\nAnd in this building, you are not a decorative addition or a late-arriving afterthought. You are built in — integral to the structure. The building rises to become a holy temple in the Lord, a dwelling in which God lives by His Spirit. You are part of the house that God lives in.\n\nYou don't belong on the periphery of spiritual life, watching through the glass while others enter. You have full citizenship. You have family membership. You are built into the foundation of something eternal.\n\nCome home to that today.\n\nFather, I am not a stranger — I belong. I am a fellow citizen, a member of Your household, built into something eternal alongside the apostles and prophets with Jesus as the cornerstone. I receive that belonging fully today. Amen. 💜"
    },
    "03-02": {
        "title": "The Secret That Was Kept Until Now",
        "devotionalText": "God had a plan that He kept hidden through ages of human history — and you are living in the era of its full unveiling.\n\nPaul calls it a mystery in Ephesians 3 — not in the sense of something confusing or cryptic, but in the technical theological sense: something kept hidden that has now been revealed. The prophets of Israel caught glimpses of it. They saw the nations included in the blessings of God — Abraham told he would be the father of many nations, Isaiah describing the servant who would be a light to the Gentiles. But the full form of it, the precise nature of the plan, was not made plain.\n\nUntil now. Through the gospel, Paul says, Gentiles are heirs together with Israel, members together of one body, and sharers together in the promise in Christ Jesus. Three togethers in a single sentence. Heirs together. Members together. Sharers together. Not adjacent to the blessings. Not receiving a similar but separate inheritance. Together — inside the same promise, the same body, the same inheritance.\n\nThe phrase in Christ Jesus is the key that unlocks all three. The union is not between Jew and Gentile as two groups deciding to cooperate. It's a union that exists inside a Person. Both groups are in Christ, and therefore they are in the same place at the same time — one body, one inheritance, one promise.\n\nYou have been included in something that was prepared before the foundations of the world. The mystery that was sealed in prior ages was unveiled on your behalf. You live in the era of the full revelation — the age when the wall is down, the family is expanded, and the inheritance belongs to all who are in Christ.\n\nYou are not lucky to be included. You were included on purpose, in the eternal counsel of God, before history began.\n\nFather, You kept this plan hidden through ages and unveiled it in Christ — and I am included in it. I am a fellow heir, a member of the one body, a sharer in the promise. This was Your design before time. I receive my full inheritance today. Amen. 💜"
    },
    "04-02": {
        "title": "Strengthened at the Root",
        "devotionalText": "Spiritual strength doesn't come from trying harder — it comes from being reinforced at a level deeper than effort can reach.\n\nPaul's prayer in Ephesians 3 is one of the most layered and beautiful in all of Scripture. He asks God to strengthen the Ephesians with power through His Spirit in their inner being — and the location matters enormously. Not in their theology. Not in their behavior patterns. Not in their external disciplines. In their inner being — the center from which everything else flows.\n\nThe image that follows is architectural: that Christ may dwell in your hearts through faith. The word for dwell here is katoikeo — not a temporary visit but a permanent settling in. Christ doesn't stay in your life the way a houseguest does, picking up after a few days. He takes up residence. And when He does, He moves things around. What is rooted and established in love begins to grow.\n\nPaul's prayer is that this inner strengthening would create room for more of Christ, which creates more love, which creates more capacity for what comes next — grasping the dimensions of love that surpass knowledge. Width. Length. Height. Depth. Four spatial directions, but none of them are directions you navigate to find Him. They are dimensions you discover as He expands within you.\n\nThis is why external behavior change is so exhausting and short-lived. You can discipline the surface without touching the root. But when God strengthens the inner person — when Christ really settles in, when love becomes the established foundation — everything above the surface changes because the roots are different.\n\nYou don't need more willpower. You need deeper roots.\n\nFather, I ask for what Paul asked — power through Your Spirit in my inner being. Strengthen me at the root. Let Christ settle fully into the center of my life. And as He takes up more residence, let love become the foundation from which everything else grows. Amen. 💜"
    },
    "05-02": {
        "title": "The Love You Can't Outrun",
        "devotionalText": "There is a love operating in your direction right now that is wider than your worst failure, longer than your lifetime, higher than your worst moment, and deeper than any wound you carry.\n\nPaul prays something almost absurd in Ephesians 3:18-19. He asks that the Ephesians would have power to grasp how wide and long and high and deep is the love of Christ. Power to grasp. Why would grasping something require power? Because the love in question is so much larger than the human capacity to receive it that ordinary perception is not enough. Your emotional and intellectual capacity for understanding love is smaller than the love you're being asked to comprehend.\n\nThe four dimensions Paul names — width, length, height, depth — map onto virtually every dimension of human experience. When love is wide, it covers what extends to the sides of your life — the breadth of your sin, the scope of your failure. When it is long, it extends through time — to your past that you'd rather not see and your future that is still unknown. When it is high, it surpasses — it rises above every low moment, every degradation, every thing that tried to reduce you. When it is deep, it goes below the surface — into the places no one sees, the wounds that formed in the dark.\n\nAnd then the paradox: to know this love that surpasses knowledge. You cannot fully know it cognitively. You can only experience it. The love of Christ keeps exceeding every attempt to contain it in a concept.\n\nThe goal of grasping this is being filled to the measure of all the fullness of God. Not just knowing about God — actually being filled with His fullness. That is what love this large does when you let it in.\n\nFather, open my capacity to receive what is too large for me to comprehend. I want to be filled to the measure of Your fullness — which requires a love I can't outthink, only receive. Fill me with Your love in every direction. Amen. 💜"
    },
    "06-02": {
        "title": "Beyond the Ceiling of Your Imagination",
        "devotionalText": "Every prayer you've ever prayed, every dream you've ever carried, every hope you've ever held — God is not limited to the ceiling of any of them.\n\nPaul closes the first three chapters of Ephesians with a doxology — a burst of praise — and the anchor of it is a statement about God's capacity that should permanently rearrange how you pray: He is able to do immeasurably more than all we ask or imagine, according to His power that is at work within us.\n\nBreak that down carefully. All we ask — every prayer, every request, everything you've ever brought to God. All we imagine — every vision, every dream, everything you've dared to hope for in your quiet moments. Immeasurably more than all of that. The word immeasurably is a Greek intensifier that essentially means beyond anything you could measure or quantify. It's not twice as much as you asked. It's not ten times. It's beyond the scope of measurement.\n\nAnd then the stunning qualifier: according to His power that is at work within us. The limitation is not God's willingness — it's the degree to which His power is at work in us. This is not a transaction between a hesitant God and a persistent human. This is an infinitely capable God whose ability operates through willing hearts.\n\nThis doesn't mean every prayer is answered the way you expect. What it means is that God's actual plans for your life are larger than your best imagination of them. When you feel like you're dreaming small, you're still dreaming smaller than what God has prepared. When you're asking boldly, you're still asking for less than what He's able to do.\n\nPray bolder. Dream larger. And then hold everything loosely, knowing His imagination for your life is larger than yours.\n\nFather, You are able to do immeasurably more than I ask or imagine. I bring my biggest prayers today — and I trust that Your plans make them look small. Expand what I ask for. Expand what I dare to imagine. And let Your power at work in me be the engine. Amen. 💜"
    },
    "07-02": {
        "title": "Worthy of the Calling You Didn't Earn",
        "devotionalText": "You did not choose this calling — it chose you. And the life that reflects it is not one you perform toward God, but one you receive from God.\n\nPaul is writing from prison when he delivers this instruction. Chains on his wrists, confined by Roman authority — and he calls himself a prisoner for the Lord. That reframing is itself a demonstration of what he's about to say. He urges the Ephesians to walk in a manner worthy of the calling they've received, and the first characteristic he names is humility.\n\nHumility is not thinking less of yourself. It is thinking accurately about yourself — knowing both what you are in your natural state and what you have been made in Christ. It is the posture that makes space for God to be God. Gentleness follows — the strength that does not need to prove itself. Patience — the capacity to stay steady when things are not moving at your preferred speed. And bearing with one another in love — which is the work nobody talks about but everyone knows they need.\n\nThe unity Paul calls them to maintain is not something they create. It already exists — the Spirit has already made them one. The belt that holds it together is peace. Their job is not to manufacture oneness but to guard what is already there.\n\nIn a world that defines worthiness by achievement and status, this calling runs in the opposite direction. The worthy life is the humble one. The life that honors God is not the impressive one — it's the one marked by gentleness and patience and bearing with people even when it costs you something.\n\nYou have been called. Not because you qualified. Called — which means He initiated it, He sustains it, He defines what walking in it looks like.\n\nFather, I walk in the calling You gave me — not by striving to be impressive, but by being humble, gentle, patient, and bearing with others in love. The calling is Yours. The walking is mine. Help me live in a way that honors what You initiated. Amen. 💜"
    },
    "08-02": {
        "title": "One, Not Many",
        "devotionalText": "The unity of the church is not a goal to achieve — it is a reality to inhabit. The Spirit has already done the joining.\n\nPaul stacks seven ones in Ephesians 4:4-6 like a creed meant to settle something that keeps being unsettled. One body. One Spirit. One hope. One Lord. One faith. One baptism. One God and Father. Every fractious tendency in the Corinthian and Ephesian churches — every personality cult, every doctrinal dispute, every preference-driven division — crashes against these seven ones.\n\nThe logic is simple and relentless: if there is one Spirit dwelling in all believers, then the division between believers is always artificial. You may be separated by language, culture, denomination, or personal history, but the same Spirit who lives in you lives in the person across the room. The theological word for this is koinonia — fellowship, participation in something shared. You cannot share the Spirit and genuinely be divided at the foundation.\n\nOne hope — which means the future you are moving toward is the same future they are moving toward. Not parallel futures for different categories of Christian. The same future, because the same Lord is guiding both trajectories toward the same completion.\n\nOne God and Father of all — Paul adds three phrases: over all, through all, in all. He is sovereign over the whole body. He works through each part. He inhabits every member. This is the architecture of unity that no human schism can permanently override.\n\nYou may have real disagreements with other members of the body. Pursue reconciliation anyway. The unity the Spirit has created is more fundamental than any difference human beings can generate.\n\nFather, You are one, the Spirit is one, and Your body is one. I stop contributing to division and start honoring the unity Your Spirit has already established. Where I am at odds with other believers, give me the humility and love to pursue what You've already created. Amen. 💜"
    },
    "09-02": {
        "title": "Precisely Gifted for the Work",
        "devotionalText": "Your spiritual gift was not assigned at random — it was apportioned by Christ Himself, sized exactly for the contribution He designed you to make.\n\nThe Greek word behind apportioned in Ephesians 4:7 is emétrésen — to measure and distribute in specific portions. Not randomly. Not equally by quantity. Each one of us received grace — gift-grace — measured and given according to Christ's wisdom about what each person needed to carry out their unique role in the body.\n\nPaul describes some of the specific gifts Christ gave: apostles, prophets, evangelists, pastors, teachers. He's not exhaustive here — he's pointing to a category of gift focused on equipping. These gifts aren't for the people who hold them to become spiritual celebrities. They exist to equip God's people for works of service — to build up the body of Christ.\n\nThis flips the church economy completely. The people with prominent gifts don't exist to be served by those without — they exist to serve and equip those without. The apostle exists so that other people function better as ambassadors. The teacher exists so that other people know how to think and live from Scripture. The gift is given for distribution, not accumulation.\n\nAnd you have been apportioned something. Christ, having ascended and filled all things, gave gifts to His people — and the gifts are working. Your particular grace-gift is not a minor thing. It is precisely measured for your role in the body, and the body does not work as well without it.\n\nYou are not just a consumer of other people's gifts. You carry one. The measure you received was chosen by the same Christ who fills all things.\n\nJesus, You apportioned my gift personally. I receive it — not as a burden but as a trust. Show me how to use what You've measured out for me, so that the body is built up and Your work gets done. Amen. 💜"
    },
    "10-02": {
        "title": "Growing Up, Not Growing Restless",
        "devotionalText": "Spiritual maturity is not an arrival point — it is the direction of movement toward a fullness that only Christ defines.\n\nPaul paints a picture in Ephesians 4:13-14 that has two poles. On one end: unity in faith, knowledge of the Son of God, maturity, the whole measure of the fullness of Christ. On the other end: spiritual infancy, being tossed back and forth by waves, carried by every wind of new teaching, vulnerable to the cunning of those with deceptive schemes.\n\nThe image of the infant tossed on the waves is vivid and uncomfortable because it's recognizable. Every believer has gone through seasons of that — where the newest voice you heard reshaped everything, where every compelling teacher created a new wave of enthusiasm followed by the next wave of doubt, where your spiritual center felt like it was located somewhere else each week.\n\nMaturity doesn't mean having every question answered. It means knowing who Jesus is well enough that your identity stays rooted when questions come. It means your knowledge of the Son of God has become personal — not just doctrinal content to defend, but a living relationship that holds you stable in the storm.\n\nSpeaking the truth in love is the mechanism Paul names for growth. Not just truth. Truth in love. And not just love. Love in truth. Both together — because truth without love cuts, and love without truth flatters. The combination is what actually builds up, which is the goal: growth in every way into Him who is the head, into Christ.\n\nYou are not supposed to stay where you started. You are meant to grow. Not frantic, waves-driven movement — but the steady upward movement toward the fullness of the One you follow.\n\nJesus, I want to know You more — not just know more about You. Let that deepening knowledge be the anchor that keeps me stable when waves come. Grow me in every way into You. Amen. 💜"
    },
    "11-02": {
        "title": "Take Off What No Longer Belongs",
        "devotionalText": "You have a new self — and the problem isn't that you haven't become it yet. The problem is that you keep dressing in clothes that don't belong to you anymore.\n\nPaul uses the language of clothing in Ephesians 4:22-24: put off your old self, be made new in the attitude of your minds, and put on the new self. The structure reveals something important about how transformation works. There is putting off. There is renewal of the mind — a transformation that happens at the level of thinking and perceiving. And there is putting on.\n\nThe old self is described as being corrupted by its deceitful desires. The word corrupted is phtheiromenon — present passive participle, indicating ongoing corruption. The old self keeps corrupting itself more deeply the longer it is indulged. It is not static — it deteriorates. What feels like maintaining the status quo in spiritual life is actually slow deterioration.\n\nBut the new self is created to be like God in true righteousness and holiness. Not striving to become like God through moral effort. Created to be like God — a new nature, a new origin, a fundamentally different kind of person than what the old self was.\n\nThe renewal of the mind is the hinge. The mind operating from old categories — from deception, from the distorted logic of the flesh — produces old-self behavior even when you want new-self outcomes. But when the mind is renewed, when you start seeing reality the way Christ sees it, you naturally put on the new self because it fits.\n\nYou are not trying to become something you aren't. You are learning to live consistently with something you already are.\n\nFather, I put off what no longer belongs — the old self that keeps corrupting. Renew my mind. Let me see reality the way You see it, so that putting on the new self becomes natural. This is who I am now. Amen. 💜"
    },
    "12-02": {
        "title": "The Truth That Holds the Body Together",
        "devotionalText": "Community is only as strong as the honesty that runs through it — and God designed truth and love to be inseparable.\n\nPaul's instruction in Ephesians 4:25 begins with therefore — connecting it to what came before. Because you have put off the old self and put on the new. Because you are members of one body. Therefore, put off falsehood and speak truthfully to your neighbor.\n\nFalsehood is one of the old self's native languages. The flesh protects itself with half-truths, manages others' perceptions with what is technically accurate but practically deceptive, maintains comfortable lies that keep conflict at bay at the cost of genuine relationship. The body of Christ cannot function this way. A body where the parts misrepresent their condition to each other is a body that cannot respond to what is actually happening.\n\nThe anger instruction that follows is precise: in your anger do not sin, and do not let the sun go down while you are still angry. This is not a prohibition on anger. Anger at injustice, at abuse, at the suffering of the vulnerable — that is right and appropriate. But unresolved anger overnight becomes fertile ground for the enemy. It hardens. It calcifies into bitterness. What started as a righteous response becomes a foothold — a place the enemy can stand in your life and work from.\n\nThe connection between truth-telling and anger management is intentional. Often we carry unresolved anger because we haven't been honest — with ourselves, with the person who wronged us, with God about what we actually feel. Truth, spoken in love and spoken soon, keeps the roots of bitterness from forming.\n\nYou are part of a body. Your honesty — or your lack of it — affects more than just you.\n\nFather, I choose truth — spoken in love, spoken to people's faces, spoken before the sun goes down. Help me resolve what is unresolved. I don't want to give the enemy a foothold. Let truth be what holds this body together. Amen. 💜"
    },
    "13-02": {
        "title": "Transformed From Taker to Giver",
        "devotionalText": "The gospel doesn't just change what you do — it reverses the direction your life flows in.\n\nPaul's instruction in Ephesians 4:28 is one of the most practical in the letter. Someone who used to steal should steal no longer. But Paul doesn't stop at the prohibition. He doesn't just say stop taking — he redirects the whole energy: work with your hands so that you have something to share with those in need.\n\nThis is a complete reversal of orientation. The taking life flows inward — acquiring, consuming, accumulating for self. The giving life flows outward — producing, working, generating so there is something to share. The person is the same person. The hands are the same hands. But the direction of the river has changed.\n\nThis is not just about theft in the legal sense. Any approach to life where your primary orientation is receiving — extracting from relationships, from community, from God — is a version of the taking life. The gospel reorients you toward the giving life: working, producing, contributing, sharing. Not because generosity earns favor with God, but because the transformation that has happened in you has changed what you are for.\n\nPaul immediately connects this to words: do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs, that it may benefit those who listen. The same principle applies to your speech. Words can be extractive — using other people's stories for your entertainment, tearing down to feel more elevated, taking from the emotional economy of those around you. Or they can be constructive — offering what the person in front of you actually needs.\n\nWhat does your daily presence add to the people around you?\n\nFather, transform me from a taker to a giver — in my work, in my words, in my presence. What I have is for sharing, not hoarding. What I say is for building up, not tearing down. Let generosity be the new direction of my life. Amen. 💜"
    },
    "14-02": {
        "title": "The One Who Sealed You and Stayed",
        "devotionalText": "You didn't just receive God's Spirit — you were marked by Him with a seal that tells the universe you belong to someone who will not let you go.\n\nIn the ancient world, a seal was not decorative. It was a mark of ownership, of authority, of guarantee. A sealed jar of grain belonged to the person whose seal was pressed into the clay. A sealed letter carried the authority of the one who stamped it. When Paul says you were sealed with the Holy Spirit for the day of redemption, he is using the most serious language of ownership and guarantee available in his culture.\n\nYou have been marked. The day you came to faith in Christ, the Holy Spirit was placed inside you as an unbreakable seal — God's way of saying: this one is Mine. Not a temporary arrangement. Not a deposit held in escrow until you perform well enough to keep it. A seal for the day of redemption — the moment when everything God started will be completed and you will be fully transformed into the image of His Son.\n\nDo not grieve the Holy Spirit. This phrase reveals something breathtaking — the Spirit can be grieved. He has feelings. He responds to your choices. Bitterness, rage, anger, slander, malice — these are specifically named as things that grieve Him, not because He becomes angry with you, but because they contradict the nature He's trying to express through you. You grieve a Spirit of love when you live in hatred. You grieve a Spirit of peace when you live in wrath.\n\nBut notice: griefed does not mean gone. The seal holds. Even when you grieve Him, He does not leave. He stays, sealed to you, working from the inside to call you back toward what you were sealed for.\n\nHoly Spirit, You are sealed to me — and I don't want to grieve You. I release every root of bitterness, every form of anger that has hardened into sin. Be at home in me. Live freely in me. Amen. 💜"
    },
    "15-02": {
        "title": "Beloved Children Learning to Love",
        "devotionalText": "You don't love because you're trying to become like God — you love because you already are His child, and love is the family trait.\n\nThe opening words of Ephesians 5 shift everything: follow God's example, therefore, as dearly loved children. The model is imitation — but the motivation is identity. You are not imitating God to earn the designation 'beloved.' You already are beloved. The imitation flows from that — a child naturally learns to walk the way their parent walks, to speak the way their parent speaks, to respond to the world the way their parent does.\n\nChrist's love is the specific template Paul points to: He loved us and gave himself up for us as a fragrant offering and sacrifice to God. Two movements in His love. First, He loved — the internal reality, the settled posture of His heart toward you. Then, He gave himself up — the external expression, the costliest possible offering. The love preceded the sacrifice, and the sacrifice showed the world what the love was made of.\n\nA fragrant offering. The Old Testament sacrifices that were accepted by God were described as a pleasing aroma — a fragrance that reached the Father. Paul is saying that when Christ gave Himself for you, it was not a grim transaction. It was a beautiful offering, made in love, received with delight by the Father who had ordained it.\n\nWhen you love this way — giving yourself for others at personal cost, not because you have to but because you want to — you are participating in the same kind of offering. Your life lived in love becomes a fragrance. Not because you performed perfectly, but because you are His child, following His example, doing what love does.\n\nFather, I am Your dearly loved child. Because of that, I follow Your example in love — not trying to become someone You'll love, but expressing the love I've already received. Let my life be a fragrant offering. Amen. 💜"
    },
    "16-02": {
        "title": "You Are What You Were Made From",
        "devotionalText": "Before you were darkness — and now you are light. Not a light-carrier. Not someone who occasionally reflects light. You are light, because you are in the One who is.\n\nPaul makes a distinction in Ephesians 5:8 that is easy to miss because of its grammar. He doesn't say you were in darkness but now you are in the light. He says you were darkness, but now you are light in the Lord. The darkness was your nature. The light is your nature now. Not your location — your identity.\n\nThis changes the entire framing of spiritual struggle. If you are merely in the light but your nature is still darkness, then every moral failure is just your nature expressing itself. But if you are light — if light is what you have been made into in Christ — then sin is not an expression of who you are, it is a contradiction of who you are. You are not a dark thing trying to behave like a light thing. You are a light thing that sometimes acts inconsistently with your nature.\n\nLight produces fruit: goodness, righteousness, and truth. These are not behaviors you manufacture — they are the natural outputs of light operating in its proper function. When you walk as a child of light, these things grow. Not because you're trying harder, but because you're functioning as what you are.\n\nFind out what pleases the Lord — have nothing to do with the fruitless deeds of darkness, but rather expose them. Light exposes darkness not by attacking it but simply by being present. You don't have to fight your way through darkness. You just have to show up as what you are.\n\nYou are light. Every room you walk into changes because of what you carry.\n\nFather, I am light in You — not because I became good enough, but because You remade my nature. Let me function as what I am — producing goodness, righteousness, and truth — simply by being who You made me. Amen. 💜"
    },
    "17-02": {
        "title": "Wake Up to What Day It Is",
        "devotionalText": "There are people walking through their lives entirely asleep — and God's call to you is to live with your eyes fully open to the eternal weight of every moment.\n\nThe quotation Paul uses in Ephesians 5:14 — wake up, sleeper, rise from the dead, and Christ will shine on you — echoes imagery that runs through the prophets. Isaiah describes a day when the dead awaken, when the nation comes alive again, when the long night gives way to light. Paul applies it to believers who are drifting through life in spiritual sleepiness.\n\nIt is possible to be alive in Christ and still be asleep in your living. To go through the motions of faith without any sense of the eternal stakes around you. To drift with the current of your culture, absorbing its values, pacing your days by its rhythms, making decisions shaped by its logic — all without ever being shaken awake to what is actually happening.\n\nBe very careful then how you live — not as unwise but as wise, making the most of every opportunity, because the days are evil. The word for making the most is exagorazo — to redeem, to buy back. The time you have is being spent regardless. The question is whether you are spending it as someone who knows its value or someone who has been lulled into thinking it doesn't matter much.\n\nMaking the most of the time does not mean being frantically productive. It means being awake — awake to what God is doing around you, awake to the people He has placed in your path, awake to the moments that have eternal weight because of how you respond to them.\n\nChrist shines on those who wake up. His light meets your open eyes.\n\nJesus, wake me up — to the reality of what is happening around me, to the eternal weight of ordinary moments, to the opportunities I've been sleepwalking past. I want to live with open eyes. Shine on me as I rise. Amen. 💜"
    },
    "18-02": {
        "title": "The Fullness That Nothing Else Provides",
        "devotionalText": "You were made with a capacity for fullness that wine cannot reach, that entertainment cannot reach, that success cannot reach — only the Spirit can fill what you were built for.\n\nThe contrast Paul draws in Ephesians 5:18 is sharper than it sounds. Do not get drunk on wine. In Corinth and Ephesus, wine was the primary vehicle for altered experience — the social lubricant, the temporary relief from the weight of life, the shortcut to feeling something different than what your circumstances produced. But it leads to debauchery — the Greek word asotos describes a life of reckless abandon, unmoored from any sense of direction or purpose.\n\nInstead, be filled with the Spirit. The Greek construction is present passive — meaning this filling is not a one-time event but a continuous state of receiving. You don't get filled once and stay full. You live in a posture of ongoing filling, continually receiving what only the Spirit can provide.\n\nThe overflow of this filling is distinctive. Singing psalms, hymns, and spiritual songs. Making music from your heart to the Lord. Giving thanks always for everything in the name of Jesus Christ. These are not disciplines that produce the filling — they are the natural result of a life that is filled. A person who is full of the Spirit cannot help but express it in some kind of song, some kind of gratitude, some kind of overflow.\n\nWine gives you a counterfeit fullness that empties you more. The Spirit gives you a genuine fullness that multiplies. Everything the flesh goes looking for in artificial alteration — release, joy, connection, transcendence — the Spirit provides in a way that doesn't leave you emptier in the morning.\n\nCome hungry. Come thirsty. Be filled with the only thing that actually satisfies.\n\nHoly Spirit, fill me. Not just once — continuously. I open myself to receive what only You can give. Let the evidence of Your fullness overflow from me in gratitude and song and a life that has genuine joy at its center. Amen. 💜"
    },
    "19-02": {
        "title": "Out of Reverence, Not Resentment",
        "devotionalText": "The mutual submission Paul calls for in Ephesians is not a power structure — it is a posture of love, motivated entirely by reverence for Christ.\n\nThe command in Ephesians 5:21 is often pulled apart from what follows — but it is the foundation: submit to one another out of reverence for Christ. Mutual. Everyone. Not one group permanently above another and one permanently below. Out of reverence for Christ — which means the motivation is not hierarchy or social order or even common sense. It is love for Jesus, expressed in how you treat the people around you.\n\nThe specific applications Paul gives — wives and husbands, children and parents, employees and employers — are not illustrations of one-directional power. They are examples of the mutual posture expressed in different relational contexts. In each pair, both parties are being called to something. The person in the culturally dominant position is called to the most radical sacrifice.\n\nHusbands, love your wives just as Christ loved the church and gave himself up for her. The standard is the cross. Not general affection. Not reasonable kindness. Self-giving, self-emptying, the kind of love that puts the beloved's flourishing above your own comfort. A husband who loves this way is not exercising power — he is surrendering it.\n\nThe entire section is bounded by the same reality: Christ and His love for the church. Marriage is meant to be a living parable of that love — imperfect and limited, but pointed in the right direction, oriented by the most extravagant example of self-giving love the world has ever seen.\n\nIn every relationship you are in, the question is not what am I owed. It is how can I give what Christ gave.\n\nJesus, I choose submission — to You first, and then in love to the people You've placed in my life. Not from obligation but out of genuine reverence for You. Let Your cross be the posture of every relationship I'm in. Amen. 💜"
    },
    "20-02": {
        "title": "Suited Up For the Battle That's Already Won",
        "devotionalText": "You are not fighting toward victory — you are fighting from it. The armor is not for winning; it is for holding the ground that Christ already won.\n\nPaul's instruction in Ephesians 6:10 is precise: be strong in the Lord and in his mighty power. Not in your own strength. Not in your spiritual history or your accumulated experience. In the Lord. The strength is His. The mighty power is His. Your role is to be in Him — and while you are in Him, His strength is available.\n\nThen comes the diagnosis that changes everything about how you fight: our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.\n\nThis is why so much human conflict is exhausting and fruitless. You are wrestling with people — the coworker, the family member, the political opponent — and all the while the real battle is happening at a level your eyes can't see. The person in front of you is not your enemy. They are, at worst, being influenced by the actual enemy. And when you treat them like an enemy, you're doing the spiritual enemy's work for him.\n\nPut on the full armor of God so that you can take your stand. Not advance — stand. The battle Christ has already won needs to be maintained in your daily life. The enemy doesn't lose ground unless someone stands in the territory Christ purchased. Your prayers, your faith, your choosing truth over deception — these are acts of warfare. Not because the outcome is uncertain, but because the enemy disputes the territory until someone enforces the outcome.\n\nYou are dressed for a battle where the verdict is already in. Stand firm in that.\n\nFather, I put on Your armor and stand — not in my strength but Yours. I see the real battle clearly: not against people, but against spiritual forces. Arm me for what is actually happening, and let me hold the ground Christ won. Amen. 💜"
    },
    "21-02": {
        "title": "Piece by Piece, Fully Covered",
        "devotionalText": "Every piece of God's armor exists for a reason — and together they cover every angle the enemy attacks from.\n\nA Roman soldier in Paul's day would have been immediately familiar with the items he lists. The belt of truth held everything together — a loose belt meant a vulnerable soldier, everything liable to shift at the wrong moment. The breastplate of righteousness protected the vital organs — the heart and lungs, the places where a wound kills. The shoes of the gospel of peace meant you moved forward without losing footing — preparation, stability, the ability to hold your ground without slipping.\n\nThe shield of faith was specifically designed for the flaming arrows — darts dipped in pitch and set on fire. In first-century warfare, a volley of these could set an entire formation of shields ablaze. But a shield soaked in water could extinguish every one. Faith extinguishes the fiery darts of the enemy — the accusations, the doubts, the fear-laden thoughts that arrive like arrows in the dark.\n\nThe helmet of salvation protects the mind — which is exactly where the enemy concentrates his attacks. Identity attacks, memory attacks, anticipatory fear, present shame — all of these target your mind. Wearing the helmet of salvation means operating from the certainty of who you are and what Christ has done, not from the uncertainty of what the enemy whispers.\n\nThe sword of the Spirit — the word of God — is the one offensive weapon in the list. Jesus used it in the wilderness when the enemy tested Him: it is written. Not clever argument. Not emotional appeal. The word. The sword that doesn't break.\n\nYou don't need to improvise your defenses. God has already designed every piece. Put it all on.\n\nFather, I put on every piece of Your armor today — truth, righteousness, peace, faith, salvation, and Your word. Cover every angle the enemy attacks. I stand fully protected, fully equipped, fully covered in You. Amen. 💜"
    },
    "22-02": {
        "title": "The Battle That Runs on Prayer",
        "devotionalText": "All the armor in the world is insufficient without the activity that animates it — and that activity is prayer.\n\nIt's not coincidental that Paul places the instruction about prayer immediately after describing the armor. The armor is the posture. Prayer is the life flowing through it. A soldier fully equipped but not in communication with the commanding officer is in danger — disconnected from orders, from intelligence, from coordinated strategy. Prayer is the communication that keeps everything alive.\n\nPray in the Spirit on all occasions. Not just during formal prayer times. Not just in crisis. On all occasions — which means prayer is meant to be the environment you live in, not the emergency number you call when things go wrong. All kinds of prayers and requests — specific, general, interceding for others, crying out for yourself, thanking, confessing, listening.\n\nBe alert. Stay watchful. The instruction implies that there are things happening around you that you will miss if you are spiritually asleep. Prayer keeps you alert — attuned to what the Spirit is doing, sensitive to what the enemy is attempting, aware of what people around you are carrying even when they can't articulate it.\n\nKeep on praying for all the Lord's people. This is intercessory prayer — carrying other members of the body in your prayer. Paul himself asks for prayer: that whenever I speak, words may be given me so that I will fearlessly make known the mystery of the gospel. The apostle who planted churches across the empire needed other people's prayers. Nobody is self-sufficient in the battle.\n\nYour prayers are not a spiritual obligation. They are real, live communication with the God who acts.\n\nHoly Spirit, I pray in You — alert, persistent, for all the Lord's people. Not just in crisis but continuously. Open my awareness to what needs intercession. Use my prayers to accomplish what only prayer can accomplish. Amen. 💜"
    },
    "23-02": {
        "title": "The Blessing You Can't Lose",
        "devotionalText": "Peace, love, faith, grace — these are the words Paul leaves the Ephesians with, and they are not wishes. They are descriptions of what is already flowing from the Father toward everyone who loves Christ.\n\nThere is something significant about how a letter ends. In the ancient world, the closing words were often the distilled intention of the writer — the thing they most wanted to linger in the minds of the recipients after the letter was read aloud and put away. Paul closes Ephesians with these words: peace to the brothers and sisters, and love with faith from God the Father and the Lord Jesus Christ. Grace to all who love our Lord Jesus Christ with an undying love.\n\nPeace — not the world's peace, which depends on circumstances cooperating. The peace of God that guards hearts and minds, that surpasses understanding, that remains when the situation hasn't changed. Love with faith — the two realities that most completely describe the life of God given to His people. You are loved, and you have been given the capacity to trust the One who loves you.\n\nAnd then: undying love. The phrase for undying in the Greek is en aphtharsia — incorruptible, imperishable, unable to decay. Paul describes the love that faithful believers have for Christ as imperishable. Not that your love is perfect. Not that it doesn't fluctuate. But that at its root, the love that was born in you by the Spirit has a quality that doesn't die.\n\nYou can trust that what was started in you is not fragile. The undying love you have for Christ is evidence of the undying love He first had for you. Love begets love. Grace generates grace.\n\nYou are covered from both ends — His love reaching toward you, and the love He placed in you reaching toward Him.\n\nFather, I receive the peace, love, faith, and grace You send to those who love Christ. I love Him with all I have — and I trust that what is true love in me is imperishable because it came from You. Amen. 💜"
    },
    "24-02": {
        "title": "The Exchange That Changed Everything",
        "devotionalText": "You are no longer the person who is trying to live for God — you are the person God is living through.\n\nPaul's statement in Galatians 2:20 is one of the most radical reframings of personal identity in all of Scripture. I have been crucified with Christ and I no longer live, but Christ lives in me. There are two death certificates and one new life packed into a single sentence.\n\nFirst death: the old self — the person you were in Adam, under sin's authority, defined by failure and striving and the endless gap between who you wanted to be and who you were. That person was crucified with Christ. Not killed in isolation — co-crucified. Your death was joined to His death so that your resurrection could be joined to His resurrection.\n\nSecond: I no longer live. The one who has been trying to maintain standing before God through personal effort, who has been carrying the weight of his own spiritual management — that person no longer exists as the subject of your life. You are not the center of your own story anymore.\n\nBut then: Christ lives in me. Not Christ influences me. Not Christ helps me when I ask. Lives in me. The risen Christ, who has all authority in heaven and earth, has taken up permanent residence in the person you now are. The life you live is His life, expressed through your specific body, your particular context, your individual relationships.\n\nThe life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me. Not vague religious faith. Faith in a specific Person who loved you personally and acted on it specifically. The cross was for you — not humanity in abstract, but you. His love chose you before you could choose Him.\n\nLive from that exchange. You are not alone in the effort. You are the vessel of a living Christ.\n\nJesus, You live in me. I stop straining to live for You and start trusting You to live through me. The life I now live belongs to the One who loved me and gave Himself for me. Amen. 💜"
    },
    "25-02": {
        "title": "Free Enough to Give Yourself Away",
        "devotionalText": "Christ set you free — not so you could protect your freedom, but so you could spend it on others.\n\nThere's a tension built into Galatians 5 that resolves beautifully when you see it clearly. It is for freedom that Christ has set us free — stand firm and do not be burdened by a yoke of slavery. Freedom is serious. Non-negotiable. Something worth protecting and defending.\n\nAnd then, twelve verses later: do not use your freedom to indulge the flesh; rather, serve one another humbly in love. The whole law is summed up in a single command: love your neighbor as yourself.\n\nSo freedom is not an end in itself. It is the condition that makes genuine love possible. A slave cannot love freely — they act under compulsion. A person under the yoke of law cannot love freely — they act from obligation. But a person who has been liberated from both compulsion and obligation can do something remarkable: choose to give themselves away.\n\nThis is what makes Christian service fundamentally different from every other kind. When you serve others from legal obligation — because the rules require it — you resent it quietly. When you serve from guilt — because you feel you should — you are performing for relief. But when you serve from freedom — because you have been loved extravagantly and that love is overflowing outward — it doesn't deplete you. It is the expression of who you are.\n\nYou are free. Fully, completely free — free from the law's condemnation, free from the flesh's slavery, free from the enemy's claim. That freedom is a resource. Spend it on the people around you.\n\nJesus, You set me free for this — not to hoard my freedom but to spend it in love. I choose to serve out of freedom, not obligation. Let Your love that freed me be the same love that flows through me toward others. Amen. 💜"
    },
    "26-02": {
        "title": "The Secret to Not Giving In",
        "devotionalText": "The way to stop gratifying the flesh is not to fight it harder — it's to walk closer.\n\nPaul's instruction in Galatians 5:16 is the most practical piece of spiritual warfare in the letter, and it works by a completely counterintuitive logic: walk by the Spirit, and you will not gratify the desires of the flesh. Not: fight the flesh harder. Not: resolve more strongly to resist. Walk by the Spirit. The Spirit's presence crowds out the flesh's opportunity.\n\nThe conflict Paul describes is real. The flesh desires what is contrary to the Spirit, and the Spirit what is contrary to the flesh. They are in constant opposition. You feel this. The pull toward what you know is wrong. The reluctance toward what you know is right. The gap between the person you want to be and the person you find yourself being on a difficult Thursday.\n\nBut Paul doesn't say to win the fight. He says to walk. Step by step, following the Spirit's lead, staying in rhythm with His promptings. The image is of someone keeping pace with a guide — not running ahead into trouble, not falling behind into old territory, but matching the guide's pace through unfamiliar country.\n\nThe person who is led by the Spirit is not under law. This is the release. The law says: here are the boundaries, do not cross them. The Spirit says: here is life, follow Me into it. The difference is not the destination — it's the motivation and the resource. Under law you manage your distance from sin by willpower. Under the Spirit you follow the one who naturally leads you away from sin and into life.\n\nStop fighting. Start following. The Spirit will take you where the flesh can't follow.\n\nHoly Spirit, I choose to walk by You — step by step, decision by decision, moment by moment. I stop trying to fight flesh through willpower and start following You through every situation. Lead me into life. Amen. 💜"
    },
    "27-02": {
        "title": "The Fruit That Grows Itself",
        "devotionalText": "You cannot manufacture love, joy, peace, or patience. But you can be the kind of soil in which the Spirit grows them.\n\nThe word fruit in Galatians 5:22 is not accidental. Paul had just described the works of the flesh — a list of behaviors produced by effort and desire aimed at the wrong things. And then he shifts categories entirely: but the fruit of the Spirit. Not the works of the Spirit. Not the achievements of the Spirit. The fruit.\n\nFruit doesn't strain. An apple tree doesn't labor to produce apples. It bears fruit because of what it is connected to — the root system, the soil, the water, the sun. When those connections are healthy, fruit is the natural result. When you are connected to the Spirit of God, the same process operates. Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control — these grow from the inside of a life that is genuinely rooted in the Spirit.\n\nThis means the absence of these qualities is not primarily a behavioral problem. It is a connection problem. When you are anxious instead of peaceful, or unkind instead of gentle, or inconsistent instead of faithful, the question is not how do I try harder to produce peace and kindness. The question is: what is interfering with my connection to the Spirit who naturally produces these things?\n\nAgainst such things there is no law. There is no law that says you have too much love or too much peace. No ceiling on the fruit. And those who belong to Christ Jesus have crucified the flesh — they have positionally ended the flesh's claim over their life through their union with the One who died to the flesh.\n\nStay connected. Stay rooted. The fruit takes care of itself.\n\nHoly Spirit, produce Your fruit in me. I stop straining and start staying — connected to You, rooted in Your love, abiding in the life You give. Let everything on Your list grow freely in the soil of my surrendered life. Amen. 💜"
    },
    "28-02": {
        "title": "The Rhythm of the Surrendered Life",
        "devotionalText": "Since we live by the Spirit — that's the starting point. Not a goal. A fact. And a fact that demands a response.\n\nPaul's closing argument in Galatians 5 has a since that carries the weight of everything that came before. Not if we live by the Spirit — not maybe or hopefully. Since. The Spirit is the source of your life in Christ. He is what animates the new nature, what connects you to the Father, what produces the fruit, what leads you away from the flesh and into life. That is already your reality.\n\nGiven that — keep in step with the Spirit. The image is military: soldiers marching in formation, matching each other's pace, moving in coordinated rhythm. But the command here is not to march in step with the person beside you — it is to match the Spirit's pace. His rhythm. His timing. His direction.\n\nThis is practical. When the Spirit prompts you to pray, stay in step and pray. When He prompts you to reach out to someone, stay in step and reach out. When He leads you away from a situation that would compromise you, stay in step and move. The opposite of keeping in step is not standing still — it is running ahead in your own energy or lagging behind in your own fear.\n\nAnd then: let us not become conceited, provoking and envying each other. These specific failures — pride, provocation, envy — are symptoms of a life that has stopped keeping step with the Spirit and started comparing itself to other people. Comparison is always a sign that you've lost your rhythm.\n\nIf someone is caught in a sin, restore gently. Bear each other's burdens. This is what a body in step looks like — aware of each other, helping each other, moving together toward the same destination.\n\nHoly Spirit, I keep in step with You — matching Your pace, following Your lead, staying in Your rhythm. Remove comparison and pride. Let me walk with others in genuine burden-sharing and gentle restoration. This is the life. Amen. 💜"
    },
    "29-02": {
        "title": "The Law That Never Has an Exception",
        "devotionalText": "You can deceive people. You can deceive yourself. But there is one listener you will never deceive — and He watches what you plant, not what you perform.\n\nPaul opens Galatians 6:7 with a warning that sounds almost jarring after everything he's said about grace. Do not be deceived: God cannot be mocked. A man reaps what he sows. The word for mocked is mukterizo — to turn up your nose at, to sneer at, to treat with contempt. You cannot treat God's moral laws as if they don't apply to you and escape the consequences. The universe is not neutral. It has a built-in, divinely maintained feedback system.\n\nWhoever sows to please the flesh, from the flesh will reap destruction. The flesh is not just sexual sin — it is any orientation of life that seeks satisfaction, security, or significance from something other than God. The person whose entire life is pointed at acquiring comfort, status, pleasure, or control — that person is sowing to the flesh even if they're outwardly religious. And the harvest is destruction — not as divine punishment inflicted, but as natural consequence harvested.\n\nWhoever sows to please the Spirit, from the Spirit will reap eternal life. Every prayer prayed. Every act of generosity given in secret. Every time you chose truth over convenience, love over ease, faithfulness over immediate reward — these are seeds. And they grow in hidden soil, in the economy of a God who does not forget.\n\nLet us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. The harvest has a timing that is not yours to determine. Your job is to keep sowing in faith that the proper time is coming.\n\nFather, I sow to the Spirit today — knowing the harvest is Yours to time. I won't grow weary in good work. Every seed planted in faith is a seed You will bring to harvest. I trust the law that You built into all things. Amen. 💜"
    }
}

# Load the JSON
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'r') as f:
    data = json.load(f)

# Apply rewrites
updated = 0
for i, d in enumerate(data['devotionals']):
    if d['date'] in FEBRUARY_REWRITES:
        data['devotionals'][i]['title'] = FEBRUARY_REWRITES[d['date']]['title']
        data['devotionals'][i]['devotionalText'] = FEBRUARY_REWRITES[d['date']]['devotionalText']
        updated += 1

print(f"Updated {updated} February devotionals")

# Save back
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved successfully")
