#!/usr/bin/env python3
import json

JANUARY_REWRITES = {
    "01-01": {
        "title": "Mercy That Doesn't Remember Yesterday",
        "devotionalText": "God's compassions are not recycled — every morning you wake up to mercy that has never been used before.\n\nThere is a moment the prophet Jeremiah reaches in Lamentations that most people overlook. He is sitting in the rubble of Jerusalem, surrounded by destruction he helped warn against and nobody listened. He has watched the city burn. He has buried people he loved. And yet, right in the middle of this devastated lamentation, something breaks open. He writes: because of the Lord's great love we are not consumed.\n\nNot were not consumed — are not. Present tense. Right now, in the middle of all this ruin, God's compassions are holding him together. And then he adds the detail that changes everything: they are new every morning.\n\nThat means this morning — this specific morning — there is fresh mercy available to you. Not leftover mercy from someone else's answered prayer. Not recycled compassion God used on your behalf last Tuesday. New mercy, made this morning, for you. The same way the sun doesn't borrow yesterday's light, God doesn't dispense yesterday's grace.\n\nThis is not sentiment. Jeremiah discovered this truth while sitting in the wreckage of everything going wrong. That's the testimony — not that everything was fine, but that God's love was sufficient even inside catastrophe. His faithfulness is described as great, not small. Not barely enough. Great.\n\nYou don't have to earn today's mercy by having done yesterday right. You don't receive less because you failed last week. Every morning is a clean supply, and the supply is governed by great faithfulness, not by your track record.\n\nWhat feels depleted in you right now? What feels like it's been used up or worn out? Bring it to this: the God who calls Himself the Father of compassion has been up since before your alarm went off, preparing new mercy for this exact day. He already knows what you're walking into.\n\nFather, thank You for mercy that didn't carry over from yesterday — mercy made fresh for this morning. I receive it. Not because I've earned it, but because Your faithfulness is great and Your compassions are new. You are holding me together right now, and I trust You with today. Amen. 💜"
    },
    "02-01": {
        "title": "When God Says He's Starting Over",
        "devotionalText": "The God who made the universe has said something staggering about your life — He is making everything new.\n\nIn Revelation 21, the apostle John sees a vision so overwhelming that description nearly fails him. The old order is passing away. Heaven and earth are being made new. And from the throne itself, a voice breaks through — not a messenger, not an angel, but the One who sits on the throne — and says: I am making everything new.\n\nThen comes the detail that stops everything. God says: write this down. Why would the Creator of all things need to pause and make sure something gets documented? Because He knows us. He knows that in a month, in a year, when circumstances are still messy and hope feels thin, we will need something written down. Not a feeling. Not a memory. Something that exists on a page, in a book, preserved — because these words are trustworthy and true.\n\nThat phrase — trustworthy and true — is the backbone of this promise. It means the newness isn't wishful thinking. It's not God being optimistic about your situation while things quietly stay the same. It is the word of the One who spoke galaxies into existence, and He is speaking it over whatever has grown old and broken in your life.\n\nNew is one of God's native languages. He is not a God who patches and repairs and hopes for the best. He makes new. Not refurbished. Not restored to former glory. New. A quality that didn't exist before.\n\nMaybe what's old in you is a wound you've carried for years. Maybe it's a dream that has gone quiet. Maybe it's hope itself — the capacity to expect anything good. All of it falls under the same word: everything. He said He is making everything new.\n\nThe word is written down. It is trustworthy. It is true. Receive it today.\n\nLord, You are making everything new in me. I receive this promise not because circumstances have changed yet, but because You said it and You are trustworthy. I bring You the old — the worn out, the broken, the things I've stopped hoping about — and I trust You to speak new life over them. Amen. 💜"
    },
    "03-01": {
        "title": "The God Who Finishes What He Starts",
        "devotionalText": "The same God who began something in you has staked His faithfulness on completing it.\n\nPaul writes Philippians from prison. That detail matters. He is chained to a Roman soldier, his ministry interrupted, his freedom stripped away. And yet he writes with stunning confidence about the people he loves in Philippi: he who began a good work in you will carry it on to completion until the day of Christ Jesus.\n\nNotice the structure of that sentence. The confidence isn't based on the Philippians' consistency. It isn't conditioned on their performance or their faithfulness. The confidence is grounded entirely in the character of the One who started it. He began it. He will complete it. The subject of both verbs is God.\n\nThis is profoundly different from how we usually think about spiritual growth. We tend to imagine that God started something in us, and now it's our job to maintain it — to not lose ground, to keep showing up, to prove we're worthy of the investment. But Paul points to God as both the author and the finisher. Your transformation is not a project you've been handed and might botch. It's a work He initiated and has committed to completing.\n\nThe phrase \"until the day of Christ Jesus\" is the timeline. Not until you reach a certain spiritual milestone. Not until you've performed consistently enough. Until the day He returns. The work continues regardless of how messy the middle looks.\n\nYou may feel unfinished today. You may feel like you've been the same stuck version of yourself for too long. But unfinished is not abandoned. An artist working on a masterpiece looks like an unfinished canvas at every stage until it isn't. God is still working. His tools are still moving. His hands have not left this canvas.\n\nBe confident in this. Not in yourself — in Him.\n\nFather, I am confident — not in my ability to hold it together, but in Your faithfulness to complete what You started. I am still in process, and I trust You with the outcome. You don't abandon Your work. You finish it. Finish what You started in me. Amen. 💜"
    },
    "04-01": {
        "title": "The Engine Behind Your Wanting",
        "devotionalText": "The desire you feel to do what's right — that's not coming from you. God is already working.\n\nPhilippians 2 contains one of the most clarifying truths in all of Scripture about how spiritual transformation actually works. Paul tells the believers to work out their salvation with fear and trembling — and then immediately explains why this isn't as terrifying as it sounds: because it is God who works in you to will and to act in order to fulfill His good purpose.\n\nBreak that apart carefully. God works in your will — the part of you that wants, that desires, that chooses. When you find yourself genuinely wanting to forgive someone you have every human reason to resent, that desire is God working in you. When you feel drawn to pray when everything in you would rather not, that's not willpower — that's God. He is the engine behind your wanting.\n\nAnd then He works in your acting — giving you the power to follow through on what He's already stirred in you. Which means the gap between what you want to do and actually doing it is something He's committed to closing.\n\nThe phrase \"fear and trembling\" is not about cowering before an angry God. It's the reverent awareness that something eternal is happening in the ordinary moments of your life. Every choice is significant because a holy God is actively working through it. That sobers you without crushing you.\n\nThis reframes the entire experience of spiritual growth. You are not alone in the effort. You are not straining toward a God who is watching to see if you measure up. You are cooperating with a God who has already moved into the process, who is already working in your will and your actions, who is committed to seeing His good purpose accomplished through your life.\n\nStop working from your own reservoir. Let Him fuel the desire and provide the power. That was the design from the beginning.\n\nFather, You are at work in me — changing what I want, empowering how I act. I stop straining in my own strength and cooperate with what You're already doing inside me. Work in my will. Fulfill Your good purpose through my life. Amen. 💜"
    },
    "05-01": {
        "title": "Why God Chose the Ones Who Don't Qualify",
        "devotionalText": "God did not choose you in spite of your weakness — He chose you specifically because of it.\n\nThe church in Corinth was not impressive by any worldly measure. Paul knows this and says it directly: not many of you were wise by human standards, not many were influential, not many were of noble birth. He doesn't soften it. The people gathered in that community were not the power brokers or the celebrated. They were the ones the world had passed over.\n\nAnd then Paul makes the move that changes everything: but God chose the foolish things of the world to shame the wise. God chose the weak things to shame the strong. The lowly things, the despised things — He chose those.\n\nThis was not accidental. It was strategic. The logic is explicit: so that no one may boast before Him. God deliberately builds with materials the world has rejected so that when something extraordinary happens, the source cannot be misattributed. When the weak person does something that requires supernatural strength, nobody congratulates them on their natural ability. They look for another explanation. They find God.\n\nYour limitation is not a disqualifier. It is the precise context in which God's power can be most clearly displayed. The apostle Paul would later describe this as carrying treasure in jars of clay — common containers that make the surpassing value obvious. The clay doesn't become impressive. The treasure becomes undeniable.\n\nStop apologizing for what you don't have. Stop waiting until you feel qualified. The gap between what you can do and what God is calling you to is not a problem — it's the space where He shows up. The people God has always used most dramatically are the ones who had the clearest view of their own inadequacy.\n\nYou were chosen knowing every weakness you have. That was not an oversight. That was the point.\n\nFather, You chose me knowing every limitation and every weakness. I stop hiding them and start offering them. My inadequacy is the canvas for Your power. Use what I am to display what You are. Amen. 💜"
    },
    "06-01": {
        "title": "Everything You Need Is in One Name",
        "devotionalText": "God looked at everything you would ever need and placed it all inside a single person — Jesus.\n\nIn the ancient world, wisdom was the most coveted possession a person could have. Philosophers built schools around it. Kings paid fortunes to acquire it. To be called wise was the highest human honor. And righteousness — the state of being right before God and man — was something generations of priests had labored to maintain through endless sacrifice and ceremony.\n\nThen Paul writes to the Corinthians and collapses all of it into one sentence: it is because of Him that you are in Christ Jesus, who has become for us wisdom from God — that is, our righteousness, holiness and redemption.\n\nNot that Jesus taught wisdom. Not that He modeled righteousness. He became those things for you. He is your wisdom — meaning every time you are at a loss, every time the path is unclear, every time you don't know what to do, you are not without resource. You are in the One who is wisdom itself. You have direct access to the mind that made the universe.\n\nHe is your righteousness — meaning your standing before God is not a score you're accumulating, not a record you have to maintain. It's a person. And that person is perfect, seated at the Father's right hand, and you are in Him.\n\nHe is your holiness — meaning the sacred quality that separates you for God is not your track record of good behavior. It's the nature of the One you're inside.\n\nHe is your redemption — meaning what was lost has been bought back, not at a discount, but at the highest price ever paid.\n\nYou are not lacking. Whatever you need today, it's already in Him — and you're already in Him.\n\nJesus, You are everything I need. Wisdom when I'm lost. Righteousness when I feel unworthy. Holiness I couldn't earn. Redemption I couldn't afford. I am in You, and You have become all of it for me. That is enough. Amen. 💜"
    },
    "07-01": {
        "title": "The Only Boast That Holds",
        "devotionalText": "There is one thing worth boasting about — and it has nothing to do with what you've accomplished.\n\nPaul is addressing a church that has fractured over personalities. Some are claiming Paul as their leader, others Apollos, others Cephas. They are organizing their identity around human figures, measuring their spiritual standing by which teacher they follow. And into this pride-fracture, Paul drops a quote from Jeremiah: let the one who boasts boast in the Lord.\n\nThe context in Jeremiah 9 is devastating. God has just told Israel that He is about to judge the nation. And He identifies the things people typically boast about — wisdom, strength, riches — and says none of it will protect them in the day of reckoning. The only boast that stands is this: that you know and understand Me.\n\nNot that you've accumulated impressive theology. Not that you've achieved a spiritual résumé worth citing. That you know Him. That you've actually met the God who is present, who acts in history, who is faithful to His covenant.\n\nThis is a profound reorientation. The competitive Christianity that compares spiritual depth and ministry output and doctrinal precision misses the entire point. Your one boast is that you know the God who is worth knowing. And He's not a prize you've earned — He's a Person who chose you.\n\nThere's deep freedom in this. You're released from the exhausting work of maintaining an impressive spiritual record. You don't have to perform for the admiration of others or defend your spiritual credentials. You just know Him. And knowing Him is more than enough.\n\nWhat are you most tempted to build your identity around? Slowly, those things will shift and change and sometimes fail. But the God you know is the same yesterday, today, and forever. That's a boast that holds.\n\nLord, I release every other source of identity and confidence. My boast is not what I've done, not how spiritual I appear, not which camp I belong to. My boast is that I know You. And You are worth knowing. Amen. 💜"
    },
    "08-01": {
        "title": "Searched and Found",
        "devotionalText": "You don't have to figure out God — His Spirit has already gone into the deep places on your behalf.\n\nThe Spirit searches all things. That phrase in 1 Corinthians 2:10 is staggering in its implications. The Holy Spirit — the third person of the Trinity — actively, continuously searches the deep things of God. Not because there's something God is hiding from Himself, but because the Spirit's role is to explore the infinite depths of the Father's heart and then share what He finds with you.\n\nThink about what that means practically. The most profound truths about God's nature, His purposes, His thoughts toward you specifically — these are not locked in a vault you have to earn access to. The Spirit has already gone into those depths, and He lives inside every believer, carrying that searched knowledge with Him.\n\nPaul is making a contrast here. He says no one knows the thoughts of God except the Spirit of God. A person's innermost thoughts are inaccessible to another human — you can guess, you can infer, but you can't actually enter another person's mind. Now transpose that to God. His thoughts would be permanently hidden, permanently beyond reach — except that we have received the Spirit who has searched those very depths. The Spirit bridges the impossible distance.\n\nThis is why Scripture isn't just information. When you read it with an open heart, you're not receiving ancient religious text — you're receiving the searched-out things the Spirit brought back from the deep places of God and is now offering to you. The Spirit who knows His mind is the same Spirit revealing that mind to yours.\n\nYou don't have to feel far from God. The One who knows Him most intimately has already moved into you.\n\nHoly Spirit, thank You for going into the depths of God on my behalf. Open my heart to receive what You've searched out — the things God has prepared, the truths He wants me to know. I am not left to guess. You are my access to the heart of the Father. Amen. 💜"
    },
    "09-01": {
        "title": "Thinking With the Mind That Made Everything",
        "devotionalText": "The same mind that designed the cosmos has been given to you — and it's not just a metaphor.\n\nPaul asks the rhetorical question straight from Isaiah: who has known the mind of the Lord so as to instruct Him? The expected answer is obvious — no one. The gap between human reasoning and divine wisdom is so vast it's almost absurd to compare them. God's ways are higher than our ways, His thoughts higher than ours.\n\nAnd then, without pausing, Paul adds four words that completely overturn the question: but we have the mind of Christ.\n\nNot access to. Not proximity to. We have it. The mind of Christ — the mind that understood the Father perfectly, that saw every situation with eternal clarity, that knew what was truly happening beneath every surface appearance — that mind has been given to every person who is in Christ.\n\nThis doesn't mean you're suddenly omniscient. It means you have the capacity to receive divine perspective on any situation when you turn toward the Spirit who is living inside you. When Paul faced imprisonment and death, he had genuine peace because he was thinking from a different vantage point than his circumstances could provide. The mind of Christ gave him access to a perspective his natural mind couldn't reach.\n\nIn practical terms, this means you are not at the mercy of your own reasoning when decisions are hard, when confusion is thick, when you don't know what to do. You have access to clarity that transcends your circumstances. The Holy Spirit, who carries the mind of Christ, is already inside you, ready to illuminate what you're not seeing.\n\nYou don't have to figure everything out on your own. You have the mind of the One who already figured it all out.\n\nJesus, You have given me Your mind — not my natural thoughts elevated, but Your thoughts made available. Teach me to think from this place. When I'm confused, when I'm fearful, when I can't see clearly — let Your mind be the lens through which I see. Amen. 💜"
    },
    "10-01": {
        "title": "The Sanctuary You Don't See",
        "devotionalText": "Right now, in this moment, you are the place where God has chosen to dwell.\n\nThere was a time when the presence of God was localized — contained in a tent, then a temple, then the Holy of Holies behind a thick curtain. Access was restricted. You came to the place where God was. The priests entered cautiously, following precise protocols, because the presence of God was terrifying in its holiness.\n\nThen Paul writes to a church in Corinth — not a community of religious professionals, but ordinary people, many of them rough around the edges — and he asks: don't you know that you yourselves are God's temple and that God's Spirit dwells in your midst?\n\nThe language matters. Temple. Not a meeting space. Not a gathering room. A temple — a sacred structure built for the permanent habitation of divine presence. The same word used for the place where the Shekinah glory settled. Paul is saying the location has changed. God is no longer in a building. He is in you.\n\nThe implications are enormous. You are not going to God when you pray — you are turning inward to recognize the One already present. You are not trying to get into His presence — you already live there. Every moment of your day, whether you feel it or not, you are a walking dwelling place of the Most High.\n\nAnd because you are His temple, you are sacred. Set apart. The word means something is marked out for God's exclusive use, treated with the care that holy things deserve. God treats you this way because He has moved in.\n\nYou carry something extraordinary wherever you go today. The presence of God travels with you into every room, every conversation, every ordinary moment. Act accordingly.\n\nHoly Spirit, I receive the reality that You dwell in me — not metaphorically but actually. I am Your temple. Let that truth change how I see myself today, how I walk into rooms, how I handle what I carry. I am not empty. I am inhabited. Amen. 💜"
    },
    "11-01": {
        "title": "Heirs of Everything",
        "devotionalText": "The Christian life is not a path toward abundance — it is the life of someone who already has everything.\n\nPaul delivers one of the most audacious statements in all of Scripture at the end of 1 Corinthians 3: all things are yours. He lists what he means — the apostles, the world, life, death, the present, the future. Everything. Yours.\n\nThe Corinthians had been sorting themselves into factions based on which human leader they followed. You're a Paul person. I'm an Apollos person. Paul finds this tragically backwards. These leaders don't own you — they serve you. The world isn't your threat — it belongs to you. Even death doesn't hold anything over you — it is your final promotion.\n\nThe logic is airtight: you are of Christ, and Christ is of God. Everything in the chain flows to you. Because you belong to the One who owns everything, you have access to everything.\n\nThis changes how you meet a day. Not as someone scraping for enough, hoping circumstances cooperate, nervously watching resources. But as an heir who moves through the world knowing the Father's estate is behind every situation. That doesn't mean your life will be free from difficulty. But it means difficulty is never the final word — because the future belongs to you too.\n\nLife and death are both yours. Think about what that does to fear. If life is yours, then every good thing God has in store for you is accessible. If death is yours, then even your own death is not your enemy — it is merely the door to more. Nothing in the created order has power over you, because all of it falls within your inheritance.\n\nYou are not poor. You are not lacking. You are an heir. Live from that today.\n\nFather, all things are mine through Christ. I release the scarcity mindset that acts as though I'm barely surviving. I am an heir of everything. Let me walk today from that inheritance — bold, generous, unafraid. Amen. 💜"
    },
    "12-01": {
        "title": "The Weight of What You've Been Given",
        "devotionalText": "God didn't just save you from something — He entrusted you with something that the angels longed to see.\n\nPaul opens 1 Corinthians 4 with a reframe of identity so radical that it would have shocked his Corinthian readers. In a culture obsessed with status and reputation, where people positioned themselves according to their social standing, Paul says: this is how you ought to regard us — as servants of Christ and as those entrusted with the mysteries of God.\n\nMysteries. In the New Testament context, a mystery isn't something cryptic or unknowable — it's something that was hidden in ages past and has now been revealed in Christ. The plan of salvation that prophets strained to see, that angels wondered about, that God held in reserve through the long centuries of human history — that has been entrusted to ordinary people like you.\n\nYou are not just saved. You are a steward. A steward in the ancient world was a manager given responsibility over the household of someone else, given authority to act on that person's behalf. You have been handed the mystery of the gospel — the good news that God reconciled the world to Himself in Christ — and commissioned to manage it faithfully.\n\nThe requirement Paul names is simple but weighty: those who have been given a trust must prove faithful. Not spectacular. Not impressive. Faithful. Consistent. Reliable in the things that matter.\n\nThis is your identity in a world that is longing for something true. You carry something people have searched for their whole lives. Not a better philosophy or an improved religious system — the actual mystery of God, alive and accessible, held in the ordinary container of your daily life.\n\nWhat does faithfulness look like for you today with what you've been given?\n\nFather, I have been entrusted with the most precious thing in existence — the mystery of who You are and what You've done. Let me hold it faithfully. Not impressively — faithfully. Make me a steward worthy of what You've placed in my hands. Amen. 💜"
    },
    "13-01": {
        "title": "The Lamb Who Covered Everything",
        "devotionalText": "The night of the first Passover, death moved through Egypt and passed over every door marked with blood — and nothing has changed about how God provides protection.\n\nWhen God prepared Israel for their exodus from Egypt, He gave instructions so specific they seemed almost strange. A lamb, without defect. Blood applied to the doorframes. And the promise: when I see the blood, I will pass over you. The destroyer could not enter a home that was marked. The blood was not a charm or a ritual — it was the visible sign that a substitutionary death had already occurred in that household. The lamb had already died. So the firstborn did not have to.\n\nPaul writes to the Corinthians and identifies Jesus with stunning directness: Christ, our Passover lamb, has been sacrificed. He's not drawing a loose analogy. He's stating that every detail of that night in Egypt was pointing forward to a single moment on a Friday afternoon outside Jerusalem. The lamb on the altar. The blood poured out. The firstborn spared.\n\nYou are the one who was marked. Not with the blood of an animal applied hastily to a wooden doorframe, but with the blood of the Son of God applied permanently, eternally, irrevocably to your life. Every accusation that would condemn you, every consequence you deserve — death passed over you because a Lamb already died in your place.\n\nThis is not religion. This is rescue. And Paul's response to it is telling: therefore let us keep the Festival — not with old bread, but with sincerity and truth. In other words, the appropriate response to being covered by the Passover Lamb is to live with the kind of authenticity that honors the seriousness of what was paid.\n\nThe blood still speaks. It speaks over every guilty memory, every moment of shame, every accusing voice. It says: already covered. Already paid.\n\nJesus, You are my Passover Lamb. The death that should have been mine became Yours. I receive the full weight of that exchange — fully covered, fully free. Let me live with the sincerity and truth that honors what You gave. Amen. 💜"
    },
    "14-01": {
        "title": "You Were Purchased, Not Abandoned",
        "devotionalText": "God set the price for your life, and He paid it without hesitation — which tells you exactly how much you're worth to Him.\n\nIn the ancient Roman world, the marketplace was where you could hear the term Paul uses — bought at a price. Slaves were purchased, and the price paid reflected the buyer's assessment of the slave's value. A high price meant the buyer considered the purchase worth it. A low price meant the opposite.\n\nPaul takes this economic language and charges it with theological electricity: you were bought at a price. And the price was not silver or gold — it was the life of the Son of God. That is the number God placed on your worth. That is what He determined you were valuable enough to pay for.\n\nThe implication Paul draws from this is breathtaking in its practical weight: you are not your own. Not in the sense of being controlled — but in the sense that your identity and worth are no longer determined by what the world says about you. The Roman slave's value was set by what the market would pay. Your value was set by what God paid. And He paid everything.\n\nThere's an instruction here too: do not become slaves of human beings. Once you know what you were purchased for, you stop letting every opinion, every criticism, every approval or rejection from the people around you determine how you see yourself. You were bought by a different buyer. Your identity comes from that transaction, not from the marketplace of human opinion.\n\nHonoring God with your body flows naturally from understanding this. It's not a burden — it's a logical response. When you know you were purchased by love for an eternal purpose, you want to live in a way that honors the love that bought you.\n\nFather, You paid the ultimate price for me — and that price tells me my worth. I stop letting human opinion set the value You already established. I am Yours. Purchased by love. Live in me as the One I belong to. Amen. 💜"
    },
    "15-01": {
        "title": "One Body, Improbable Unity",
        "devotionalText": "The church is the most unlikely community in human history — and that's exactly the point.\n\nCorinth in Paul's day was a cosmopolitan city: Roman citizens, Greek merchants, freed slaves, Jewish synagogue members, wealthy patrons and struggling laborers. When Paul says we were all baptized by one Spirit into one body — whether Jews or Gentiles, slave or free — he is describing something that could not happen by natural social forces. These groups didn't mix. Status differences in the ancient world were not just social awkwardness — they were legally enforced, culturally enforced, enforced at every level of daily life.\n\nAnd the Spirit decided to put them all in the same body.\n\nThe human body Paul uses as his metaphor is brilliant precisely because you don't choose your parts. Your hand didn't interview for the position. Your eye didn't apply. They were placed — intentionally, with purpose, in relationship to everything else. The ear cannot decide it would rather be an eye. The foot cannot opt out of the body because it isn't a hand.\n\nThis is not a metaphor for passive acceptance. It's a vision of intentional, purposeful community built on a foundation no human builder would have chosen. The unity of the body of Christ is not the result of finding people who are like you — it's the result of being placed by the same Spirit into something larger than your preferences.\n\nIn a world that fragments endlessly — along racial lines, economic lines, cultural lines — the church is meant to be living proof that another kind of community is possible. Not because we decided to be diverse, but because the Spirit of God moved through every human barrier and said: one body.\n\nYour brothers and sisters may not look like you or think like you. They were placed in your life by the same Spirit who placed you in theirs.\n\nHoly Spirit, You have made me part of something I could never have built. I receive every person You've placed in this body with me — they are a gift, not a burden. Let the unity You created be something I protect and celebrate. Amen. 💜"
    },
    "16-01": {
        "title": "You Were Placed, Not Placed By Accident",
        "devotionalText": "Every gift you have, every position you're in, every capacity that feels ordinary to you — God put it there on purpose.\n\nPaul is addressing a tension in the Corinthian church: the spectacular gifts feel more important than the quiet ones. The miraculous feels more significant than the steady. The visible feels more valuable than the hidden. And Paul interrupts this entire hierarchy with a simple statement: but in fact God has placed the parts in the body, every one of them, just as He wanted them to be.\n\nJust as He wanted. Not just as He had to. Not just as was available. As He wanted. This is the language of intention, of design, of a Creator working from a vision rather than improvising.\n\nYour placement in the body of Christ is not the result of random spiritual assignment. It is the result of a God who looked at what He was building — the whole, the complete, the beautiful thing He had in mind — and determined exactly where you belonged in it. The gifts you have, the temperament you carry, the particular way you see and serve — these are not accidents. They are His wanted design.\n\nWhich means the person who feels like a background part is not less important — they are differently essential. A lung doesn't get the credit a hand gets. A kidney works invisibly. But remove any of these and the body dies. God places the parts as He wants them because He can see the whole — and He needs all of them.\n\nStop evaluating your contribution by whether it gets noticed. Stop comparing your placement to someone else's. The one who placed you had the full picture in view when He did it. Your role is exactly where He wanted His body to have that particular function.\n\nYou are not an afterthought. You are a wanted design.\n\nFather, You placed me exactly where You wanted me — in this body, with these gifts, in this time. I stop comparing and start functioning. I am needed exactly where You put me. Let me serve faithfully from the place You designed for me. Amen. 💜"
    },
    "17-01": {
        "title": "The Parts the World Overlooks",
        "devotionalText": "God's economy inverts everything — the ones the world considers least significant are often the ones He considers most indispensable.\n\nPaul is making a counterintuitive argument in 1 Corinthians 12. The Corinthians were elevating the dramatic spiritual gifts — tongues, prophecy, miracles — and implicitly devaluing the quieter ones. The public-facing work felt more important. The visible gifts seemed more spiritual.\n\nPaul responds by talking about human anatomy. Those parts of the body that seem to be weaker are indispensable. The parts we think are less honorable we treat with special honor. The parts that are unpresentable are treated with special modesty. In other words, the body actually goes out of its way to protect what seems less impressive.\n\nThink about which organs are hidden versus visible. Your liver never appears in a photograph. Your kidneys work in complete obscurity. But a failing liver kills you. A failing kidney kills you. The hidden, unglamorous, unnoticed work is the work that keeps everything else alive.\n\nGod designed the body — spiritual and physical — this way on purpose. He gives greater honor to the parts that lack it, so that there should be no division in the body, so that its parts should have equal concern for each other.\n\nThis is not just encouragement for introverts. It's a theological statement about how God values things. The world honors the prominent. God honors the faithful. The world notices the spectacular. God notices the consistent. The world celebrates the visible. God celebrates what happens in secret.\n\nIf you have been doing quiet, unnoticed work — if you have been serving in the background, praying without acknowledgment, giving without recognition — God does not miss this. He not only sees it; He honors it.\n\nFather, You see the parts that go unnoticed — including me when I feel overlooked. You have not missed a single quiet act of faithfulness. Help me value what You value, honor what You honor, and serve from a place that doesn't need to be seen. Amen. 💜"
    },
    "18-01": {
        "title": "The Greatest Thing in the World",
        "devotionalText": "When Paul puts three of the greatest spiritual realities side by side and says love is greatest — he is telling you something about the nature of God Himself.\n\nFaith moves mountains. Scripture says so. Genuine, mountain-moving faith is described throughout the Gospels and Epistles as one of the most significant forces available to a human being. Hope anchors the soul. The writer of Hebrews calls it a firm and secure anchor — something that holds you steady when everything else is unstable.\n\nAnd Paul says love is greater than both.\n\nWhy? Because faith is the means. Hope is the posture. Love is the nature of God. When Paul writes in 1 John that God is love — not just loving, but love itself — he is identifying love as the deepest reality in the universe. Faith will eventually give way to sight. Hope will eventually give way to fulfillment. But love is what remains when everything else has been completed.\n\nIn the love chapter — 1 Corinthians 13 — Paul has just finished a long description of what love actually looks like: patient, kind, not envious, not boastful, not self-seeking. It bears all things, believes all things, hopes all things, endures all things. And then the famous line: love never fails.\n\nThis is not just a sentiment for greeting cards. It is the most radical claim in existence. In a world where everything eventually fails — bodies, systems, relationships, certainties — love never does. Because love is grounded in the character of a God who cannot change.\n\nTo love well is not just a nice thing. It is to participate in the fundamental nature of God, the only thing that will remain when time has finished doing its work.\n\nFather, You are love — and love is the greatest thing. Grow love in me that bears all things and never gives up. I want to participate in the nature that defines You. Let love be the deepest reality in my life. Amen. 💜"
    },
    "19-01": {
        "title": "Love That Has No Off Switch",
        "devotionalText": "Every other power in the universe has a limit — and love is the only one that doesn't.\n\nPaul makes a stunning contrast in 1 Corinthians 13. Prophecies will cease. Tongues will be stilled. Knowledge — even the partial knowledge of the spiritual realm — will pass away. These are not bad things. Prophecy is one of the most powerful gifts in the church. Knowledge enables ministry. Tongues can be the language of the Spirit in a human mouth. And yet all of these have an end. They are means to an end. They serve their purpose and then give way to something fuller.\n\nExcept love. Love never fails.\n\nThe Greek word Paul uses for fails — pipte — means to fall, to drop, to lose effectiveness. Love never drops. Never runs out. Never loses its capacity to do what it was designed to do. When the age is complete and every spiritual gift has accomplished its purpose and no longer needs to operate — love will still be running. Because love is not a means to an end. It is the end.\n\nThis is deeply personal. The love God has for you does not have an off switch. It doesn't diminish when you fail repeatedly. It doesn't reset when you go through a season of distance. It doesn't cool off when you stop performing. His love for you is not conditional on your consistency because His love doesn't fail — and failure to maintain conditions would constitute love failing.\n\nYou are loved with a love that will still be operating when prophecy has finished, when tongues have ceased, when every partial thing has given way to the complete. The most durable force in existence is aimed at you.\n\nYou are held by something that cannot let go.\n\nFather, Your love for me never fails. I stop treating it as something I have to maintain or earn back. You love me with the only love in the universe that has no off switch. Let that security sink into the deepest parts of me. Amen. 💜"
    },
    "20-01": {
        "title": "First Importance",
        "devotionalText": "There is one fact at the center of everything — and if you lose hold of it, nothing else holds together.\n\nPaul is very careful with his language in 1 Corinthians 15. He uses the language of transmission: what I received I passed on to you. This isn't his opinion or his theological interpretation. This is the kerygma — the core proclamation — that was handed down from the eyewitnesses themselves. And then he names what is of first importance.\n\nNot of great importance. Not of significant importance. First importance. The primary thing. The thing everything else orbits.\n\nChrist died for our sins. He was buried. He was raised on the third day. These three facts are the axis of history — and Paul says they happened according to the Scriptures. In other words, this was not a surprise ending. This was the story God had been telling since the beginning — through the Passover lamb, through the temple sacrifices, through the prophet who said He was pierced for our transgressions — all pointing toward this.\n\nThe burial matters because it confirms the death was real. This was not a spiritual metaphor. A body was placed in a sealed tomb. And on the third day — in history, in a specific garden outside Jerusalem, on a specific Sunday morning — the tomb was empty.\n\nOver five hundred people saw Him alive after the resurrection. Paul names this because he knows what it means: this is verifiable. This is not mythology. The witnesses were still alive when he wrote this letter. You could have gone and asked them.\n\nThis is what everything stands on. Not good advice, not inspiring teaching, not a moral system — a person who died for specific sins and came back from specific death. That is the center. Everything else radiates from there.\n\nJesus, Your death and resurrection are of first importance — and I make them first importance in my life. I don't drift from the center. Every other truth I believe radiates from this: You died. You rose. You changed everything. Amen. 💜"
    },
    "21-01": {
        "title": "The One Who Gives Life Instead of Receiving It",
        "devotionalText": "The first Adam received life. The last Adam became the source of it — and this difference changes everything about who you are.\n\nPaul draws one of the most theologically loaded contrasts in all of his letters. The first man Adam became a living being — this is direct from Genesis. God breathed into Adam's nostrils, and the man who had been formed from dust became alive. He received life. He was a recipient.\n\nBut the last Adam — Jesus — is a life-giving spirit. He does not receive life. He dispenses it. He is the source. When Lazarus lay in a tomb four days dead, Jesus didn't ask for help or borrow power from elsewhere. He simply said: come forth. And life moved. That's not a man who has life — that's a man who is life.\n\nPaul notes the order: the natural came first, then the spiritual. You were born into Adam first. Dust, mortality, the nature that strains and fails and eventually gives way. Every human being comes into the world on Adam's terms — receiving a life that is already counting down.\n\nBut then comes the second birth. In Christ, you are connected to the last Adam — the one who is not a recipient of life but its eternal source. You carry now not just the breath of God in your nostrils but the spirit of the risen Christ inside you. A different nature. A different origin. A different kind of life.\n\nYou bear both images — Adam's and Christ's. But the work of the Spirit is to increasingly express the image you were made for, the one you were re-created in: the image of the heavenly man.\n\nYou are not the product of dust with a ceiling. You are being conformed to the image of the One who gives life itself.\n\nJesus, You are the last Adam — not a recipient of life, but its source. I am connected to You. I carry Your life-giving nature, not just Adam's dying one. Transform my living into something that reflects the image of heaven. Amen. 💜"
    },
    "22-01": {
        "title": "The Sting That Got Removed",
        "devotionalText": "Death had a weapon. Christ took it — and death has been standing in the ring unarmed ever since.\n\nPaul breaks into one of the most ecstatic passages in all of his letters. He has just finished explaining the resurrection — the transformation from perishable to imperishable, from mortal to immortal. And then, like someone who cannot contain himself any longer, he turns and speaks directly to death: Where, O death, is your victory? Where, O death, is your sting?\n\nThis is a taunt. A legitimate, Spirit-fueled taunt. Because death has been defeated and Paul cannot help but rub it in.\n\nThe sting of death is sin. Death got its power — its ability to bring ultimate separation, ultimate consequence — from sin. Sin is what gave death its authority. Remove sin's grip and death becomes a door rather than a grave.\n\nAnd then: the power of sin is the law. The law gave sin its condemning force. The law could name the violation but couldn't provide the solution. It could specify the debt but couldn't pay it. Which is exactly what Christ did — He fulfilled the law, absorbed its condemnation, died the death that sin required, and rose out from under it entirely.\n\nDeath has nothing left. The sting is gone. The victory is gone. What's left is a door — and on the other side of that door, Paul has just described, is imperishable, immortal, glorious resurrection life.\n\nYou don't have to be afraid of death. Not because death isn't real, but because it has been definitively disarmed. The worst it can do is release you into more of what you already have in Christ.\n\nBut thanks be to God — He gives us the victory through our Lord Jesus Christ.\n\nJesus, death has no sting for me — You removed it. Sin has no ultimate condemnation for me — You bore it. I live free of death's fear, and I face death when it comes without dread. You've already won. Thanks be to God. Amen. 💜"
    },
    "23-01": {
        "title": "The Unmovable Life",
        "devotionalText": "The resurrection is not just a future hope — it is the present foundation that makes you impossible to shake.\n\nPaul ends his great resurrection chapter not with a philosophical conclusion but with a practical instruction: therefore, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.\n\nThe word therefore is load-bearing. It connects everything Paul has said about the resurrection to how you should live right now. Because death has been defeated. Because the imperishable is coming. Because what was sown mortal will be raised immortal. Therefore — stand firm.\n\nStand firm is a military image — a soldier who will not be moved from his position. Unmoved by opposition, by pressure, by discouragement, by the enemy's tactics. Not stubborn or inflexible in the wrong ways — but rooted in something so certain that no assault can dislodge it. That something is the resurrection of Jesus Christ.\n\nLet nothing move you. Think about what tries to move you. Fear of the future. Discouragement from repeated failure. Weariness from prolonged effort without visible results. The sense that your work doesn't matter. Paul addresses all of it in one phrase: your labor in the Lord is not in vain.\n\nNot a single prayer prayed. Not a single act of faithfulness. Not a single sacrifice made. Not a single word spoken in love. None of it is wasted. In a world where so much human effort disappears into the void, God has established this: what is done in Him has eternal weight.\n\nThe resurrection means your work outlasts your death. That's not sentiment — it's the logic of the empty tomb.\n\nFather, I stand firm — not because I am strong, but because the resurrection is certain. My labor in You is not wasted. I give myself fully to what You've called me to, knowing that what is done in You lasts forever. Nothing can move me from this. Amen. 💜"
    },
    "24-01": {
        "title": "The God Who Enters the Trouble With You",
        "devotionalText": "God does not comfort you by removing trouble — He comforts you by entering it.\n\nPaul opens 2 Corinthians with a doxology — a word of praise to God — but the praise he chooses is unexpected. He doesn't praise God for taking away his hardships. He praises Him as the Father of compassion and the God of all comfort, who comforts us in all our troubles.\n\nAll our troubles. Not some. Not the ones that qualify. Not the ones big enough to count. All. The Greek word translated troubles — thlipsis — means pressure, affliction, the crushing kind of difficulty that feels like it has weight. God comforts in that. In the middle of it. Not after it passes, though He does that too — but inside it, while it's still happening.\n\nAnd then Paul reveals a dimension to this comfort that makes it even more significant: so that we can comfort those in any trouble with the comfort we ourselves receive from God. The comfort God gives you is not just for you — it moves through you. Your suffering, and God's presence in it, equips you to stand with someone else in their suffering in a way that generic sympathy cannot.\n\nPaul knew this personally. He was not writing from an armchair about hypothetical difficulty. He was writing from prison, from beatings, from shipwreck, from the daily pressure of churches full of people who needed more than he had. And he found God there — not a God who explained the suffering or eliminated it, but a God who showed up inside it with tangible, personal comfort.\n\nYour trouble is not a sign that God has stepped back. It is actually the context in which you may most clearly experience what Paul called the God of all comfort.\n\nFather of compassion, I bring You my trouble — not asking You to explain it or remove it immediately, but asking You to be present in it. Comfort me so I can comfort others. Be the God of all comfort in my exact situation today. Amen. 💜"
    },
    "25-01": {
        "title": "When Yes Is Already Signed",
        "devotionalText": "Every promise God has ever made carries a signature — and the signature is Jesus.\n\nIn the ancient world, a letter was only as reliable as the seal attached to it. Break open a letter and see the king's seal, and you knew the content was authoritative. It came from the source. It had backing behind it.\n\nPaul says something extraordinary about the promises of God in 2 Corinthians 1: no matter how many promises God has made, they are Yes in Christ. Every single one. Not the impressive ones and not the smaller ones. Not the ones from the prophet Isaiah and not the ones from Deuteronomy and not the ones scattered through the Psalms. Every one. Yes.\n\nThe mechanism is Christ. He didn't just teach about the promises — He fulfilled them. His obedience, His sacrifice, His resurrection activated the inheritance of every covenant word God had ever spoken. Your response to this is Amen — so be it — spoken through Him, to the glory of God.\n\nThen Paul adds something personal: God has anointed you, set His seal of ownership on you, and put His Spirit in your hearts as a deposit. Three things: anointed, sealed, and given the Spirit as a down payment. You are not just told that the promises are yes — you are stamped with the guarantee. The Spirit is the first payment of a larger transaction that will be fully completed when Christ returns.\n\nThis matters practically because there will be mornings when the promises feel distant and circumstances feel loud. On those mornings, you go back to the seal. You go back to the anointing. You go back to the Spirit inside you — who is himself the proof that God's yes is operative.\n\nThe promises are not maybe. They are not probably. They are Yes, signed with the most authoritative name in the universe.\n\nFather, all Your promises are Yes in Christ — and I say Amen. I receive them not because circumstances support them today, but because Your seal is on my life. Your Spirit is Your guarantee in me. Amen. 💜"
    },
    "26-01": {
        "title": "The Ministry That Gives Life Instead of Taking It",
        "devotionalText": "There is a kind of religion that kills the people it touches — and then there is the Spirit, who does the opposite.\n\nPaul makes a stark contrast in 2 Corinthians 3. He is reflecting on two covenants — the old written on stone, the new written by the Spirit. And he draws the most arresting line: the letter kills, but the Spirit gives life.\n\nThe letter here is not just Scripture — it is law untempered by grace, religion stripped of relationship, requirements without the resource to meet them. The Pharisees in Jesus' day were experts at the letter. They could parse the law to its finest detail. And Jesus looked at their converts and said: you make them twice as much a child of hell as you are. The letter, applied without the Spirit, produces condemnation, shame, exhaustion, and ultimately death.\n\nBut the Spirit gives life. The same Spirit who hovered over the formless void in Genesis 1 and brought order and life out of nothing — that Spirit is at work in you, not to condemn but to transform. Not to demand but to empower. Not to expose your failures without provision, but to lead you into the truth that sets you free.\n\nPaul says God has made us competent as ministers of this new covenant. Not the letter. The Spirit. Which means when you share your faith, when you speak truth to someone who is struggling, the most powerful thing you can do is not provide a better argument or a stricter standard — it is to bring the life-giving presence of the Spirit into the room.\n\nYou are not a prosecutor. You are a life-giver. You carry the new covenant — not the one that condemns but the one that sets free.\n\nHoly Spirit, I don't want to be a minister of the letter — I want to minister life. Flow through me with the freedom that comes from new covenant grace. Let what I bring into rooms make people more alive, not more burdened. Amen. 💜"
    },
    "27-01": {
        "title": "The Slow Work of Glory",
        "devotionalText": "Transformation doesn't announce itself — it moves like the light in a room when the sun is rising.\n\nPaul is describing something in 2 Corinthians 3:18 that is easy to underestimate: with unveiled faces we all contemplate the Lord's glory and are being transformed into his image with ever-increasing glory. The transformation is real. It's happening. But the mode of it is not dramatic or sudden — it's progressive. Glory to glory. More of His image, continually, through continued exposure to Him.\n\nThe contrast Paul sets up is with Moses, who came down from meeting God with a radiance that terrified the people — and then faded. Moses had to put a veil over his face because the glory was diminishing and he didn't want people to see the fade. The old covenant produced moments of brightness that couldn't be sustained.\n\nBut the new covenant produces something different: ongoing, cumulative transformation. Not a moment of brightness that fades, but a process that moves in one direction — more of His image, more of His character, more of His glory reflected in your actual life.\n\nWhere the Spirit of the Lord is, there is freedom. This is the environment in which transformation happens — not under compulsion or fear, but in the freedom of relationship. You are not being forced into conformity. You are beholding Someone and becoming what you see. It's the most natural process in the world.\n\nThis means you don't need to manufacture spiritual transformation or engineer it through sheer discipline. You need to look. Fix your gaze on who He is — in Scripture, in prayer, in the moments you recognize Him in your day. Stay there. The transformation follows the beholding.\n\nHoly Spirit, I trust the process. I stop straining and start beholding. Do what only You can do — transform me from glory to glory into the image of the One I keep looking at. I want to reflect what I see. Amen. 💜"
    },
    "28-01": {
        "title": "Not Searching for Purpose — Walking Into It",
        "devotionalText": "You were not made to find your purpose — you were made to walk into what God already prepared.\n\nThe Greek word Paul uses in Ephesians 2:10 for handiwork is poiema — the same root from which we get poem. You are not a product on an assembly line. You are a crafted work. Something made with intention, care, and artistry by a Creator who knows how this kind of thing is done.\n\nAnd this poem was written for a purpose. Created in Christ Jesus to do good works, which God prepared in advance for us to do. Prepared in advance. The works are not improvised as you go. They were prepared — laid out, made ready — before you arrived at the moment that requires them.\n\nThis changes the entire framework of the question most people ask: what is my purpose? The question implies that purpose is something you discover or create, something you might find if you search long enough. But Paul says the works were prepared in advance. They exist. They are waiting. Your role is not to invent them — it is to walk into them.\n\nThis does something significant to the weight of a day. When you step out your door in the morning, you are not going out into randomness hoping something meaningful will happen. You are stepping into a prepared landscape — a landscape in which the Craftsman has already placed the work that your particular shape fits. Not someone else's shape. Yours.\n\nThe people who seem to walk in purpose are not people who figured something out that others haven't. They are people who stopped asking whether they have a purpose and started paying attention to what's already prepared in front of them.\n\nYou are His poem. Walk into the stanzas He's already written.\n\nFather, I am Your crafted work — made with intention for works You already prepared. I stop searching anxiously for purpose and start walking attentively into what You've already laid out. I trust that the prepared works will become clear as I follow You. Amen. 💜"
    },
    "29-01": {
        "title": "Loved Back to Life",
        "devotionalText": "The love that brought you to life didn't wait for you to deserve it.\n\nPaul's construction in Ephesians 2 is precise and devastating in the best way. He starts by describing what you were before: dead in transgressions and sins, following the ways of the world and the ruler of the kingdom of the air, gratifying the cravings of your sinful nature. He does not soften this. You were dead. Not sick. Not struggling. Not spiritually suboptimal. Dead.\n\nAnd then come two words that change everything: but God.\n\nNot but you decided to change. Not but you eventually showed up. But God. He acts first. He moves into death before there is any sign of life to encourage Him. Because of his great love for us, God, who is rich in mercy, made us alive with Christ.\n\nRich in mercy. Not sufficient mercy. Not occasional mercy. Rich — overflowing, abundant, in excess of what was asked. The mercy God brought to your deadness was not the bare minimum required. He brought everything.\n\nAnd the timing is what exposes the nature of the love: while you were dead. Not while you were improving. Not after you showed promise. While you were spiritually lifeless, unresponsive, and in no position to offer anything back. That is when He moved.\n\nThis is what grace means in its most fundamental form. It precedes your response because it doesn't require your response to begin. Love like this is not a reward — it's an initiation. God initiated. You were the one who was raised.\n\nYou are not the hero of your own salvation story. You are the one who came back from the dead. And the hands that raised you were motivated entirely by love that never needed a reason beyond itself.\n\nFather, You loved me back to life when I was dead — not when I improved, not when I showed up. Your great love and rich mercy acted first. I am alive because You moved. All credit belongs to You. Amen. 💜"
    },
    "30-01": {
        "title": "Already Seated",
        "devotionalText": "You are not working your way up to a seat at God's table — you are already seated, and the chair is permanent.\n\nPaul describes something in Ephesians 2:6 that is past tense — already accomplished: God raised us up with Christ and seated us with him in the heavenly realms in Christ Jesus. Raised. Seated. Both verbs are aorist — a Greek tense that indicates a completed action with ongoing results. Something happened. It is done. And the results are still in force.\n\nYour position is not a ladder you are climbing. It is a reality you have been placed into. When you came to faith in Christ, you weren't placed at the bottom of a spiritual hierarchy and given the chance to work your way toward significance. You were seated — same word used for a king taking his throne — in Christ, in the heavenly realms, right now.\n\nAnd then Paul gives the purpose: in order that in the coming ages, he might show the incomparable riches of his grace, expressed in his kindness to us in Christ Jesus. You are not just saved — you are a demonstration. Your life is an ongoing exhibit of what God's grace actually looks like when it operates. In the ages to come, your story will be evidence of His kindness.\n\nThis is staggering if you let it land. The eternal God decided to make His grace visible in the universe by seating the unworthy in places of honor. You are one of those. Your seat at the table is not evidence of how good you are — it is evidence of how good He is.\n\nLive from that seat. Not striving toward it, not wondering if you've earned it, not afraid of losing it. Seated. Secure. Already positioned in the place love prepared.\n\nFather, I am already seated with Christ — not working toward it, but placed in it. Let me live from that security today. I am a display of Your grace. Let my life show people what Your kindness looks like. Amen. 💜"
    },
    "31-01": {
        "title": "A Gift You Can't Earn, a Grace You Can't Manufacture",
        "devotionalText": "If salvation could be earned, it wouldn't be a gift — and God chose to give, not to sell.\n\nPaul's statement in Ephesians 2:8-9 is one of the most quoted in Scripture, and also one of the most misunderstood. For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one may boast.\n\nEvery human religious system, regardless of tradition, shares a common logic: you do the right things and accumulate standing. You perform well enough and the divine accepts you. The difference in quality between your behavior and someone else's corresponds to a difference in your standing before God.\n\nPaul says the Christian gospel is the radical inversion of this logic. Saved by grace — meaning God's unearned, undeserved favor was the mechanism. Through faith — meaning the posture that receives rather than performs. And then, in case anyone is wondering if faith counts as the work that earns the gift: this is not from yourselves. Even the faith is not yours in the sense that you generated it. It is the gift of God.\n\nThe purpose is explicit: so that no one may boast. The entire structure is designed to eliminate spiritual pride at its root. If you contributed even ten percent to your salvation, you would have grounds for ten percent of the boasting. But if the entire transaction — grace, faith, completion — was God's gift, then all boasting belongs to Him.\n\nThis is freedom. Not because standards don't matter, but because your standing before God is not determined by how well you maintain them. You are not saved by your performance, sustained by your performance, or one failure away from losing what grace gave you.\n\nFather, I receive what I cannot earn. Salvation is Your gift — not my achievement. I bring no boast except in what You have freely given. Thank You for the grace that saves completely. Amen. 💜"
    }
}

# Load the JSON
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'r') as f:
    data = json.load(f)

# Apply rewrites
updated = 0
for i, d in enumerate(data['devotionals']):
    if d['date'] in JANUARY_REWRITES:
        data['devotionals'][i]['title'] = JANUARY_REWRITES[d['date']]['title']
        data['devotionals'][i]['devotionalText'] = JANUARY_REWRITES[d['date']]['devotionalText']
        updated += 1

print(f"Updated {updated} January devotionals")

# Save back
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved successfully")
