#!/usr/bin/env python3
import json

NOVEMBER_REWRITES = {
    "01-11": {
        "title": "The Door That Opens to Those Who Stay",
        "devotionalText": "Jesus does not describe prayer as a transaction — He describes it as a persistent pursuit of a Person who rewards those who keep coming.\n\nAsk, seek, knock. Three words, but they are not three separate options to choose from. They are a sequence that escalates. You start with asking — the simplest posture, the most dependent. If asking doesn't seem to produce what you need, you seek — you go looking, you put energy into pursuit. And if seeking still hasn't produced the answer, you knock — you press, you stay at the door, you keep your hand on it.\n\nJesus ties each action to a promise. Ask and it will be given. Seek and you will find. Knock and the door will be opened. No condition is attached except the action itself. The guarantee is absolute — not guaranteed on your timeline or in the form you expect, but guaranteed nonetheless. The God you are approaching has committed Himself to responding to the person who keeps coming.\n\nFor everyone who asks receives. Everyone. The scope is total, the category is universal. Not the spiritually impressive. Not the ones with the right theological vocabulary. Everyone who asks. This is the nature of the Father — not a reluctant dispenser who must be talked into giving, but a Father who set up the system so that asking leads to receiving.\n\nThe ones who seek find. Not might find. Find. You cannot genuinely seek God and come up empty — the seeking itself is already a form of finding, because the one who seeks has already turned toward the One who is there.\n\nTo the one who knocks, the door will be opened. Not might be. Will be. The door is not locked against you. Keep your hand on it.\n\nFather, I ask — and trust I will receive. I seek — and trust I will find. I knock — and trust the door will open. You set this up because You are a Father who gives. I take You at Your word. Amen. 💜"
    },
    "02-11": {
        "title": "Unlimited in the Right Hands",
        "devotionalText": "Jesus made a promise in John 14 that sounds like an overstatement — until you understand the source of the power behind it.\n\nWhoever believes in me will do the works I have been doing — and they will do even greater things than these, because I am going to the Father. The staggering claim is not that individual believers would surpass Jesus in spiritual power. It is that the collective body of Christ — through every generation, across every nation, in every language — would accomplish the work of redemption on a scale impossible for one body in one place.\n\nWhen Jesus walked the earth, He was geographically constrained. One body, one location, one conversation at a time. His presence was real but local. But when He ascended and sent the Spirit, the presence was distributed. Not divided — multiplied. Every person in whom the Spirit dwells carries the same Spirit that was in Jesus. The mission that was local became global. The work that was limited to one person became available to millions simultaneously.\n\nGreater things — in scope, in reach, in the number of lives transformed. Not greater in kind, but greater in quantity and reach. The gospel has reached people and places and centuries that Jesus' physical presence never touched.\n\nBecause I am going to the Father — His departure was not abandonment; it was liberation. The geographical limit was removed. The Spirit came. The church was born. The work multiplied.\n\nYou are a vessel of the same Spirit that empowered Jesus. The works you do in His name — praying, speaking truth, loving the overlooked, acting in faith — are the continued work of the One who is now at the Father's right hand, interceding for you.\n\nJesus, through Your Spirit in me, I continue Your work. Let what I do and say extend Your presence into places and people You are still reaching. I am willing to be used for what You started. Amen. 💜"
    },
    "03-11": {
        "title": "Prayer With a Name Behind It",
        "devotionalText": "When you pray in the name of Jesus, you are not appending a religious phrase — you are invoking the authority of the most powerful name in existence.\n\nI will do whatever you ask in my name. Whatever — the breadth of that word is intentional. Jesus doesn't qualify it with a narrow category of acceptable requests. He says whatever you ask in my name, with the purpose so that the Father may be glorified in the Son.\n\nAsking in Jesus' name is not a magic formula. It is praying from your position in Christ — representing His interests, aligning with His purposes, asking for what He would ask for in your situation. A business representative acting in their company's name has authority because they are legitimately acting on behalf of that company. They are not inventing requests — they are advancing the company's mission.\n\nWhen you pray in Jesus' name with genuine understanding of what that means, you are not asking for your preferences and signing His name to them. You are coming to the Father as someone who belongs to the Son, asking for what the Son's own heart would desire for your situation.\n\nI will do it — Jesus Himself commits to acting on these prayers. Not might consider. Not will evaluate. Will do. The One who has all authority in heaven and on earth has committed Himself to responding to prayer that genuinely carries His name.\n\nAnd the purpose is the Father's glory in the Son. Every answered prayer is a display. Every breakthrough is testimony. Every miracle is an advertisement for the nature of the One whose name made it possible.\n\nPray boldly. You carry a Name that heaven responds to.\n\nJesus, I pray in Your name — not as a formula but as a reality. I come in Your authority, asking what Your heart desires for my situation. Do what You promised. Let the Father be glorified through what You do on my behalf. Amen. 💜"
    },
    "04-11": {
        "title": "Rivers from the Center of You",
        "devotionalText": "The promise Jesus makes in John 7 is not about a steady drip of spiritual water — it is about rivers.\n\nOn the last and greatest day of the Feast of Tabernacles, Jesus stood up and called out to the crowd: if anyone is thirsty, let him come to me and drink. The feast involved water-drawing ceremonies, the priest pouring water at the altar while the people remembered their ancestors drinking from the rock in the wilderness. Into that context, Jesus says: I am what you've been remembering.\n\nAnd then the promise to everyone who believes: rivers of living water will flow from within them. From within. Not toward them from an external source. Rivers originating inside the believer and flowing outward. John clarifies that He was speaking about the Spirit.\n\nThe Spirit is not a trickle. He is not a reservoir that occasionally overflows. He is described as rivers — plural, a word that suggests abundance, multiple streams, inexhaustible flow. The person who has the Spirit living within them has a source that does not run dry, a supply that is not diminished by giving it away.\n\nThis means your capacity to love is not limited by your emotional reserves. Your capacity to encourage is not depleted by how much encouragement you have received. Your capacity to give is not constrained by what you have accumulated. The rivers are from within — and the within is connected to the One who is the source of all life.\n\nAre you living with the rivers flowing? Or have you been functioning as though the Spirit is a limited resource that might run out if you draw on Him too much?\n\nHoly Spirit, You are rivers — not a trickle — flowing from within me. I open my life to the full force of that flow. Let what comes from within me be so abundant that it reaches people I haven't even met yet. Amen. 💜"
    },
    "05-11": {
        "title": "Not What the World Offers",
        "devotionalText": "Jesus makes a distinction that sounds like a small qualifier but carries an enormous difference: the peace He gives is not the kind the world gives.\n\nPeace I leave with you; my peace I give you. I do not give to you as the world gives. The world's peace is conditional — it exists when circumstances are under control, when relationships are stable, when finances are steady, when health is good. The world's peace is the temporary absence of disruption. It evaporates the moment any of those conditions changes.\n\nJesus is not offering more of that. He is offering a different kind of peace — one that coexists with disruption, that holds steady in the middle of the storm, that does not require favorable circumstances to remain.\n\nHe spoke these words the night before His crucifixion. His disciples were about to face the most disorienting forty-eight hours of their lives — arrest, trial, abandonment, death. And He tells them: I am leaving you peace. Not peace that arrives after the difficulty resolves. Peace that is available in the middle of it.\n\nDo not let your hearts be troubled and do not be afraid. The command presupposes that trouble and fear will knock on the door. He's not promising they won't come. He's saying don't let them in — because you have something that doesn't need trouble to leave before it can arrive.\n\nThe peace of God that surpasses understanding is not passive. It guards. Paul says it stands watch over hearts and minds. It doesn't just rest in you — it actively protects the inner person from being overwhelmed by what the outer circumstances are producing.\n\nYou can have peace right now. Not after things resolve. Right now.\n\nJesus, I receive the peace You leave with me — not as the world gives, but as You give. I will not let my heart be troubled. Your peace stands guard over me. I choose it, right now, regardless of what is happening around me. Amen. 💜"
    },
    "06-11": {
        "title": "The Overcomer's Address",
        "devotionalText": "Jesus doesn't promise a life without trouble — He promises a life in which trouble has already been overcome.\n\nIn this world you will have trouble. Jesus says it plainly, without apology or softening. Not might have. Not some of you will have. You will have trouble. Anyone who tells you that following Jesus is a path to a problem-free life has not read the book carefully.\n\nBut then — that word again, that great interruption: but take heart! I have overcome the world. The past tense is the entire point. This is not a future promise about what Jesus will eventually do when your situation resolves. It is a statement about something already accomplished. Jesus looked at the world system — with all its darkness, its suffering, its hatred, its death — and said: overcome. Done. Past tense.\n\nThe courage Jesus calls for is not the courage of a soldier who doesn't know the outcome of the battle. It is the courage of a soldier who has already been told the battle is won and is now asked to hold their position until the victory is fully manifested. The trouble is real. The outcome is settled.\n\nTake heart — the Greek is tharseo, to be courageous, to be bold. Jesus commands courage. Not as something you summon from your own reserves, but as the logical response to what He has said. He has overcome the world. The trouble you are in is inside a world that has already been overcome. Its power to ultimately harm you is already nullified by the One who has overcome it.\n\nYou are not fighting toward a victory. You are standing in one.\n\nJesus, I take heart — because You have overcome the world. The trouble I face today is real, but it is inside a reality You have already conquered. I am courageous not because my situation is easy, but because You have overcome. Amen. 💜"
    },
    "07-11": {
        "title": "Power to Witness What You've Already Received",
        "devotionalText": "The power Jesus promised in Acts 1 was not for personal benefit — it was for purpose, and the purpose was to take what you've received to the ends of the earth.\n\nYou will receive power when the Holy Spirit comes on you — and you will be my witnesses. The sequence is precise. Not: you will be powerful. Not: you will have spiritual experiences. You will be witnesses. The power is given for a specific function: to bear testimony, to be living evidence of what Christ has done.\n\nA witness is not a speculator. A witness is someone who was there, who saw what happened, who carries firsthand knowledge. The disciples had been there. They had watched Jesus die, and then they had watched Him alive. They had seen the empty tomb, touched the wounds, eaten breakfast with the resurrected One. And now He was sending the Spirit to empower them to declare what they had witnessed.\n\nIn Jerusalem — the city that had just crucified Him. Judea and Samaria — the regions that had rejected Him or been rejected by His people. To the ends of the earth — every nation, every language, every generation. The reach of the witness was explicitly designed to be total.\n\nYou are a witness too. Not a secondhand reporter passing along old information. The same Spirit who empowered the disciples to speak in Jerusalem is alive in you, bearing witness to the same resurrection, the same living Lord, the same transforming power you have personally experienced.\n\nThe ends of the earth are still waiting. The power is already given. The only thing required is a willing witness.\n\nHoly Spirit, empower me to witness — to carry what I've received into every room, every relationship, every conversation. Let the testimony of what You've done in me reach people who are still waiting to hear it. Amen. 💜"
    },
    "08-11": {
        "title": "The Resurrection Is Not a Memory — It's a Power",
        "devotionalText": "The same power that brought Jesus back from the dead is not a historical fact you believe — it is a present force operating inside your body right now.\n\nRomans 8:11 is one of the most extraordinary promises in all of Scripture: if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies because of his Spirit who lives in you.\n\nThe argument moves from the greatest to the lesser. God accomplished the greatest act of resurrection power in history — raising Jesus from physical death. If He did that, and if the Spirit who accomplished that is now living in you — what does that mean for everything smaller than raising the dead? What does it mean for your weakness, your weariness, your sickness, your discouragement, your limited capacity?\n\nThe Spirit who raised Jesus is not a diminished version of Himself now that He's dwelling in you. He brought His full power into residence. The same resurrection force is available for the problems that are significantly smaller than death.\n\nGive life to your mortal bodies — present tense. This is not exclusively about the future resurrection of your body, though it includes that. It is about the life the Spirit gives to your body now — strength for weariness, healing for sickness, vitality for what is flagging. The resurrection power is not saved for a future event. It is available in the present moment.\n\nYou carry resurrection power. Not potential resurrection power — active, present resurrection power, housed in the same Spirit who is your permanent companion.\n\nHoly Spirit, the resurrection power that raised Jesus lives in me. I receive Your life in my mortal body today — not just future hope but present reality. Bring life to what is weak, strength to what is depleted, vitality to what is flagging. Amen. 💜"
    },
    "09-11": {
        "title": "Not By Might, Not By Power",
        "devotionalText": "The prophet Zechariah received a word that has confronted human self-reliance in every generation since: the thing you are trying to accomplish cannot be accomplished the way you are trying to accomplish it.\n\nZerubbabel had a mountain in front of him — literally and figuratively. The returned exiles were trying to rebuild the temple in Jerusalem, and they were facing massive opposition: political, physical, and spiritual. The opposition was enormous enough that the work had stopped. Human resources were insufficient. The gap between what was needed and what was available was paralyzing.\n\nInto this paralysis, God speaks through Zechariah: not by might, nor by power, but by my Spirit, says the Lord Almighty. Three levels of human resource — collective human strength, individual personal effort — and both are dismissed. Not because they're evil. Because they are insufficient for this particular work.\n\nThe work God calls His people to is always bigger than what they can accomplish by human means. This is not an oversight in the design. It is the design. The gap between human ability and divine calling is the space where God's Spirit operates. When the task is achievable in your own strength, you might accomplish it and give yourself the credit. When the task requires the Spirit, there is no confusion about the source.\n\nNot by might nor by power — but you. You specifically. You are not being disqualified. You are being shown where the real resources are. The Spirit of the Lord Almighty — not a limited supply, not a reluctant partner — is the resource for the work.\n\nHoly Spirit, I stop trying to accomplish Your work in my own strength. What You've called me to requires You. I stop filling the gap with human effort and start trusting Your Spirit to do what I cannot. Amen. 💜"
    },
    "10-11": {
        "title": "The Mountain That Becomes a Plain",
        "devotionalText": "Zechariah 4 describes the most spectacular outcome possible from the most unlikely sequence of events — and it starts with someone who had no right to be confident.\n\nZerubbabel was facing a mighty mountain — the obstacle, the opposition, the impossible scale of the task before him. The temple needed to be rebuilt. The resources were inadequate. The enemies were organized. The mountain was real.\n\nAnd God says: what are you, mighty mountain? Before Zerubbabel you will become level ground. The question is not information-seeking. It is confrontational. The mountain is being addressed by the One who made it, and it is being told its future: level ground. Not reduced, not bypassed, not endured. Leveled.\n\nThe capstone will be brought out with shouts of grace, grace to it. The same hands that laid the foundation will place the final stone. The work started by inadequate human hands will be completed — not because the hands became more capable, but because the grace of God is the power source.\n\nThe hands of Zerubbabel have laid the foundation of this temple; his hands will also complete it. And the question that will follow the completion: who despised the day of small things? The day of small beginnings — the discouraging day when the task seemed impossible — will look different in hindsight. When the mountain is a plain and the capstone is in place, the people who gave up on the small days will have to reckon with what God accomplished.\n\nDon't despise the small day you're in. The mountain ahead of you has heard the same word Zerubbabel's mountain heard.\n\nFather, I speak to the mountain before me: become level ground. Not by my might — by Your Spirit. I don't despise the small beginning I'm in. I trust that the same hands that laid the foundation will place the capstone. Grace, grace to it. Amen. 💜"
    },
    "11-11": {
        "title": "You Are Sacred Space",
        "devotionalText": "The question Paul asks in 1 Corinthians 3 is not rhetorical — he genuinely wants you to grapple with its implications for how you live.\n\nDon't you know that you yourselves are God's temple and that God's Spirit dwells in your midst? If anyone destroys God's temple, God will destroy that person; for God's temple is sacred, and you are that temple.\n\nIn its original context, Paul is addressing a church that is fracturing along personality lines — followers of Paul versus followers of Apollos, each group pulling in a different direction and tearing the community apart. He names this as destruction of the temple. When you divide what God has unified, when you treat the body of Christ as raw material for factionalism, you are destroying sacred space.\n\nBut the principle extends beyond factional church politics. You — as an individual — are God's temple. The Spirit dwells in you. This means your body is sacred space, your mind is sacred space, your inner life is sacred space. What you allow into the temple matters. What you do with the temple matters.\n\nSacred means set apart for God's exclusive use and treated with the care that holiness requires. A temple is not a casual space. You don't wander through a temple disrespecting what it houses. You enter with awareness, with reverence, with consideration for whose presence fills it.\n\nThis is not a burden. It is a dignity. You are the place where God has chosen to dwell. The Creator of the universe looked at every possible place to put His presence and chose the human body — specifically yours.\n\nTreat what He inhabits accordingly.\n\nHoly Spirit, You dwell in me — and I am sacred space. I receive the dignity of that calling. Help me treat what You inhabit with the care it deserves. I want to be a temple worthy of Your presence. Amen. 💜"
    },
    "12-11": {
        "title": "Compelled by Love, Not Obligation",
        "devotionalText": "There is a motive for ministry that never burns out — and it has nothing to do with duty, guilt, or the fear of consequences.\n\nPaul names it with unusual transparency in 2 Corinthians 5:14: for Christ's love compels us, because we are convinced that one died for all, and therefore all died. The word compels is sunechei — to hold together, to constrain, to drive forward. It is the image of something that cannot be contained, a force that moves because it cannot stay still.\n\nThe love of Christ is what compels Paul's ministry. Not obligation. Not fear of punishment for not doing enough. Not the approval of the people he serves. The love of Christ — specifically, the love demonstrated in His death for all — creates in Paul a response that is functionally uncontainable. He cannot encounter what Christ did on the cross and remain passive.\n\nOne died for all, therefore all died. The representative death of Christ was the death of the old humanity in Him. And He rose — not just for Himself, but so that those who live would no longer live for themselves but for Him who died for them and was raised again.\n\nThis is the shift that love produces. Before Christ, the center of your life was yourself — not out of malice, but by default. Self is the natural orientation of the old nature. But when you encounter what Christ did for you — when the love of it lands — the center shifts. Not because you decide to be less selfish, but because you have been so profoundly loved that love becomes the new gravity of your life.\n\nCompelled by love is different from motivated by duty in every measurable way.\n\nJesus, Your love for me compels me — I cannot stay still in the face of what You did. I live no longer for myself but for You who died for me and was raised. Let love be the motive of everything I do. Amen. 💜"
    },
    "13-11": {
        "title": "An Ambassador From Another Kingdom",
        "devotionalText": "You are not a resident of this world making the best of your situation. You are a representative of another kingdom, conducting the most important business in history.\n\nPaul uses the language of ambassadorship in 2 Corinthians 5:20: we are therefore Christ's ambassadors, as though God were making his appeal through us. The political image is precise. An ambassador does not represent himself. He does not conduct personal business on behalf of the nation that sent him. He represents the interests, the character, and the message of the one who appointed him.\n\nChrist's ambassador carries one message: reconciliation is available. We implore you on Christ's behalf: be reconciled to God. This is the urgent, personal appeal of the embassy to every person who hasn't yet received what was made possible at the cross. The appeal is not cold theology — it is the language of urgency. We implore you. There is genuine desire behind the message.\n\nBecause of what makes reconciliation possible: God made him who had no sin to be sin for us, so that in him we might become the righteousness of God. The substitution is complete. Christ took what was yours. You receive what was His. The exchange at the cross creates the possibility that Paul is now imploring people to enter.\n\nAn ambassador lives from his country's values, not the host country's. He represents his king in a foreign land. He conducts his king's business as his primary occupation, not as a side project.\n\nYou are in the world. You are not of the world. You represent a kingdom that has sent you here with a specific message and a specific mission.\n\nFather, I am Your ambassador — representing Your kingdom, carrying Your message, conducting Your business. Let me live like someone who knows whose I am. I implore people toward reconciliation, because I know what it cost and what it provides. Amen. 💜"
    },
    "14-11": {
        "title": "The Workers Are the Answer to the Prayer",
        "devotionalText": "Jesus identified the harvest problem and then gave the strangest possible instruction — and then immediately sent the disciples out to be the answer.\n\nThe harvest is plentiful but the workers are few. Ask the Lord of the harvest to send out workers into his harvest field. There is something almost disorienting about this sequence. Jesus sees the need. He tells His disciples the problem. And then instead of announcing a solution, He asks them to pray for workers.\n\nAnd then He sends them out.\n\nThe prayer for workers was not a request for someone else to show up. It was the preparation of people who were about to become the answer to their own prayer. The act of praying for workers — of genuinely asking God to send people into the harvest — has a way of opening the one who prays to hear: go.\n\nThe harvest is not in a distant future when conditions are better. The harvest Jesus describes as plentiful was the people right in front of His disciples — the crowds who were harassed and helpless, like sheep without a shepherd. The same crowds that would have been easy to walk past if you were focused on your own business.\n\nJesus had compassion on the crowds. This compassion is the motive. Not duty, not religious obligation, not the desire to build something — compassion, the word that describes being moved in the gut by the condition of those around you.\n\nThe plentiful harvest is around you today. The workers are few, in every generation. You prayed for workers — and God's answer to that prayer might include you.\n\nLord of the harvest, I ask You to send workers into the harvest — including me. Give me the compassion that Jesus had for the crowds. Make me an answer to the prayer I'm praying. Amen. 💜"
    },
    "15-11": {
        "title": "What a City on a Hill Can't Do",
        "devotionalText": "Jesus does not say you should try to be the light of the world. He says you are the light of the world — and then points out that light cannot hide itself.\n\nYou are the salt of the earth. You are the light of the world. A city on a hill cannot be hidden. The declarations are indicative — statements of what already is, not instructions about what you should become. Jesus is identifying the nature of the people who have been transformed by the kingdom of God.\n\nSalt preserves what would otherwise decay. It adds flavor that transforms bland food. It has a pervasive quality — a small amount reaches everything it touches. The church is meant to be this in the world: not isolated in a separate culture, but present in every part of society, preserving what is good and adding the flavor of genuine humanity that the kingdom of God produces.\n\nA city on a hill cannot be hidden. You don't have to announce yourself as a Christian before you've said anything else. You don't have to label yourself. A city on a hill is visible because it is elevated — and the life shaped by the kingdom of God carries an elevation that is recognizable. Not an elevation of pride, but of hope and love and integrity that stands out in a landscape that is often dark.\n\nNor do people light a lamp and put it under a bowl — they put it on its stand and it gives light to everyone in the house. The light is for the room, not for the light-bearer. You carry something that is specifically for the people around you, not for your own private edification.\n\nLet your light shine. Not by performing, but by being what you already are.\n\nFather, I am salt and light — not by my effort but by Your transformation. Let me function as what I am. Give me the courage to stop hiding and start shining. The world needs what You've placed in me. Amen. 💜"
    },
    "16-11": {
        "title": "Love Your Enemies — Because You Know Something They Don't",
        "devotionalText": "The instruction Jesus gives in Matthew 5 is the one that most clearly separates His teaching from every other ethical system — and it is built on a vision of God that nothing else can produce.\n\nLove your enemies and pray for those who persecute you, that you may be children of your Father in heaven. The instruction has a purpose clause attached: so that you may be children of your Father. Not so that your enemies will change. Not because loving enemies is smart strategy. Because the God who is your Father makes His sun rise on the evil and the good, and sends rain on the righteous and the unrighteous.\n\nThis is the character of the Father. He does not wait for people to deserve His provision before He provides it. The sun rises on people who hate Him. The rain falls on people who have never acknowledged Him. He loves first, without condition, without the recipient's cooperation. He loves because that is His nature.\n\nWhen you love your enemies, you are not just being kind — you are manifesting the family character. You are functioning as a child of the Father because you are doing what He does. The family resemblance becomes visible.\n\nIf you love those who love you, what reward will you get? Even the tax collectors do that. The love that distinguishes you is the love that costs something. The love that goes against natural instinct. The love that chooses to pray for the person whose actions most clearly justify the opposite response.\n\nThis is only possible if you know something about who God is and what He has done for you when you were His enemy. You were loved first. You are not giving something you don't have.\n\nFather, I love my enemies because You loved me when I was Yours. I pray for those who have hurt me, not because they deserve it, but because that's what Your children do. Make me look like You. Amen. 💜"
    },
    "17-11": {
        "title": "The Kingdom Addition Principle",
        "devotionalText": "Jesus doesn't tell you not to have needs — He tells you where to put your attention, and promises that everything else will be added.\n\nBut seek first his kingdom and his righteousness, and all these things will be given to you as well. The all these things refers to everything Jesus just described: food, clothing, the material provisions of daily life. He has spent the preceding verses explaining that anxiety about these things is unnecessary — not because they don't matter, but because your Father knows you need them and has committed to providing them.\n\nThe instruction is not to pretend needs don't exist. It is to put primary attention in the right place. Seek first. Not seek only — first. The orientation of your pursuit matters. When your primary energy goes toward building the kingdom of God — toward what God values, toward people who need what you carry, toward the righteousness that Christ represents — the other things are added. They come along behind the primary seeking.\n\nThe word seek is zeteo — to look for, to strive toward, to desire earnestly. This is not passive or casual. Seeking the kingdom is an active, directed pursuit. But it is a pursuit with a promise attached: as you seek this way, your Father who knows what you need will see to it that the needs are met.\n\nTomorrow will worry about itself. Today's trouble is sufficient for today. The instruction is beautifully confined to the present moment — which is the only moment you actually inhabit. The anxiety that consumes most people is about tomorrow, which hasn't happened yet, addressed by a Father who will be there when it arrives.\n\nSeek the kingdom today. Let tomorrow be tomorrow's Father's problem.\n\nFather, I seek Your kingdom first — not as one item in a list, but as the primary orientation of my life. I trust that everything I need will be added as I keep seeking You. Today is enough. You are enough. Amen. 💜"
    },
    "18-11": {
        "title": "The Strange Blessedness of the Persecuted",
        "devotionalText": "Jesus says something about persecution that sounds wrong until you understand the kingdom logic behind it.\n\nBlessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven. Blessed are you when people insult you, persecute you and falsely say all kinds of evil against you because of me. Rejoice and be glad, because great is your reward in heaven.\n\nThe temptation is to dismiss this as religious idealism — the kind of sentiment that sounds noble but nobody actually believes. But look at the condition: because of righteousness, because of me. The blessing is not attached to suffering in general. It is attached to suffering that comes specifically as a result of aligning yourself with Christ and His kingdom.\n\nFor in the same way they persecuted the prophets who were before you. You are in a line. The people who spoke the truth God gave them throughout history faced the same response from the same resistance. Your experience of opposition for following Christ connects you to a company of people who are described as the great cloud of witnesses in Hebrews.\n\nGreat is your reward in heaven — this is not abstract compensation. It is the accumulation of what Paul calls an eternal weight of glory, a weight that far outweighs what is being endured. The present difficulty and the coming reward are being weighed against each other, and the reward wins by a margin that Paul says cannot even be adequately expressed.\n\nThe kingdom belongs to the persecuted. Not the comfortable, not the celebrated, not the people who have successfully avoided all opposition. Those who have stayed aligned with Christ through the opposition.\n\nFather, I receive the strange blessing of opposition for Your sake. I am in good company — the prophets before me, the disciples before me. What is coming outweighs what I'm enduring. I stay aligned with You. Amen. 💜"
    },
    "19-11": {
        "title": "Authority Over What Comes Against You",
        "devotionalText": "The authority Jesus gives in Luke 10 is not a distant theological concept — it is a present, practical power over the things that actively work against you.\n\nI have given you authority to trample on snakes and scorpions and to overcome all the power of the enemy; nothing will harm you. The authority was given — past tense, already accomplished. You are not waiting to receive authority. You have been given it by the One who has all authority in heaven and on earth.\n\nThe snakes and scorpions are not literal — Jesus is using them as images for the spiritual powers that work against God's purposes and against His people. To trample suggests complete victory, not cautious avoidance. The authority given is not defensive only — it is offensive. You don't just endure the enemy's attacks; you exercise authority over them.\n\nAll the power of the enemy — not some of it. All of it. There is nothing in the enemy's arsenal that falls outside the scope of the authority Christ gave you. This doesn't mean the enemy is not real or that he won't attack. It means that nothing he does against you has a power that exceeds what you have been given in Christ.\n\nBut then Jesus adds the most important clarification: however, do not rejoice that the spirits submit to you, but rejoice that your names are written in heaven. The authority is real — but it is not the foundation of your identity. Your identity is in relationship, not in power. Your name is written in heaven not because of what you've done, but because of what He did. That is the rejoicing that holds.\n\nYou have authority. But you have something more important: a name written in heaven.\n\nJesus, I receive the authority You gave me — over the enemy's power, over what comes against me. I use it confidently. But I rejoice most in this: my name is written in heaven, not because of my power but because of Your love. Amen. 💜"
    },
    "20-11": {
        "title": "The Better Reason to Rejoice",
        "devotionalText": "The disciples returned from their first mission trip with reports of spiritual power — and Jesus gently redirected their celebration toward something more durable.\n\nThe seventy-two returned with joy. Lord, even the demons submit to us in your name! This was genuine, legitimate, Spirit-given ministry. They had exercised real authority and seen real results. Their excitement was appropriate. But Jesus takes the moment to point them deeper: do not rejoice that the spirits submit to you, but rejoice that your names are written in heaven.\n\nThe distinction is subtle but profound. Rejoicing in the spirits submitting makes your joy dependent on outcomes — on ministry results, on visible spiritual victories, on the experiences that make you feel spiritually powerful. This joy is real, but it is fragile. There will be days when the battle is harder, when results are slower, when what you attempt doesn't produce the visible breakthrough. And on those days, outcome-based joy evaporates.\n\nBut your name written in heaven is not outcome-dependent. It is not result-dependent. It is not performance-dependent. It exists because of what Jesus accomplished, sealed by the Spirit, permanent in the records of a God who does not erase names He has written in love.\n\nI saw Satan fall like lightning from heaven, Jesus says. He has already seen the outcome of the war. From that vantage point, He is not anxious about the battles. And He is redirecting His disciples — and you — to the foundation that remains when the results are mixed and the battles are hard.\n\nYour name is written in heaven. That is the thing to rejoice about. Today, regardless of how ministry is going, regardless of how you feel — that is still true.\n\nJesus, I rejoice in this above all: my name is written in heaven. Not because of what I accomplished — because of what You did. This is the joy that holds when nothing else does. Amen. 💜"
    },
    "21-11": {
        "title": "Strength for the Ones Who Have None Left",
        "devotionalText": "Isaiah 40 was written to people who had run out — out of energy, out of hope, out of the capacity to believe things would change. And God's word to them was not: try harder.\n\nHe gives strength to the weary and increases the power of the weak. The subjects are specific: the weary and the weak. Not the strong who need a boost. Not the rested who could use some additional capacity. The weary — the ones who have already expended everything they had. The weak — the ones who never had much to begin with.\n\nThis is not a verse about peak performance. It is a verse about what happens when you have hit your human limit and there is no visible resource left to draw on. God specializes in precisely that moment.\n\nEven youths grow tired and weary, and young men stumble and fall — which is Isaiah's way of establishing that this is not a character problem or a faith problem. The young, the strongest members of any society, run out too. Everyone runs out. The human resource has a ceiling.\n\nBut those who hope in the Lord will renew their strength. The Hebrew for hope here — qavah — means to wait, to look expectantly toward, to have your attention fixed on. It is not passive waiting. It is the active posture of someone who knows what is coming and is keeping their eyes on the source of it.\n\nThey will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. Three levels of movement, all sustained by a strength that is not their own.\n\nYou don't have to have strength left. You just have to hope in the One who gives it.\n\nFather, I am weary — and I hope in You. Not in my reserves, not in my discipline, not in my willpower. In You. Renew my strength. Let me soar on what You give, not what I have. Amen. 💜"
    },
    "22-11": {
        "title": "The Exchange That Defies Every Law of Nature",
        "devotionalText": "Eagles don't soar by flapping harder — they spread their wings and let the thermal carry them. And Isaiah 40 describes exactly this kind of rising.\n\nThose who hope in the Lord will renew their strength. The word renew is yachalyph in Hebrew — to exchange. They will exchange their strength for His. This is not augmentation — more strength added to what you already have. This is substitution — your depleted human strength traded in for the unlimited divine strength of the One who created energy itself.\n\nThey will soar on wings like eagles. The eagle is the image of effortless elevation. Eagles in the mountain regions catch thermals — rising columns of warm air — and spread their wings to be carried upward without exertion. The rising is not the result of their own power. It is the result of being in the right position to receive what is already moving.\n\nThis is what hoping in the Lord produces. Not more human effort, but a repositioning that allows you to be carried by what God is already doing. The thermal is always there. The question is whether your wings are spread.\n\nThey will run and not grow weary, they will walk and not be faint. Notice the order: soar, then run, then walk. The most dramatic is named first, but the most sustainable is named last. Walking without fainting — the steady, faithful, ordinary perseverance of daily life — is equally sustained by this exchange as the dramatic soaring.\n\nThe great moments of spiritual elevation and the quiet months of faithful trudging are both sustained by the same source: the hope that keeps your attention on the Lord and your wings spread.\n\nFather, I spread my wings and hope in You. I exchange my depleted strength for Yours. Carry me on what You're already doing. Let me soar when You soar, run when You run, and walk without fainting when that's what the day requires. Amen. 💜"
    },
    "23-11": {
        "title": "God's Personal Presence in the River",
        "devotionalText": "God does not promise you an easy crossing. He promises you His presence in the crossing — and He says that makes all the difference.\n\nIsaiah 43:2 was spoken to a people who were not yet in their difficulty. God is telling them what He will do when the hard places come — not if, but when. When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.\n\nThe waters don't become shallow. The rivers don't diminish. The fire doesn't cool down. What changes is the presence of the One who says I will be with you. The promise is not that the dangerous things stop being dangerous. It is that you go through them accompanied by the One who has authority over every dangerous thing.\n\nWith you — the same two words that appear throughout Scripture as the most concentrated form of divine promise. God said them to Abraham in an unknown land. To Moses before the impossible confrontation with Pharaoh. To Joshua before the conquest. To Jeremiah when he protested his inadequacy. To the disciples at the Great Commission: I am with you always, to the very end of the age.\n\nFor I am the Lord your God, the Holy One of Israel, your Savior. The promise is grounded in identity — specifically His identity. He is the Holy One, which means His holiness is not threatened by your hard places. He is your Savior, which means saving you from things that would otherwise overwhelm you is precisely what He does.\n\nYou are going through, not drowning in. There is a difference, and His name is the reason.\n\nFather, You are with me in the river, in the fire, in the hard crossing. I will not drown and I will not be burned — not because it isn't dangerous, but because You are with me. Your presence is my protection. Amen. 💜"
    },
    "24-11": {
        "title": "Precious and Honored — Not Your Opinion, His",
        "devotionalText": "The most important question about your worth is not what you think of yourself — it is what God says, and He has been unambiguous.\n\nIsaiah 43:4 contains one of the most direct expressions of God's personal valuation of His people in all of Scripture: since you are precious and honored in my sight, and because I love you, I will give people in exchange for you, nations in exchange for your life.\n\nPrecious — in the Hebrew, yaqar, meaning to be valued highly, to be esteemed, to be treated as rare and costly. This word is used for fine gold, for jewels, for things that are worth protecting and preserving. That is the category God uses for you in His sight.\n\nHonored — respected, regarded with weightiness. Not tolerated. Not managed. Honored — given the kind of regard that reflects genuine respect for what you are.\n\nAnd then the reason: because I love you. This is not love that follows from your preciousness and honor — it is the source of it. You are precious because you are loved, not loved because you are precious. The love is prior. The love is the foundation. Everything else flows from it.\n\nI will give people in exchange for you — in the context of Isaiah 43, God is describing His willingness to deliver Israel from captivity at enormous cost. The scale of His commitment matches the depth of His love. What He will give in exchange for His beloved people reveals how much He regards them as worth it.\n\nYou are worth it to God. Not because of what you offer. Because of who He is and how He loves.\n\nFather, You say I am precious and honored in Your sight, and You love me. I receive that — not just as theological truth, but as the most personal fact about my existence. Your love defines my worth. Nothing else does. Amen. 💜"
    },
    "25-11": {
        "title": "You Were Worth The Whole Exchange",
        "devotionalText": "The price God paid for you reveals something about what He thinks you are worth — and He determined that price before you could do anything to influence it.\n\nIsaiah 43:4 contains an exchange that is staggering in its proportions: I will give people in exchange for you, nations in exchange for your life. In the original context, God is describing how seriously He takes the redemption of His people — He is willing to give other things of significant value to secure the freedom of the ones He loves.\n\nBut the verse is bracketed by two declarations that ground the exchange in something personal: you are precious and honored in my sight, and because I love you. The exchange is motivated by love. The value assigned to you is not a market calculation — it is the expression of a Father's heart.\n\nDo not be afraid, for I am with you — the exchange is followed immediately by reassurance. God knows that being told you are worth so much to Him could feel too large to hold. So He adds: I am with you. The God who values you this much is also the God who is personally present with you.\n\nI will bring your children from the east and gather you from the west. The gathering is God's initiative. He goes in every direction to collect the ones He has declared precious. The scattered ones, the lost ones, the ones who wandered and don't know how to find the way back — He goes after them.\n\nYou are not someone who has to find your way to God. You are someone God has declared precious and then moved toward. He paid for you before you knew your own worth. That is love that cannot be manufactured — it can only be received.\n\nFather, I receive the exchange You made for me — the declaration that I am precious, the price You paid, the gathering You initiated. I am worth it to You. That is the most important thing I know about myself. Amen. 💜"
    },
    "26-11": {
        "title": "Every Weapon Made Against You Has Already Missed",
        "devotionalText": "Isaiah 54:17 does not say weapons won't be formed against you. It says they won't succeed — and it calls this your heritage.\n\nNo weapon forged against you will prevail, and you will refute every tongue that accuses you. This is the heritage of the servants of the Lord, and this is their vindication from me, declares the Lord.\n\nWeapons will be forged. The verse doesn't pretend otherwise. The enemies of your soul are crafting opposition, accusation, and instruments of harm. They are real, and the forming of them is real. But there is a gap between forming and succeeding — and God has declared that the weapons stop at the gap.\n\nWill prevail — the Hebrew is tatsliach, to succeed, to prosper, to accomplish its purpose. The weapon is formed but it does not prosper. It does not accomplish what it was designed to do. There is a protection in place that is not visible but is effective.\n\nYou will refute every tongue that accuses you — not that accusation won't come. In fact, this verse assumes accusation is coming. Tongues that accuse — voices that condemn, that make charges against you, that bring your past failures into the present. You will refute them. Not by defending yourself, not by having a flawless track record, but because the vindication comes from God. It is his declaration, not yours.\n\nThis is your heritage. Not an occasional blessing but an inheritance — something you receive as a child of God, something that belongs to you because of whose you are, something passed down to you from the covenant.\n\nThe weapons miss. The accusations are answered. This is what it means to belong to God.\n\nFather, no weapon forged against me will prevail — this is my heritage as Your servant. I stand in the vindication that comes from You, not from my own defense. Every accusation is answered by Your word over me. Amen. 💜"
    },
    "27-11": {
        "title": "A Word That Cannot Return Empty",
        "devotionalText": "God's word is not just true — it is effective. It accomplishes something specific in the world every time it goes out.\n\nIsaiah 55:11 is one of the most clarifying statements about the nature of Scripture ever written: so is my word that goes out from my mouth: it will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it.\n\nNot return empty. The image is of a word sent out on a mission and returning only when the mission is complete. A messenger dispatched who does not come back until the message has been delivered and received. God's word does not go out without effect. It always lands somewhere, it always produces something, it always accomplishes the specific thing for which it was sent.\n\nThis means when you read Scripture and a verse lands on you — when a specific word seems to address your specific situation — that is not coincidence. That is the word accomplishing its purpose. It was sent for that moment. It will produce what God intends from it.\n\nIt means when you speak God's word over someone — praying scripture over your children, declaring truth over a sick body, standing on a promise in the face of contradiction — the word is out. It is not bouncing off the ceiling. It is doing something invisible to you but completely tracked by God.\n\nAs the rain and the snow come down from heaven and do not return until they have watered the earth — the word operates with the same certainty as natural law. The rain doesn't ask permission to water the ground. It does what it was made to do.\n\nGod's word is doing something in your situation right now.\n\nFather, Your word goes out and accomplishes its purpose — and I trust it. I speak Your word over my life, my family, my circumstances, knowing it will not return empty. It is achieving what You sent it to achieve. Amen. 💜"
    },
    "28-11": {
        "title": "All Authority, One Commission",
        "devotionalText": "Jesus opens the Great Commission with a statement about authority — and everything that follows is built on it.\n\nAll authority in heaven and on earth has been given to me. Therefore go. The therefore is structural. The commission to go, to make disciples, to baptize, to teach — all of it is grounded in the prior statement about authority. If the authority is total, the commission is possible. If the authority is limited, the commission is uncertain.\n\nAll authority — in heaven and on earth. Not authority in spiritual matters only. Not authority on Sundays. All authority, covering every domain of existence. Political systems, natural forces, spiritual powers, human choices — all of it falls under the authority of the One giving the commission.\n\nTherefore go. The word for go is actually a participle in the Greek — as you go, or going. It doesn't necessarily mean you have to relocate your life to a foreign country (though some are called to that). It means in the movement of your life, in the going that is already happening, make disciples. The going is already taking place. The question is what you're doing as you go.\n\nTeaching them to obey everything I have commanded you — not just to know, but to obey. Not just cognitive assent, but the life transformation that comes from actually doing what Jesus taught. This is the content of discipleship: formation, not just information.\n\nAnd I am with you always, to the very end of the age. The commission ends with the same promise that has sustained every person who has ever tried to do anything significant for God. You are not alone in it.\n\nJesus, You have all authority — and on that basis, I go. I make disciples as I go, teaching what You commanded, trusting You are with me in all of it. The commission is possible because of the authority. Amen. 💜"
    },
    "29-11": {
        "title": "Plans That Will Not Be Undone",
        "devotionalText": "God's plans for you are not aspirational — they are settled. And they have been settled in His heart since before you arrived at this moment.\n\nJeremiah 29:11 was spoken to people who had been deported to Babylon. Their city was destroyed. Their temple was gone. The situation by every visible measure was catastrophic — the opposite of prosperity, the absence of hope, the picture of harm.\n\nFor I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.\n\nThe plans are in God's knowledge — not in the circumstances, not in the current conditions, not in what seems visible or likely. God knows His plans for you in the same way that He knew the plans He had for Jeremiah before he was born, before he was formed in the womb. The plans preceded the conditions. They will outlast the current conditions.\n\nTo prosper you — the Hebrew shalom carries a fullness that the English word prosperity misses. Not just material success, but wholeness, completeness, the flourishing of every dimension of a person's life. God's plan for you is shalom: nothing broken, nothing missing.\n\nNot to harm you. The exile felt like harm. It was not the plan. The plan was for the future and the hope. The hard season was the journey between where they were and where the plan was taking them.\n\nYou may be in what feels like Babylon — far from where you hoped to be, the visible conditions seeming to contradict the promises. God's plans for you have not been revised. They were written before this season and they will be fulfilled after it.\n\nFather, I trust Your plans — not because circumstances support them right now, but because You know them. Plans for shalom, for a future, for hope. Your plans for me cannot be undone by what I'm walking through. Amen. 💜"
    },
    "30-11": {
        "title": "Call to Me — He Actually Means It",
        "devotionalText": "There are many things God asks of you — but in Jeremiah 33, He inverts the relationship and does the asking: call to Me.\n\nCall to me and I will answer you and tell you great and unsearchable things you do not know. The invitation has three parts: call, answer, and reveal. God commits to all three. You provide the calling. He provides everything else.\n\nGreat — Hebrew gadol, vast, magnificent, of enormous scope. Unsearchable — bachur, the word means inaccessible, too difficult, things that cannot be found by human searching. In other words, the things God is promising to tell you are not things you could have figured out on your own. They are not available in any library, not accessible through any amount of human intelligence or effort. They are in a category that can only be received by revelation.\n\nJeremiah receives this word while imprisoned in a courtyard — held there by the king because of his unpopular prophetic messages. The nation is about to fall, and Jeremiah has been saying so. And in the middle of the confinement and the catastrophe, God says: call to me. I have things to tell you. Great things. Things you don't know yet.\n\nThe pattern is consistent throughout Scripture: the worst moments become the context for the deepest revelation. The prison, the wilderness, the exile, the dark night — these are the places where God's call to call tends to be received most openly, because every other option has been exhausted.\n\nYou have access to things that cannot be discovered any other way. They require one thing: calling.\n\nFather, I call to You — not because circumstances are good, but because You invited me to. Answer me. Tell me the great and unsearchable things I don't know. I am listening, and I trust You will speak. Amen. 💜"
    }
}

# Load the JSON
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'r') as f:
    data = json.load(f)

# Apply rewrites
updated = 0
for i, d in enumerate(data['devotionals']):
    if d['date'] in NOVEMBER_REWRITES:
        data['devotionals'][i]['title'] = NOVEMBER_REWRITES[d['date']]['title']
        data['devotionals'][i]['devotionalText'] = NOVEMBER_REWRITES[d['date']]['devotionalText']
        updated += 1

print(f"Updated {updated} November devotionals")

# Save back
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved successfully")
