#!/usr/bin/env python3
import json

SEPTEMBER_REWRITES = {
    "01-09": {
        "title": "When Heaven Invades Your Prison",
        "devotionalText": "The worst thing your enemies ever did to you is also the thing God will use to promote you — because He was there the whole time.\n\nJoseph's brothers sold him to Midianite traders for twenty pieces of silver. He arrived in Egypt as property, classified as cargo. Then Potiphar's wife lied about him and he landed in prison — forgotten, unjustly accused, with no advocate and no timeline for release. By every visible measurement, his story was a tragedy.\n\nBut Acts 7 preserves the commentary that changes everything: God was with him and rescued him out of all his afflictions, and gave him favor and wisdom in the sight of Pharaoh.\n\nGod was with him. Not waiting outside the prison. Not watching from a safe distance. With him — in the pit, in the slave market, in the cell. And that presence didn't just provide comfort; it produced transformation. Joseph moved through thirteen years of injustice and emerged with wisdom so extraordinary that the most powerful man in the world put him second in command over an empire.\n\nThe same jealousy that threw him into a pit elevated him into a palace. The same false accusation that put him in prison became the credential that put him before Pharaoh. Every scheme of the enemy became a stepping stone to his destiny, because God was threading purpose through the disasters all along.\n\nYour pit is not your grave. The person or circumstance trying to take you out may be the very thing positioning you for something you couldn't have reached any other way. God's track record in Joseph's story is His track record in yours: He gets you through the affliction, and He gives you favor in the process.\n\nJesus, You were with Joseph through every betrayal — and You are with me through mine. Transform my pit into a platform. Turn my afflictions into wisdom. Let Your favor rest on me so powerfully that even my enemies have to acknowledge Your hand. Amen. 💜"
    },
    "02-09": {
        "title": "The Promise That Silences Every Voice of Lack",
        "devotionalText": "In a world that screams you need more, God has already spoken a word that is enough to silence it — if you let it sink deep enough.\n\nThe instruction in Hebrews 13:5 is deceptively simple: keep your life free from love of money, and be content with what you have. In any other context this would read as spiritual advice. But then the writer attaches a reason that transforms it entirely: for He has said, 'I will never leave you nor forsake you.'\n\nThe contentment is not a discipline. It is a logical response to a promise. If the One who owns everything has permanently attached Himself to you, then the thing that drives discontentment — the sense that you don't have enough, that more is required before you can be secure — is exposed as a lie. You already have the One who has everything. What exactly are you lacking?\n\nThe original Greek of that promise contains five negatives stacked on top of each other — the language is almost urgent in its intensity. Never, no never, will I in any way forsake you. The writer of Hebrews was working with a Hebrew promise that exhausted its language trying to communicate the same thing: the commitment is absolute.\n\nContentment is not settling for a smaller life. It is waking up to the enormous life you already have. You are accompanied by the Creator of the universe in every ordinary moment of your day. Every decision you face is made in the presence of the One who has infinite wisdom. Every inadequacy you feel is a temporary perception in the presence of the One who lacks nothing.\n\nYou are not poor. You are not lacking. You have the One who has everything and who will never leave.\n\nFather, Your promise has silenced every voice that says I need more. You have said You will never leave me. That is enough. I choose contentment — not because circumstances are perfect, but because You are present and that changes everything. Amen. 💜"
    },
    "03-09": {
        "title": "Sweet Water From a Bitter Place",
        "devotionalText": "God doesn't always relocate you from your bitter situation — sometimes He transforms the bitter water right where you're standing.\n\nThree days without water in the wilderness of Shur. The people of Israel had crossed the Red Sea on dry ground, watched the most powerful military in the world drown behind them, and now they were thirsty in the desert. When they finally found water at Marah, it was bitter — undrinkable. The gap between desperate need and available supply was cruel.\n\nMoses cried out to God. God showed him a piece of wood. Moses threw it into the water. And the water became sweet.\n\nThe piece of wood is not incidental. In Scripture, wood becomes a recurring image for the cross — the tree on which Christ hung, absorbing every curse, every bitterness, every consequence of a world gone wrong. When you trace the line from Marah to Calvary, you see God's pattern: He transforms bitter waters by introducing the tree.\n\nThe bitterness in your life — the relationship that soured, the disappointment that curdled into cynicism, the grief that turned every good memory into an ache — God has not asked you to pretend it isn't bitter. He is not in the business of denial. He is in the business of transformation.\n\nBut transformation requires trust. Moses had to throw the wood in. He had to take the action God showed him, in the direction of the very problem, before the water changed. You don't get to watch from a distance. You bring what God shows you to the bitter place, and you trust that the same God who sweetened the waters at Marah can sweeten yours.\n\nJesus, I bring You my bitter waters. Don't let me run from them or pretend they aren't real — meet me in them. Introduce what only You can introduce. Transform what I could not change. Make my testimony a testimony of Your sweetening power. Amen. 💜"
    },
    "04-09": {
        "title": "What God Saw Before Anyone Else Did",
        "devotionalText": "David was out in the field when Samuel arrived — and God had already decided before anyone thought to include him in the invitation.\n\nThe scene is one of the most revealing in the Old Testament. God sends the prophet Samuel to Jesse's house to anoint the next king of Israel. Jesse brings out his sons — impressive, eldest first, Eliab so kingly in appearance that Samuel thinks: surely this is the Lord's anointed. And God says: I have rejected him. The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart.\n\nSeven sons pass before Samuel. Seven rejections. And then: are these all the sons you have? Well, the youngest is out with the sheep. Samuel says: send for him. We will not sit down until he arrives.\n\nDavid arrives — and he is ruddy, with beautiful eyes and a fine appearance. Not impressive by the criteria that matter to people, not at all the expected choice. But the Lord says: rise and anoint him. And from that day on, the Spirit of the Lord rushed upon David.\n\nWhat you are doing in obscurity right now is not irrelevant to what God is preparing. David was tending sheep — faithful, consistent, invisible. He was developing the very character that would make him a shepherd-king, the kind who walked into valley of the shadow and came out knowing something about the Lord's presence.\n\nGod is not looking at your résumé. He is looking at your heart. And He often does His most significant preparing when no one important is watching.\n\nFather, You see what no one else sees — the faithfulness in obscurity, the heart in the hidden place. Anoint what You've been preparing in me. What I'm doing in the field matters, even when the invitation hasn't come yet. Amen. 💜"
    },
    "05-09": {
        "title": "The Logic of a Father's Heart",
        "devotionalText": "If even broken human fathers give their children what they ask for, what does that tell you about the generosity of a perfect Father?\n\nJesus is in the middle of teaching about prayer, and He makes an argument from lesser to greater that no rational person can resist. He asks the crowd — and through Matthew, He asks you — to think about your own father. If your child asks for bread, does he give him a stone? If he asks for a fish, does he give him a snake? Of course not. Even the most ordinary, imperfect, self-centered human father wouldn't do that to his own child.\n\nAnd then the turn: if you, then, though you are evil, know how to give good gifts to your children, how much more will your Father in heaven give good gifts to those who ask Him?\n\nYou are evil in this context does not mean morally depraved — it means you are fallen, limited, compromised by self-interest. You are the lesser in this comparison. Your capacity for generosity is limited by your selfishness, your fatigue, your resources, your moods. God's is not limited by any of those things.\n\nHow much more. That phrase contains everything. Your Father is not reluctant. He is not waiting to be convinced. He is not measuring your spiritual performance before releasing good gifts. He is a Father with infinite resources, infinite love, infinite generosity — and He is your Father. You are His child.\n\nThe logic dismantles every version of God as stingy, as holding back, as making you prove yourself before blessing you. A Father who gives good gifts doesn't make His children earn them. He gives because He is a Father and you are His child and good things are what Fathers give.\n\nFather, Your love is not withholding — it is giving. I come as Your child, asking, trusting that You are better than any human father. Give me good gifts today, not because I deserve them, but because that's who You are. Amen. 💜"
    },
    "06-09": {
        "title": "When God Stands Up",
        "devotionalText": "There is a posture God takes when the enemy moves against His people — and it is not passive.\n\nPsalm 68 opens with a battle cry that is also a declaration about the nature of God: may God arise, may his enemies be scattered; may his foes flee before him. The Hebrew word for arise — qum — is the posture of someone who has been seated, standing to their feet in response to something that requires action. This is not the passive, indifferent God of philosophical speculation. This is the living God rising up.\n\nThe imagery is borrowed from Numbers 10, when Moses would pray these words every time the ark of the covenant moved: rise up, Lord, and let your enemies be scattered. Israel learned something in the wilderness that translated into every subsequent generation: when God moves, resistance evaporates. Enemies don't just retreat — they scatter. They flee as smoke is blown away, as wax melts before fire.\n\nAnd who is this God? He is the Father of the fatherless, defender of widows — God in his holy dwelling. He sets the lonely in families, leads out the prisoners with singing. The God who scatters enemies is the same God who notices the orphan and the widow, who remembers the forgotten, who liberates the imprisoned.\n\nThe enemies you face — whether they are external opposition, internal strongholds, or forces working against what God has called you to — are facing a God who does not watch passively. He is a God who arises. Who moves. Who answers the cry of His people by standing up in their defense.\n\nYou are not fighting alone. You are fighting with someone who is already up.\n\nFather, arise on my behalf. Scatter what is working against Your purposes in my life. Be the defender of the defenseless, the freedom-bringer for the imprisoned, the family-giver for the lonely. Rise up, and let Your enemies be scattered. Amen. 💜"
    },
    "07-09": {
        "title": "The Grace That Grace Cannot Compete With",
        "devotionalText": "Law and grace cannot coexist as equally valid paths — one has been made obsolete by the other, and the obsolete one kills.\n\nPaul makes a stark declaration in Galatians 2:21: I do not set aside the grace of God, for if righteousness could be gained through the law, Christ died for nothing. This is as decisive as a theological statement can be. Either the law can make you righteous, or grace can. If the law can do it, Christ's death was unnecessary — a divine overreaction. If Christ's death was necessary, then the law was definitively insufficient.\n\nThe logic works only one way. The cross proves the law's inadequacy. If any person had ever achieved sufficient righteousness through law-keeping, the logic of the crucifixion breaks down. But no one did. Every sacrifice ever offered in the temple was another acknowledgment that the sin problem persisted, that nothing human beings could offer was sufficient to permanently close the gap.\n\nChrist's death was not another sacrifice added to the list. It was the final sacrifice that made all previous sacrifices retroactively pointing forward to it, and all future sacrifice unnecessary. He absorbed what the law demanded. He met every standard. He satisfied every requirement.\n\nSetting aside grace means treating it as insufficient — returning to law-keeping as the mechanism of right standing before God. Paul says he will not do this. And neither should you. Every time you operate as though your standing before God depends on your behavioral performance, you are functionally setting aside grace. You are treating the cross as insufficient.\n\nGrace is not a supplement to law-keeping. It is its replacement.\n\nFather, I refuse to set aside grace. I do not add law-keeping to what Christ finished. His death was not for nothing — it was for everything. I rest in the righteousness He provided, not the one I could never achieve. Amen. 💜"
    },
    "08-09": {
        "title": "What He Carried That You Were Supposed to Carry",
        "devotionalText": "There is a moment in Isaiah 53 that is almost too much to look at directly — because it describes what was done to an innocent person on your behalf.\n\nIsaiah wrote this chapter seven hundred years before Jesus was born. He had never seen a crucifixion. He had no word for it. And yet he describes with almost forensic precision what would happen to the Servant of the Lord: pierced for our transgressions, crushed for our iniquities. The punishment that brought us peace was upon him, and by his wounds we are healed.\n\nPierced. Crushed. Punished. These are not metaphors for mild inconvenience. This is the language of violent, devastating suffering — the kind that breaks the body and ends the life. And the prophet identifies the cause with startling clarity: our transgressions. Our iniquities. Not His sin — ours. He carried what belonged to us.\n\nBut then the flip side: we are healed. By his wounds we are healed. The damage done to Him produces repair in us. The punishment absorbed by Him produces peace for us. This is an exchange that has no parallel in any human system of justice — the guilty party receives the benefit, and the innocent party receives the penalty.\n\nYou may carry guilt from things you've done or left undone. You may carry shame from things that were done to you. You may carry the ache of wounds that have not fully healed. Isaiah's prophecy speaks into every one of these: the healing is available, already purchased, already paid for in the suffering of the One who was pierced on your behalf.\n\nThis is not religion. This is the most personal transaction in the universe.\n\nJesus, You were pierced for my transgressions — the very sins I carry guilt about, the specific wounds in my story. I receive the healing that Your wounds purchased. What was put on You is taken off me. I receive that exchange with everything I have. Amen. 💜"
    },
    "09-09": {
        "title": "The Mountains That Will Never Move Again",
        "devotionalText": "God has made you a promise that He sealed not with words but with something even more permanent — His own sworn oath.\n\nIsaiah 54 contains one of the most breathtaking covenant declarations in all of Scripture. God speaks to a people who have just endured devastating judgment — exile, loss, the apparent abandonment of every promise. And He comes with an oath that references the most catastrophic event in human history: to me this is like the days of Noah. When I swore that the waters of Noah would never again cover the earth — I am swearing now.\n\nThe flood was not just a natural disaster. It was a judgment so total that it required a divine covenant to ensure it would never happen again. God sealed that covenant with a rainbow — a visible, permanent reminder in the sky. And now He says: my covenant of peace is like that. It will not be shaken.\n\nThough the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken. Mountains are the most stable things visible in the ancient world — permanent landmarks, unchanged through generations. If those move, my love for you still doesn't. The hills can be removed. My peace will not be.\n\nThis was spoken to people who had experienced the shaking of everything they trusted. Their city destroyed, their temple reduced to rubble, their national identity in pieces. And God comes with an oath: what I have sworn to you is more permanent than the mountains.\n\nYour circumstances may be shaking. Your stability may feel like it's gone. But there is a love sworn to you that the shaking cannot touch.\n\nFather, Your unfailing love is more permanent than the mountains. Though everything around me shakes, Your covenant of peace holds. I stand on what You swore, not what I see. Nothing that can shake will ever shake Your love for me. Amen. 💜"
    },
    "10-09": {
        "title": "The Geography of the Righteous",
        "devotionalText": "Righteousness is not just a legal status — it is a territory, and God has placed you so far inside it that oppression cannot find the address.\n\nIsaiah 54:14 describes the dwelling place of those who belong to God with language that is almost architectural: in righteousness you will be established. You will be far from oppression, for you will not fear. You will be far from terror, for it will not come near you.\n\nFar from oppression. Not freed from oppression after a struggle. Established so firmly in righteousness that oppression cannot reach the address. The geography is the key — you are positioned inside something that creates distance from what used to have access to you.\n\nThe word established in the Hebrew carries the image of being founded, being set on a firm base the way a city is built on bedrock. When God establishes something, He is not providing a temporary arrangement to be reconsidered. He is laying a foundation that is meant to hold weight indefinitely.\n\nYou will not fear — because the fear was connected to the old geography. When you lived in the territory of the unrighteous, oppression was a valid threat. But now you are positioned differently. The fear of the Lord displaces every other fear not by suppressing it through effort, but by filling the space that fear used to occupy.\n\nTerror will not come near you. Not because you are protected from the knowledge that danger exists in the world, but because the God who established you in righteousness is between you and everything that would terrorize you.\n\nYou are not just forgiven. You are relocated. Moved into a territory where oppression does not have a route to your door.\n\nFather, I am established in righteousness — far from oppression, far from terror. I live in the territory You created for me, where fear has no authority. Let me inhabit this address fully, without returning to the old geography. Amen. 💜"
    },
    "11-09": {
        "title": "Not Your Own Righteousness — His",
        "devotionalText": "Every attempt you make to build your own righteousness is ultimately a rejection of what Christ offers — and the exchange He offers is infinitely better.\n\nPaul's autobiography in Philippians 3 is one of the most stunning reversals in personal testimony. He lists his credentials: circumcised on the eighth day, of the people of Israel, of the tribe of Benjamin, a Hebrew of Hebrews, as to the law a Pharisee, as to zeal a persecutor of the church, as to righteousness under the law, blameless. He was the most qualified religious performer of his generation.\n\nAnd he calls all of it loss. Garbage. Worthless — not because the things themselves were evil, but because he was using them to build a righteousness of his own, when something infinitely better was available.\n\nThe righteousness that comes through faith in Christ — that is what he wants to be found in. Not his own righteousness, which comes from the law. The righteousness that comes from God on the basis of faith. There are two kinds of righteousness on the table. One is self-manufactured, built from performance and compliance, capable of producing pride but not peace. The other comes from God — given, not earned, accessed through trust rather than labor.\n\nTo know Christ and the power of His resurrection, and the fellowship of sharing in His sufferings — Paul wants this more than he wants the blameless performance record. Because the performance record kept him focused on himself. The righteousness from God keeps him focused on Christ.\n\nStop building your own righteousness. The one on offer from God is better in every way — and it comes free.\n\nJesus, I release every attempt to build my own righteousness and receive Yours. I want to be found in You — not having a righteousness of my own, but the one that comes from God through faith. This is the better thing. Amen. 💜"
    },
    "12-09": {
        "title": "Confidence Before the Throne",
        "devotionalText": "You have been invited to approach a throne that should terrify you — and the invitation includes confidence.\n\nThe tabernacle and temple in Israel were designed with careful gradations of holiness. The outer court, the inner court, the Holy Place, and then the Holy of Holies — separated by a thick curtain, accessible to one priest once a year, and even then only after elaborate ritual preparation. The message was architectural: God is holy, you are not, and the gap requires an entire system of mediation to navigate safely.\n\nThen the curtain tore from top to bottom on the afternoon of the crucifixion. And the writer of Hebrews, reflecting on what that torn curtain meant, writes one of the most liberating invitations in Scripture: let us therefore approach God's throne of grace with confidence.\n\nWith confidence. The Greek word is parresia — it means freedom of speech, boldness, the right to speak openly. This is the kind of access a citizen has to their representative, a child has to their parent. Not trembling at the door. Not hoping to be noticed. Walking in with the confidence of someone who belongs there.\n\nBecause of what? Because you have a great high priest who has gone through the heavens — Jesus the Son of God — who is able to empathize with your weaknesses because He was tested in every way, just as you are, yet He did not sin. He is not a high priest who can't relate to your struggle. He has been in the human body, in the temptation, in the pressure. He knows.\n\nYou will find mercy. You will find grace. That is what the throne offers — not judgment, not evaluation, not a performance review. Mercy and grace, at the moment of need.\n\nJesus, I come boldly — not on my own merit, but on Yours. You are my great high priest, familiar with everything I face. I need mercy today, and I need grace. I receive both from the throne You have opened to me. Amen. 💜"
    },
    "13-09": {
        "title": "What the Natural Mind Cannot Access",
        "devotionalText": "There are things about God that logic cannot reach and intelligence cannot deduce — and God made them accessible through a different faculty entirely.\n\nPaul's declaration in 1 Corinthians 2:14 is sometimes uncomfortable to modern ears: the person without the Spirit does not accept the things that come from the Spirit of God but considers them foolishness. This is not a statement about intelligence. Paul himself was one of the most rigorous intellectual minds of his generation. The issue is not capacity — it is category.\n\nThe things of the Spirit belong to a different category of knowledge than what natural human reasoning can access. A microphone cannot detect colors. It's not defective — it's simply not the right instrument for that kind of data. Natural human reasoning is not defective when it fails to grasp spiritual truth. It is simply operating without the instrument that makes spiritual knowledge possible.\n\nBut the spiritual person judges all things. The word judges here means to examine, discern, penetrate to the real nature of something. The person with the Spirit has the capacity to perceive what is actually happening spiritually in any situation — to see beneath the surface of events to the divine activity, to recognize the work of God where others only see coincidence or chaos.\n\nThis is not a reason for spiritual arrogance. It is a reason for profound gratitude and dependence. You did not generate this capacity in yourself. The Spirit was given to you — and with the Spirit came the ability to receive, understand, and live from what the natural mind cannot touch.\n\nYou have access to insight that the most brilliant unspiritual person cannot access. Use it. Ask for it. Depend on it daily.\n\nHoly Spirit, I rely on You for the knowledge that natural reasoning cannot reach. Open my spiritual perception today — let me see what is actually happening beneath the surface of my circumstances. Give me discernment that exceeds my natural intelligence. Amen. 💜"
    },
    "14-09": {
        "title": "Living Stones in a Living Temple",
        "devotionalText": "You did not join a religious institution. You came to a living Person — and His life is flowing into you and making you into something you could never become alone.\n\nPeter's language in 1 Peter 2:4-5 is striking in its living quality. Jesus is the living Stone — rejected by people but chosen and precious to God. You come to Him, and in coming to Him you become living stones — built into a spiritual house that is being constructed by the same God who chose the cornerstone.\n\nThe cornerstone was the first and most critical stone placed in any ancient building. Every other stone was measured and aligned relative to it. Plumb lines were dropped from it. Angles were set by reference to it. Get the cornerstone right and the whole structure could be aligned. Get it wrong and nothing else could compensate.\n\nChrist is that stone. He was rejected by the builders — the religious authorities who evaluated Him and concluded He was not the kind of material they were looking for. But God chose Him and placed Him. And now every other stone in the structure — every person who comes to Christ — is aligned relative to Him.\n\nYou are a living stone. Not a dead stone placed by a builder and sitting inert. A living stone — animated by the same life that animates the cornerstone, contributing to a spiritual house in which God is offering spiritual sacrifices through the priesthood of every believer.\n\nYou matter to the structure. The building is not complete without your stone. And your stone is alive because it is connected to the One who is Life itself.\n\nJesus, You are the living Stone — rejected by people, chosen by God. I come to You and receive the living quality that only You give. Make me into the stone I was designed to be, aligned to You, contributing to what God is building. Amen. 💜"
    },
    "15-09": {
        "title": "The Identity That Was Chosen Before You Were Born",
        "devotionalText": "You did not choose your identity in Christ — it was chosen for you, before history began, by a God who does not make random selections.\n\nThe words Peter writes in 1 Peter 2:9 were originally spoken over Israel at Sinai, and now they are spoken over everyone who is in Christ: you are a chosen generation, a royal priesthood, a holy nation, His own special people.\n\nChosen. Royal. Holy. Special. Every one of these designations runs against the grain of how the world would classify the people receiving this letter — scattered exiles, social outsiders, belonging nowhere in particular by the world's measure. And Peter says: no, actually, you belong to a category that the world doesn't have the vocabulary to describe.\n\nA royal priesthood is a staggering combination. Priests were not kings. Kings were not priests. The mixture was forbidden in Israel — when King Uzziah tried to burn incense in the temple, he was struck with leprosy on the spot. But in Christ, the two roles are fused. You have access to God as a priest — able to enter His presence, offer spiritual sacrifices, stand before Him. And you carry the dignity and authority of royalty.\n\nHis own special people — the Greek word is peripoiesis, meaning a possession treasured above all others. Not a possession that is merely owned, but one that is valued, guarded, delighted in.\n\nAnd the purpose: that you may declare the praises of Him who called you out of darkness into His wonderful light. Your identity is not just for your benefit. It is the basis from which you reflect His character into the world around you.\n\nFather, I receive who You say I am — chosen, royal, holy, Yours. I stop letting the world's categories define me. You called me out of darkness into wonderful light, and I will declare what that looks like. Amen. 💜"
    },
    "16-09": {
        "title": "The Separation That Cannot Happen",
        "devotionalText": "There is a list of everything that could possibly separate you from God's love — and Paul works through it with the confidence of someone who already knows how it ends.\n\nRomans 8:38-39 reads like a courtroom argument, systematically eliminating every possible threat. Death — the thing that ends every human relationship. Life — with all its complications and moral failures. Angels — the supernatural beings that Paul has already explained could not be compared to the Son. Demons — the opposing spiritual forces. The present, with its immediate pressures. The future, with its unknown dangers. Height. Depth. Anything else in all of creation.\n\nNot one of them. Cannot. Not might not, not probably won't. Cannot. The Greek word is dunesetai — will not be able. It is grammatically a statement about capability, not probability. These things don't have the ability to separate you from the love of God in Christ Jesus our Lord.\n\nWhy not? Because the love is not maintained by your performance or your circumstances. It is a love that is in Christ Jesus — meaning it exists within the sphere of an unbreakable relationship. You are in Christ. The love is in Christ. And nothing can remove you from Christ, because you are held by the same power that raised Him from the dead.\n\nThis is not an invitation to live carelessly. It is an invitation to live fearlessly. The person who knows they cannot be separated from God's love doesn't drift away from God — they run toward Him without the terror that they might reach Him only to be rejected.\n\nYou are loved with the most durable love in the universe. It will hold.\n\nFather, I am convinced — nothing can separate me from Your love. Not my past, not my failures, not the forces working against me, not my own weakness. Your love holds. I live from that certainty today. Amen. 💜"
    },
    "17-09": {
        "title": "Not Just Surviving — Overwhelming",
        "devotionalText": "There is a difference between barely making it through something and going through it with such abundance of grace that you come out more than you went in with.\n\nPaul's phrase in Romans 8:37 is almost extravagant: in all these things we are more than conquerors through him who loved us. The things in question are significant — tribulation, distress, persecution, famine, nakedness, peril, sword. He is not describing minor inconveniences. He is describing the kind of suffering that Paul himself had personally experienced.\n\nMore than conquerors — the Greek is hypernikao. A conqueror wins. More than a conqueror wins so completely that the victory becomes something else, something bigger. The word hyper is the intensifier — beyond, above, in excess of. You don't just get through — you get through and come out the other side carrying more than you had before.\n\nThrough him who loved us. The instrument is crucial. This overwhelming victory is not produced by human tenacity or spiritual willpower. It flows from the love of the One who faced every one of these conditions on your behalf and came out the other side of death itself. His love doesn't just protect you from the battle — it transforms you through it.\n\nThis is one of the most encouraging reframings of difficulty in all of Scripture. You are not just going to survive what you're going through. You are going to come out the other side with something you didn't have before. The suffering is not wasted. The difficulty is not merely endured. Through the love of the One who overcame it all, you overwhelm it.\n\nLord, I don't just survive — I overwhelm, through You who loved me. Nothing I face today is stronger than the love that conquered death. I go through difficulty not as a victim but as a more-than-conqueror. Amen. 💜"
    },
    "18-09": {
        "title": "If God Is For You",
        "devotionalText": "The question Paul asks in Romans 8 is not rhetorical — it is the most important question you will ever ask about your own life, and the answer reframes everything.\n\nWhat then shall we say in response to these things? Paul has just finished painting a picture of unstoppable divine purpose — predestined, called, justified, glorified. And then he asks: if God is for us, who can be against us?\n\nThe if here is not doubt — in the original Greek, it is a first-class conditional that assumes the condition is true. Since God is for us. Given that God is for us. And given that — who can stand in opposition with any real power?\n\nThis is not a promise that no one will oppose you. History, and Paul's own biography, make clear that opposition is real and sometimes violent. People will be against you. Circumstances will seem to work against you. There will be seasons when everything feels like resistance.\n\nBut the question is not whether anyone is against you. The question is whether anyone against you has power that exceeds the power of the God who is for you. And the answer to that question is definitive: no. The enemies of your soul do not have a force greater than the God who chose you, called you, and has staked His own character on your completion.\n\nHe who did not spare His own Son — but gave Him up for us all — how will He not also, along with Him, freely give us all things? The cross is the proof. God demonstrated His commitment to you at the highest possible cost. If He was for you enough to give His Son, He is for you enough to handle everything else.\n\nGod is for you. Receive that today like it's the most important fact in the universe — because it is.\n\nFather, You are for me — and if You are for me, nothing that comes against me has the final word. I live from the security of Your presence on my side, knowing the cross already proved how completely You've committed to me. Amen. 💜"
    },
    "19-09": {
        "title": "The Gift That Comes With Everything Else",
        "devotionalText": "God has a pattern: when He gives you His Son, He is not giving you one thing. He is giving you everything.\n\nPaul's argument in Romans 8:32 moves from the greatest gift to all other gifts through a logic that is almost mathematically clean. He who did not spare His own Son, but gave Him up for us all — how will He not also, along with Him, graciously give us all things?\n\nHe did not spare. Abraham was asked to not spare Isaac — to offer the thing he loved most. And God intervened and provided a ram. But for His own Son, God did not intervene. He let the death happen. He watched the abandonment on the cross — My God, my God, why have you forsaken me — and did not spare. Because you were the one being spared.\n\nIf that is the level of God's commitment to you — the willingness to give the most costly thing in the universe — then what is the logic of worrying that He might withhold smaller provisions? If He didn't hold back the Son, what exactly are you afraid He's going to keep from you?\n\nAlong with Him, all things. The all things are not an afterthought. They come bundled with the Son. When you received Christ, you received the Father's commitment to provide everything needed for the life He has called you to live.\n\nThis changes the nature of prayer. You don't have to convince a reluctant God to give. You are asking a Father who has already demonstrated the full extent of His generosity — and asking for things that are small by comparison to what He already gave.\n\nFather, You gave me Your Son — and with Him, You give me everything. I release every fear that You might withhold what I need. The cross proved Your commitment. I ask with confidence, knowing You are not stingy with the children You love. Amen. 💜"
    },
    "20-09": {
        "title": "The Chain That Pulls You to Glory",
        "devotionalText": "Your glorification is not something God is hoping for — it is the last link in a chain that has been pulling since before the world began.\n\nRomans 8:30 contains one of the most audacious claims about divine purpose in the entire New Testament. Paul lists five verbs in a single sentence, each one the consequence of the one before: those he predestined, he also called; those he called, he also justified; those he justified, he also glorified.\n\nGlorified — past tense. Not will glorify. Glorified. The verb is aorist — a completed action. From God's perspective, your glorification is so certain that it can be spoken of as already accomplished. You are not hoping to end up glorified. You are already on the chain that leads there, and the chain has no break in it.\n\nNotice where the chain begins: foreknew. God knew you before creation. He loved you before history. He predestined your purpose before you existed. And from that eternal starting point, the chain has been moving toward your calling, your justification, your glorification without interruption.\n\nThis means your ultimate transformation into the image of Christ is not in question. It is not dependent on your maintaining some threshold of spiritual performance. It is dependent on the God who began the chain — and He does not begin things He does not finish.\n\nYou are being pulled toward glory. Not by your effort — by His purpose. Not by your consistency — by His calling. The same God who foreknew you before you were born is the same God who will glorify you when the process is complete.\n\nThat chain does not break.\n\nFather, I am on the chain You began before the world — predestined, called, justified, and being brought to glory. The outcome is not in question because You are not uncertain. I rest in the certainty of what You've already set in motion. Amen. 💜"
    },
    "21-09": {
        "title": "Old Things and New Things",
        "devotionalText": "There is a moment in time when the old story ends and the new one begins — and for anyone in Christ, that moment has already happened.\n\nPaul writes 2 Corinthians 5:17 with a declarative certainty that leaves no room for qualification: if anyone is in Christ, the new creation has come: the old has gone, the new is here. Not the old is fading. Not the new is coming. The old has gone. The new is here. Accomplished, finished, present tense.\n\nThe Greek word for new creation is kaine ktisis — a fresh creation, a new kind of existence that didn't exist before. Not a renovation of the old. Not a patched-up version of the previous model. A genuinely new thing, of a quality that simply wasn't there before. When God made the heavens and the earth in Genesis 1, He spoke kaine ktisis into existence. When you came to Christ, He did it again — this time in you.\n\nThis is not just theological language about a legal change in status. It describes an ontological shift — what you fundamentally are has changed. The person you were in Adam — defined by the old nature, bound to the old patterns, destined for the old end — that person is gone. The new person in Christ inhabits the same body, lives in the same neighborhood, has the same face. But the core of what you are is new.\n\nThe reason Paul can say this with such confidence is that the new creation is not dependent on how you feel or how consistently you are performing. It is the result of what God did in Christ — and what God does is not reversible by what you do.\n\nYou are new. Live from that.\n\nFather, I am a new creation in Christ — not patched or improved, but new. The old has gone. I receive this reality fully today, not as something I'm working toward but as something I already am. Let me live from the new, not the old. Amen. 💜"
    },
    "22-09": {
        "title": "Already Citizens of Somewhere Better",
        "devotionalText": "You have an address that no earthly government can revoke and no earthly circumstance can change.\n\nPhilippians 3:20 lands in the middle of a passage about people who are described as enemies of the cross — people whose minds are set on earthly things, whose god is their stomach, whose glory is their shame. And into this contrast, Paul writes: but our citizenship is in heaven.\n\nIn Paul's day, this was loaded language. Philippi was a Roman colony — its citizens were legally Roman even though they lived far from Rome. Roman citizens had rights and protections that non-citizens didn't have. They were subject to Roman law. They participated in Roman culture. They were, in a meaningful sense, residents of Rome while physically in Macedonia.\n\nPaul takes this concept and elevates it: your real citizenship, your primary political identity, the government under whose authority you actually live — is heaven. Not some future heaven when you die, but the present reality of belonging to a different kingdom than the one your earthly address reflects.\n\nAnd then: we eagerly await a Savior from there, the Lord Jesus Christ. The language is active, forward-leaning. Not passive resignation. Eager awaiting — the posture of someone who knows what is coming and cannot wait to see it. He will transform our lowly bodies to be like his glorious body — the resurrection as the final expression of what the new creation means.\n\nYou are not a permanent resident of this present age. You are a citizen of heaven, living temporarily in a place that is being transformed. The passport you carry is not the one your government issued.\n\nFather, my citizenship is in heaven — I live from that reality today. I am not ultimately shaped by the culture around me because I belong to a different kingdom. I eagerly await what is coming, and I live now as a citizen of where I'm going. Amen. 💜"
    },
    "23-09": {
        "title": "Hidden in the Safest Place in the Universe",
        "devotionalText": "You are hidden — not concealed or forgotten, but tucked safely inside the most secure location that has ever existed.\n\nColossians 3:3 is four words in the Greek that carry an enormous freight: you died, and your life is now hidden with Christ in God. Three realities stacked inside each other like nested containers. Your life is in Christ. Christ is in God. And you are in Christ.\n\nThe imagery of hiddenness is protective rather than secretive. In the ancient world, valuable things were hidden — buried where thieves couldn't find them, stored in impenetrable places. To hide something was to place it where it was safe. When Paul says your life is hidden with Christ in God, he is not saying you are invisible or that your life doesn't matter. He is saying your real life is stored in the most secure location in existence.\n\nThis has immediate practical implications. Your identity cannot be stolen. Your future cannot be removed. The things that matter most about who you are — your standing before God, your inheritance, your eternal destiny — are not sitting on the surface where circumstances can access them. They are hidden. Buried in the impenetrable reality of Christ in God.\n\nWhen Christ, who is your life, appears, then you also will appear with him in glory. The hiddenness is temporary in the sense that the full revelation is still coming. Right now what is truest about you is not fully visible — even to you. But when Christ is revealed in His fullness, you will be revealed with Him.\n\nYour real life is safer than anything on earth has ever been safe.\n\nFather, my life is hidden with Christ in You — secure in the most impenetrable location in the universe. Nothing can access what You are keeping. I stop building identity on what is visible and rest in what is safely hidden. My real life is with You. Amen. 💜"
    },
    "24-09": {
        "title": "The Position That Changes Your Perspective",
        "devotionalText": "You are not a person on earth trying to get access to heaven — you are a person seated in heaven, temporarily serving on earth.\n\nEphesians 2:6 describes a completed reality that most Christians never fully inhabit: God raised us up with Christ and seated us with him in the heavenly realms. Raised. Seated. Both verbs are past tense in the Greek — completed actions with ongoing results. This is not something that will happen. It has happened.\n\nSeated. The image is significant — a seated person is not a striving person. They are not working to maintain position or earn access. They are at rest in a position given to them. When the work of an ancient judge was finished, he sat down. When a king's reign was complete, he sat on his throne. The seated position indicates completed work and established authority.\n\nYou are seated with Christ. Which means you share his vantage point. You are looking at the world from above the circumstances, not inside them. The problems you face are problems you are technically above — not because they aren't real, but because your actual position gives you access to a perspective that transcends them.\n\nMost people live as though they are standing in the middle of their circumstances, surrounded and overwhelmed, trying to find a way out. But the seated position is a different relationship with circumstances entirely. You look down at them, not up. You address them from authority, not from fear.\n\nYour position was assigned by God. It was not earned. You cannot lose it by failing. You can, however, fail to inhabit it — to live as though you're still standing on the ground when you've been seated in the heavens.\n\nFather, I am seated with Christ — above my circumstances, looking down not up. Let me live from this position today. I have a vantage point I didn't earn and cannot lose. I inhabit it by faith, not by feeling. Amen. 💜"
    },
    "25-09": {
        "title": "The Masterpiece Already in Progress",
        "devotionalText": "You are not a rough draft God is hoping to eventually improve — you are the poem He is writing with full intention and artistry right now.\n\nEphesians 2:10 uses the Greek word poiema — the same word from which we get poem. God's handiwork, created in Christ Jesus. You are not a product generated on an assembly line. You are something made with the care and intentionality of an artist who has a specific thing in mind and is working with specific materials to achieve it.\n\nAnd this poem was written for a purpose: to do good works, which God prepared in advance for us to do. Prepared in advance — the works are not improvised. They existed before you did, waiting for the specific shape of you to arrive and carry them out. There is a prepared landscape in which you move, and the works are already placed in it like stepping stones, already prepared for your particular stride.\n\nThis changes the existential question that haunts most human beings: what am I for? You are not here to find your purpose through achievement or performance. You are here to walk into what was prepared for you — which means your purpose is not something you create, it is something you discover as you follow the One who prepared it.\n\nAnd because it was God who prepared the works, you can trust the preparation. He didn't guess at what you would need. He didn't leave out the hard parts and include only the comfortable ones. He prepared what you were made for — which includes the challenging moments, the opportunities that stretch beyond your current capacity, the places where you must trust rather than perform.\n\nYou are a poem being written toward its conclusion. Every line is intentional.\n\nFather, I am Your masterpiece — not someday, but now, in process, being crafted with intention. I walk into the prepared works with confidence, knowing You planned them for this version of me. Amen. 💜"
    },
    "26-09": {
        "title": "Power in the Inner Places",
        "devotionalText": "External change is fragile. Internal transformation is the only kind that lasts — and God's Spirit goes to the root.\n\nPaul's prayer in Ephesians 3:16 targets the deepest part of the person: I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being. The inner being is the place that external disciplines and behavioral modification can never fully reach. It is the center from which everything else flows — the root system of your thoughts, desires, beliefs, and responses.\n\nThe inner being can be strengthened. And the strength that comes into it comes from His Spirit, out of His glorious riches. The riches are relevant because they determine the magnitude of the supply. A person praying from poverty gives what they can spare. God prays from — and provides from — glorious riches. The strength available to your inner being is not the strength of a modest budget. It is the strength of unlimited divine supply.\n\nWhen the inner being is strengthened, Christ dwells more fully in your heart through faith. There is a direct correlation between inner strength and the degree to which Christ takes up residence. The stronger the root, the more the fruit. The deeper the foundation, the taller the structure that can be built on it.\n\nAnd then the capacity grows: being rooted and established in love, you gain the power to grasp dimensions of Christ's love that were previously inaccessible. The inner strengthening creates room for more of Him. More of Him creates room for more of His love. More of His love strengthens the inner being further. It is a cycle that moves in one direction — deeper and richer and more full.\n\nFather, I ask for what Paul asked — power through Your Spirit in my inner being. Go to the root. Build from the inside out. Strengthen what no external effort can reach. Amen. 💜"
    },
    "27-09": {
        "title": "Blessed Before the Day You Were Born",
        "devotionalText": "The blessing God has for you did not originate when you came to faith — it was prepared in eternity and has been waiting for you all along.\n\nEphesians 1:3 opens with one of the longest sentences in the Greek New Testament, and it begins with something that reorients every other word: praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.\n\nEvery. Not some spiritual blessings. Not the ones you've earned by your spiritual performance. Every one. And the location is the heavenly realms — meaning these blessings are not stored in temporary earthly arrangements that can be stolen or lost. They are stored in the only realm that is permanent.\n\nIn Christ. That phrase will appear over and over in Ephesians 1 — in Him, in Christ, in the Beloved. Every blessing is accessed through your union with Christ. Not independently. Not by performance. By being inside the relationship with Him that was established when you believed.\n\nThe blessings were not created after you came to faith. God has already blessed — past tense, completed action. The storehouse was already stocked. The blessings were already prepared. Your faith did not create them; it simply connected you to what was already there.\n\nThis is why you can pray with confidence — not because you are convincing God to provide something He was reluctant to give, but because you are reaching for what has already been prepared. You are not knocking on a closed door. You are opening a door that was already unlocked from the inside.\n\nFather, You have already blessed me with every spiritual blessing in Christ. I reach for what's already been prepared. I am not begging — I am receiving what love already set aside for me. Amen. 💜"
    },
    "28-09": {
        "title": "The Choice Made Before the World Began",
        "devotionalText": "Your identity in Christ was not a response to something you did — it was a decision made before you existed, in the eternal counsel of a God who saw you and chose you anyway.\n\nEphesians 1:4 is one of the most profound verses in the New Testament: He chose us in him before the creation of the world to be holy and blameless in his sight. In love he predestined us for adoption.\n\nBefore the creation of the world. The selection happened before the problem happened. Before Adam's fall, before the long history of human failure, before you were born and capable of anything — God looked across the expanse of all possible people and chose you. The choice was not a response to foreseen faith or anticipated good behavior. It was a sovereign decision made in love before history began.\n\nIn Christ — which is where the choice operates. Your election is not independent of Jesus; it exists inside your union with Him. You were chosen in Him, which means your election and His person are inseparable. To be chosen in Christ is to be brought into the eternal relationship He has with the Father.\n\nThe purpose of the choosing: to be holy and blameless in His sight. In love. This is not the language of legal transaction. In love he predestined us for adoption to sonship through Jesus Christ, in accordance with his pleasure and will. The choosing is affectionate. Pleasurable to Him. Not reluctant or obligatory. He wanted you.\n\nYou are not someone God tolerated into His family. You are someone He chose, before anything you could offer, because He wanted you.\n\nFather, You chose me in Christ before the world began — not because of what You foresaw in me, but because of what You determined for me. I receive that choosing. You wanted me. Let that truth be the foundation of everything I am. Amen. 💜"
    },
    "29-09": {
        "title": "Living on Another Power Source",
        "devotionalText": "Christianity is not a life you live for Christ — it is a life Christ lives through you. The difference is everything.\n\nPaul's testimony in Galatians 2:20 is so radical that it requires several readings before it settles: I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.\n\nTwo lives are described. The old one — the one that died. And the new one — which is not Paul's at all. It is Christ's, expressed through Paul's body, sustained by Paul's faith, powered by the love of the One who gave Himself specifically for Paul.\n\nHave been crucified — perfect passive tense. Happened in the past, results still active. Paul is not in the process of dying. He has died. The person who was striving to establish his own righteousness through religious performance — that person was co-crucified with Christ. And now he is a different entity, animated by a different source.\n\nChrist lives in me. Not helps me. Not inspires me. Lives. This is the most intimate possible description of the Christian life — not Christ alongside me as a companion, but Christ inside me as life itself. His resurrection power is the engine. His love is the fuel. His purposes are the direction.\n\nThe life I now live in the body — in this physical, ordinary, limited, sometimes struggling body — is lived by faith. Not by sight. Not by feelings. By trust in the One who loved me and gave Himself for me. Personally. For me.\n\nJesus, You live in me. I release the self-managed version of my faith and trust You to live through me. Your love that gave Yourself for me is the same love that sustains my life now. Amen. 💜"
    },
    "30-09": {
        "title": "The Name That Bends Everything",
        "devotionalText": "The name of Jesus is not just a title — it is the most powerful word in the universe, and one day every created thing will demonstrate that it knows this.\n\nPhilippians 2:9-11 describes a sequence that is both cosmic and personal. Because of the obedience of Christ — even to death on a cross — God has exalted him to the highest place and given him the name that is above every name. Not a higher name. Not one of the higher names. The name above every name. Every other name in existence is subordinated to this one.\n\nThen the outcome: at the name of Jesus every knee should bow, in heaven and on earth and under the earth, and every tongue acknowledge that Jesus Christ is Lord, to the glory of God the Father. The three realms — heaven, earth, and under the earth — cover every possible category of existence. Nothing that exists is excluded from this final confession.\n\nEvery knee. Not willing knees only. Not knees of those who already believe. Every knee. The opponents, the mockers, the dismissive — every single one will bow. Not because they are forced into a theological position, but because the reality of who Jesus is will be undeniable. You cannot stand upright in the presence of ultimate truth and refuse to acknowledge it.\n\nEvery tongue will acknowledge. The confession is universal and genuine — not coerced, but inevitable. And the outcome is to the glory of God the Father. The exaltation of the Son magnifies the Father who exalted Him.\n\nYou confess now, voluntarily, in faith. One day that confession will be made by all creation, without exception. You are on the right side of the only truth that matters.\n\nJesus, every knee will bow at Your name — and I bow mine now, willingly, in love. You are Lord over all creation, and You are Lord over my life. I confess what the universe will one day confess: Jesus Christ is Lord. Amen. 💜"
    }
}

# Load the JSON
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'r') as f:
    data = json.load(f)

# Apply rewrites
updated = 0
for i, d in enumerate(data['devotionals']):
    if d['date'] in SEPTEMBER_REWRITES:
        data['devotionals'][i]['title'] = SEPTEMBER_REWRITES[d['date']]['title']
        data['devotionals'][i]['devotionalText'] = SEPTEMBER_REWRITES[d['date']]['devotionalText']
        updated += 1

print(f"Updated {updated} September devotionals")

# Save back
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved successfully")
