#!/usr/bin/env python3
import json

OCTOBER_REWRITES = {
    "01-10": {
        "title": "Your Inheritance Is Waiting",
        "devotionalText": "God qualified you for the richest inheritance in existence — not by reviewing your performance, but by sending His own Son in your place.\n\nThe word qualified carries everything. To be qualified means the standard was fully met — not partially, not provisionally, but completely. God examined every requirement for sharing in the inheritance of the saints, then satisfied every single one through Jesus, so that you could walk in as though you had earned it — even though you never could have.\n\nThis inheritance exists inside the kingdom of light, which means you already live there. Not heading toward it someday. Already in it. The transfer happened the moment you placed your trust in Christ. You are not a servant waiting to be rewarded. You are an heir who already lives in the family estate.\n\nHere is what that means for whatever you are carrying today. You do not have to earn your way to God's goodness. You do not have to get yourself together before He moves on your behalf. Heirs don't earn what they inherit — they simply receive it. That is the posture God is drawing you into right now.\n\nYou can trust this because the Father sealed the covenant not with words but with blood. The cross is the irrevocable document that transferred everything belonging to Christ directly to you. That transaction does not get renegotiated on your hardest morning.\n\nYou are already qualified. Already positioned inside the light. Walk through today like someone who has received everything — because in Christ, you have.\n\nFather, I am qualified — not by anything I achieved, but by everything Jesus secured. I am Your heir, already living in the kingdom of light. I receive this inheritance with open hands and a full heart. Your love wrote me into the will, and nothing can write me out. Amen. 💜"
    },
    "02-10": {
        "title": "Rescued and Relocated",
        "devotionalText": "God did not wait for you to find your way out of darkness — He came in and carried you out Himself.\n\nThe word rescued is past tense and it is permanent. The prison break already happened. The chains already fell. You are not waiting to be rescued — you have been rescued. This is not a future hope. This is a finished reality. The God who created universes looked at the dominion that had you and said, Not anymore, and then He acted.\n\nBut He didn't just pull you out of one place — He moved you into another. Brought us into the kingdom of the Son He loves. You were not just freed from darkness; you were relocated to love. You have a new kingdom, a new King, and a new address. You belong somewhere now. Somewhere good. Somewhere permanent.\n\nThis changes how you see this morning. Whatever feels dark in your life right now — whatever feels like it still has a grip — the truth is you no longer live under its dominion. You live under the authority of the One who loves you. That darkness has no legal claim on you.\n\nYou can trust this because the God who rescued you has never lost anyone He carried. He did not bring you this far to abandon you. He is the same God who parted seas and emptied tombs. Your situation is not beyond His reach.\n\nYou have been relocated to the kingdom of love. That is your permanent address. Live from that place today.\n\nFather, You rescued me — past tense, finished, settled. I am out of darkness and inside the kingdom of Your beloved Son. Nothing has dominion over me that You have not already defeated. I live in love, not fear. Thank You for carrying me home. Amen. 💜"
    },
    "03-10": {
        "title": "The God Who Moved In",
        "devotionalText": "The living God did not simply agree to help you from a distance — He moved into you and made you His permanent home.\n\nPaul makes a staggering claim in Romans 8: if the Spirit of God lives in you, you are no longer in the realm of the flesh — you are in the realm of the Spirit. That is a total transformation of address. You don't just have access to God's presence; you are indwelt by it. The same Spirit who hovered over creation, who raised Christ from the dead, chose your body as His dwelling place.\n\nThis is not temporary. The Spirit doesn't visit when you pray hard enough or leave when you fail. He lives there. Present tense, continuous tense, permanent tense. You carry divine presence into every room you walk into, every conversation you have, every battle you face.\n\nThink about what this means for your day. You are not trying to get God's attention — He is already inside you. You are not reaching up hoping He reaches down — He is closer than your own heartbeat. The Spirit who intercedes, who leads, who empowers — He is already there, already active, already working.\n\nYou can trust this because God does not take up residence in temporary arrangements. He is not a guest who leaves in the morning. He promised to never leave or forsake you, and He sealed that promise by taking up permanent residence within you.\n\nYou are a walking sanctuary. Act like one today.\n\nHoly Spirit, You live in me — not occasionally, not provisionally, but permanently. I carry Your presence everywhere I go. I am never alone, never abandoned, never without divine help. Thank You for choosing me as Your home. Amen. 💜"
    },
    "04-10": {
        "title": "Led by the Father's Own Spirit",
        "devotionalText": "The way you know you are a child of God is not by how perfectly you perform — it is by who is leading you.\n\nRomans 8:14 contains one of the most identity-forming statements in all of Paul's letters: those who are led by the Spirit of God are the children of God. The Spirit is the evidence of sonship. Not achievement, not spiritual résumé, not the absence of failure — the presence of the Spirit, and the experience of being led by Him.\n\nLed by the Spirit means more than receiving occasional guidance. It describes a life that is oriented toward the Spirit's movement — sensitive to His prompting, responsive to His leading, willing to follow even when the direction is uncomfortable. The Spirit doesn't overpower your will. He leads. And you choose to follow.\n\nBut notice what Paul says in the very next verse: you did not receive a spirit of slavery to fall back into fear. The alternative to Spirit-led living is fear-driven living — the exhausting existence of a slave who performs to avoid punishment, who works to maintain standing, who lives in dread of the moment performance fails. That is not the life God gave you.\n\nYou received the Spirit of adoption. And in that Spirit, you cry out Abba, Father — the intimate Aramaic word for father that small Jewish children used, closer to Daddy than the formal Father. That is the cry the Spirit produces in you. It is the cry of a child who knows they belong, who is not afraid of the one they're addressing, who runs toward rather than away.\n\nYou are led. You are loved. You are a child.\n\nFather — Abba — I am led by Your Spirit, which makes me Your child. I release the spirit of fear and embrace the spirit of adoption. I run toward You today, not away from You. You are my Father. Amen. 💜"
    },
    "05-10": {
        "title": "Not a Slave — A Son",
        "devotionalText": "The most important distinction in your spiritual life is not between sinning and not sinning — it is between the identity of a slave and the identity of a child.\n\nRomans 8:15-16 describes two spirits that could be operating in a person's life. The spirit of slavery produces fear — the constant anxiety of a person whose standing is always in question, who can never do enough, who lives under the threat of rejection. It is the spirit of religious performance, of trying to maintain God's approval through consistent behavior.\n\nBut the Spirit you received — the one God gave you when you came to Christ — does not make you a slave. It is the Spirit of adoption, and it witnesses directly to your spirit that you are God's child. Not a servant. Not a contractor. A child.\n\nThe word Paul uses for the Spirit's witness is summartureo — to testify alongside, to confirm. The Holy Spirit is actively testifying within you, alongside your own spirit, confirming: you are a child of God. This is not wishful thinking. This is divine witness. The third person of the Trinity is speaking your identity into you from the inside.\n\nA child of God does not approach the Father in fear. They approach with confidence — not the confidence of earned merit, but the confidence of belonging. A child asks their father for what they need without rehearsing arguments for why they deserve it. They ask because they belong to the household and the father's resources are the family's resources.\n\nYou are not a slave managing your performance. You are a child living in the Father's house.\n\nHoly Spirit, witness to me today — confirm in my heart what is already true: I am a child of God. I release every slave mentality that approaches the Father in fear. I come as Your child, confident in belonging, not in performance. Amen. 💜"
    },
    "06-10": {
        "title": "Co-heirs With the One Who Has Everything",
        "devotionalText": "You are not just saved — you are an heir. And the estate you've been written into belongs to the Son of God.\n\nRomans 8:17 builds on the adoption language of the previous verses and arrives at a conclusion that staggers the imagination: if we are children, then we are heirs — heirs of God and co-heirs with Christ. Heirs of God. Not heirs of a portion of God's estate. Heirs of God Himself — which means the inheritance includes everything that belongs to the Father.\n\nCo-heirs with Christ — which means you share the same inheritance that Jesus Himself inherits. Not a lesser portion for the adopted children while the Son gets the real estate. The same inheritance, shared together, because you are truly family.\n\nBut Paul adds a phrase that deserves honest attention: if indeed we share in his sufferings in order that we may also share in his glory. The path to shared glory runs through shared suffering. Not earned glory — shared glory. Not your suffering earning anything, but your suffering being connected to His, the way a vine is connected to branches. His resurrection is the destination. His cross is the path.\n\nThis is not a reason for fear. It is a reason for reframing. The difficulties you face are not evidence that God has withdrawn. They may be the very path on which you are experiencing the fellowship of His suffering — the deeply intimate place where the crucified Christ walks closest to those who are hurting.\n\nShared suffering, shared glory. Co-heirs in everything.\n\nFather, I am an heir — co-heir with Christ, participant in His suffering and destined for His glory. I receive the inheritance that love prepared. And I trust the path, even when it runs through pain. Amen. 💜"
    },
    "07-10": {
        "title": "The Promise Behind All Things Working Together",
        "devotionalText": "Romans 8:28 is one of the most quoted verses in the Bible — and most people quote only half of it.\n\nAnd we know that in all things God works for the good of those who love him, who have been called according to his purpose. That's the part everyone knows. But the verse doesn't land until you read the context. Paul has just been talking about suffering, groaning, weakness, and not knowing what to pray for. This promise about all things working for good was written to people in real pain, not to people wondering which of two good options to choose.\n\nAll things — not just the pleasant things. Not just the things that resolve quickly. The things that remain unresolved for years. The things that seemed random and cruel. The things that were caused by someone else's sin. All things — Paul includes them all in what God is able to work for good.\n\nBut the promise has a context: those who love him, who have been called according to his purpose. This is not a general spiritual law that applies to everyone. It is a specific covenant promise to those who are in relationship with God. And it is rooted in purpose — His purpose, which preceded the suffering and will outlast it.\n\nThe following verse reveals what the purpose is: to be conformed to the image of his Son, so that he might be the firstborn among many brothers and sisters. The all things are being worked toward that end. Every hardship, every unanswered question, every painful season — God is using it in the shaping of a people who look like Jesus.\n\nYou are being shaped, not abandoned. The hard things are materials in the hands of a craftsman who knows exactly what He's making.\n\nFather, I trust the all things — including the parts I don't understand. You are working, and the goal is Christlikeness. I hold onto Your purpose in my pain, knowing the craftsman has not put down His tools. Amen. 💜"
    },
    "08-10": {
        "title": "The Mystery Revealed in You",
        "devotionalText": "God kept a secret hidden through the ages — and then He chose to make it known through the lives of ordinary people.\n\nColossians 1:27 describes what Paul calls the glorious riches of this mystery. He has just explained that for ages this thing was hidden. The prophets of Israel saw glimpses. The nations of the world were entirely in the dark. And then, in this generation, in this age, God decided to reveal it: the mystery is Christ in you, the hope of glory.\n\nChrist in you. Not Christ beside you or above you or available to you when you pray. In you. The fullness of the Godhead — the same Christ who is the image of the invisible God, by whom all things were created, who is before all things — is living inside ordinary human beings. This is what was hidden. This is what is now revealed.\n\nThe hope of glory — which means the presence of Christ in you is the guarantee of your ultimate transformation. Glory is not just a future destination; it is a direction you are already moving in because of who is living inside you. The Christ who is in you is pulling your life toward the completion He already represents.\n\nPaul says he labors and struggles to present everyone fully mature in Christ. The goal is not that people have information about Christ — it is that Christ is so thoroughly formed in them that their maturity becomes evident. The mystery becomes visible in a transformed life.\n\nYou are the revelation of a mystery that was kept hidden since before the world began. The ages waited for this. You are living in the era of its full unveiling.\n\nJesus, You are in me — the hope of glory, the mystery revealed. Let Your presence be visible in my life. Transform me from the inside out until the mystery is undeniable. I am the place where the secret becomes visible. Amen. 💜"
    },
    "09-10": {
        "title": "Set Your Heart on What's Above",
        "devotionalText": "Where you set your heart determines what kind of life you actually live — and Paul says to set it on the highest possible thing.\n\nColossians 3:1-2 gives one of the most important instructions in the letter: since you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God. Set your minds on things above, not on earthly things.\n\nBoth heart and mind. Both desire and thought. The instruction covers the two dimensions of inner life that everything else flows from — what you want and what you think about. Paul isn't asking you to ignore earthly life. He is asking you to live earthly life from a heavenly orientation.\n\nThe reason is theological: you have been raised with Christ. Your resurrection is already accomplished in the same way that Christ's resurrection is accomplished. You are not a person standing on the earth looking up at heaven hoping to get there. You are a person who is already raised — whose real life is hidden with Christ in God — temporarily inhabiting an earthly body.\n\nSince that is your reality, it makes sense to set your attention on the reality that is most true. The earthly things are real but temporary. The things above — the purposes of God, the character of Christ, the coming kingdom — are real and permanent. Setting your heart on what is permanent gives you stability that circumstances cannot provide.\n\nWhere you keep your attention shapes your desires. Where your desires go, your life follows. Setting your heart on things above is not escapism — it is reorientation toward ultimate truth.\n\nJesus, I set my heart on You — where You are seated at the Father's right hand. I let what is above shape what is below in my life. My real life is hidden in You. Let my daily living reflect that orientation. Amen. 💜"
    },
    "10-10": {
        "title": "Dead to Sin, Alive to God — Right Now",
        "devotionalText": "The problem with sin is not that it has power over you — it's that you keep acting like it does.\n\nRomans 6:11 is a command that requires you to do something with what you know: count yourselves dead to sin but alive to God in Christ Jesus. The verb count — logizomai — is an accounting term. It means to calculate, to reckon, to factor something into your equations. Paul is telling you to include a specific reality in how you calculate your life: you are dead to sin.\n\nDead to sin does not mean sin cannot tempt you. It means sin has no more legal authority over you than a dead man's debts have over his living children. The old self who was enslaved to sin has died. You have been crucified with Christ. The dominion that sin exercised over your old nature no longer applies to your new one.\n\nBut the reckoning is required. This is not automatic. Paul says count yourselves — you must factor it in. You must include in your moment-by-moment calculation the fact that sin's power over you has been broken. When temptation comes, when the old patterns call, you reckon: I am dead to this. It has no dominion over me.\n\nAlive to God in Christ Jesus. The aliveness is also something to reckon. Every impulse toward holiness, every draw toward prayer, every moment when you want something genuinely good and true — count that. That is your aliveness to God expressing itself. Reckon it. Factor it in.\n\nYou are dead to sin and alive to God — not as a goal, but as a present fact. Reckon accordingly.\n\nFather, I count myself dead to sin and alive to You — right now. I factor Your reality into every moment. When sin calls, I reckon: dead. When You call, I reckon: alive. Let this accounting reshape how I live today. Amen. 💜"
    },
    "11-10": {
        "title": "The Temple You Live In",
        "devotionalText": "You treat a temple differently than you treat an ordinary building — and Paul says your body is a temple.\n\n1 Corinthians 6:19-20 asks one of the most searching questions in the New Testament: do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own; you were bought at a price.\n\nTemple language in Paul's world carried enormous weight. The Jerusalem Temple was the dwelling place of the living God — the place where heaven met earth, where the divine presence was most fully concentrated. Ordinary people could not simply walk in. Priests served in it with solemn precision. It was the most sacred space in the world.\n\nAnd Paul says: your body is that.\n\nThe same Spirit who made the tabernacle in the wilderness holy by dwelling in it now dwells in you. Your physical body — with all its limitations and frailties — is the current dwelling place of the God of the universe. Not metaphorically. Actually.\n\nYou are not your own. This is not a burden — it is a liberation. You don't have to figure out what your body is for or what you should do with it. That question was answered at the cross: you were bought at a price. Your body belongs to the One who purchased it, and He has a clear purpose for it — that God may be glorified in your body.\n\nGlorified in your body. Every act of care for your physical self, every decision about what you invite your body into, every choice about how you use the only body you have — these are stewardship decisions, not just personal preferences.\n\nHoly Spirit, You live in me — in this body. I honor that by honoring what You inhabit. I am not my own. I belong to the One who bought me. Let me steward that well. Amen. 💜"
    },
    "12-10": {
        "title": "The Transformer in the Mind",
        "devotionalText": "The world has a pattern for your life — and it is aggressively trying to press you into it. The only thing powerful enough to resist is a transformed mind.\n\nRomans 12:2 is a verse that most people have read dozens of times without noticing the sequence it describes: do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is — his good, pleasing and perfect will.\n\nConform is a passive action — something that happens to you if you don't actively resist it. The world's pattern is always pressing. The way it thinks about success, about worth, about what matters, about how you should spend your time and energy and desire — it is a constant ambient pressure. The default is to be shaped by it.\n\nBe transformed — the Greek is metamorphousthe, from which we get metamorphosis. This is also passive in form: it is something that happens to you. But it happens through a specific mechanism: the renewing of your mind. The transformation is not produced by willpower or behavior modification. It happens when the mind is renewed — when the categories through which you perceive reality are progressively replaced with God's categories.\n\nThen you will be able to test and approve — the result of transformation is discernment. The renewed mind can actually perceive what God's will is. Not just know the rules, but genuinely assess what is good and pleasing and perfect in any given situation.\n\nYou can't out-discipline the world's pressure. But a renewed mind can perceive what the world can't see — and live from that.\n\nFather, renew my mind. Replace my categories with Yours. Let the transformation come from the inside out, so that I can discern what is truly good. I don't want to be conformed — I want to be transformed. Amen. 💜"
    },
    "13-10": {
        "title": "Your Part in the Body",
        "devotionalText": "The body of Christ is not complete without your specific contribution — and no substitute can fill the role you were placed in.\n\nPaul returns to the body metaphor in Romans 12, having established the theological foundation in the earlier chapters. Each of us is a member of one body, he says — but with different gifts, according to the grace given to each of us. The gifts he lists include prophecy, service, teaching, exhortation, giving, leadership, and showing mercy. None of these are about performance. They are about function — what each person is equipped to contribute to the whole.\n\nThe instruction for each gift is telling. The prophet speaks in proportion to faith. The servant gives himself fully to serving. The teacher teaches — not part-time, not when inspired, but as a consistent contribution. The one who gives does so generously. The one who leads does so diligently. The one who shows mercy does so cheerfully.\n\nCheerfully — that word stops the list. Mercy is listed alongside prophecy and teaching as a spiritual gift. And the specific instruction for it is not that it be given adequately or faithfully, but cheerfully. Mercy that is dispensed with reluctance is not functioning in its full capacity. It is mercy that gives itself away with genuine joy that demonstrates the nature of the God from whom all mercy flows.\n\nWhat gift have you been given? Are you functioning in it? The body needs what you carry. Not someone else's version of it — yours. The grace was given specifically to you, shaped for your particular contribution.\n\nFather, I give the gift You gave me — not minimally, not reluctantly, but fully and cheerfully. The body needs what I carry. Let me function faithfully in the role You placed me in, contributing what only I can contribute. Amen. 💜"
    },
    "14-10": {
        "title": "The Power in Your Mouth",
        "devotionalText": "You hold in your mouth one of the most powerful instruments in the universe — and you use it multiple times every day without thinking about it.\n\nProverbs 18:21 is not an encouragement to be positive. It is a statement of fact about the structure of reality: the tongue has the power of life and death, and those who love it will eat its fruit. Life and death. Not good days and bad days. Not helpful and unhelpful. Life and death — the fullest categories of blessing and destruction.\n\nThe second half of the verse is especially sobering: those who love it will eat its fruit. You don't get to speak words without consequences. Words have a trajectory. The things you say over yourself — about your capacity, your future, your worth — those words are planting something. The things you say over others — your children, your spouse, your colleagues — those words are planting something. The fruit grows from the seeds.\n\nJesus took this seriously. He said that people will give account on the day of judgment for every careless word they have spoken. He also said that out of the overflow of the heart the mouth speaks. The mouth is a revealer — it tells you what is filling the heart. But it is also a shaper — what you speak consistently creates new realities in the soil of your soul and the lives of people around you.\n\nThe tongue has the power of life. This means your words can build, can heal, can encourage, can strengthen, can speak truth into dark places and call things that are not yet real into being. That is extraordinary power to carry in an ordinary organ.\n\nUse it for life today. Deliberately. Intentionally. With awareness of what you're actually doing.\n\nFather, I choose life with my mouth today. Help me hear what I'm saying before it lands. Let my words be consistently life-giving — to myself, to others, to the situations around me. I will eat what I plant. Let me plant well. Amen. 💜"
    },
    "15-10": {
        "title": "Guard the Source",
        "devotionalText": "Every action you take, every word you speak, every decision you make — it all flows from one source. Guard it accordingly.\n\nProverbs 4:23 does not recommend guarding your heart. It commands it, with an explanation attached that makes the command self-evident: above all else, guard your heart, for everything you do flows from it. Above all else — not just as one priority among many, but as the priority that undergirds every other priority. Why? Because everything flows from it.\n\nThe heart in Hebrew thought is not primarily the seat of emotion. It is the center of will, thought, desire, and the integrated self — the place from which a person's life is actually directed. What the heart is oriented toward, the life moves toward. What the heart has absorbed, the actions eventually express.\n\nGuarding the heart means being intentional about what you let in. The things you meditate on. The voices you allow to speak most consistently into your life. The environments you habitually put yourself in. The relationships that shape your desires. These things are either fortifying the heart or weakening it, and the cumulative effect shows up in every area of your life downstream.\n\nJesus said: blessed are the pure in heart, for they shall see God. The pure heart is not one that has never been contaminated — it is one that has been cleansed and kept. The word pure carries the image of something that has been refined, cleared of what doesn't belong, maintained in a condition of clarity.\n\nWhat are you letting in? What is flowing out? Follow the river back to the source, and tend the source carefully.\n\nFather, help me guard my heart — not in anxiety but in wisdom. What I allow to fill this place shapes everything else. I want a heart that is oriented toward You, tended carefully, producing the life that flows from a pure source. Amen. 💜"
    },
    "16-10": {
        "title": "Renewed While Wasting Away",
        "devotionalText": "The outer person is losing ground every day — and the inner person is gaining ground every day. These are not in competition.\n\nPaul's framing in 2 Corinthians 4:16 is one of the most honest and hopeful things in the New Testament: though outwardly we are wasting away, yet inwardly we are being renewed day by day. He does not pretend the outward deterioration isn't real. Bodies age. Energy decreases. Physical capacity diminishes. Wasting away is accurate and Paul acknowledges it.\n\nBut simultaneously — not eventually, not after the outward is finished, but simultaneously — the inward is being renewed. Day by day. Present tense, continuous. Every day that the outer person loses something, the inner person is being refreshed, strengthened, filled with more of what matters.\n\nTherefore we do not lose heart. That therefore is the key. Paul's refusal to despair is not denial. It is not optimism based on ignoring reality. It is a calculation — weighing the outer and inner together and concluding that the inner is winning. The renewal happening in the hidden person is more significant than the deterioration happening in the visible one.\n\nThis perspective is only possible if you believe the inner person is more real than the outer one — which is exactly what Paul believes. You are not a body that has a soul. You are a soul that temporarily inhabits a body. The body is the temporary. The inner person is the eternal.\n\nYou don't have to lose heart as your body changes, as your circumstances shift, as the outer things you built your confidence in begin to show their limits. There is a deeper renewal happening simultaneously.\n\nFather, I don't lose heart — because while the outer is wasting away, the inner is being renewed day by day. I invest in the inner person. I receive Your daily renewal. The real me is getting stronger even when the visible me is getting weaker. Amen. 💜"
    },
    "17-10": {
        "title": "The Weight That Waits for You",
        "devotionalText": "You are not enduring difficulty for nothing — you are accumulating something that Paul calls an eternal weight of glory.\n\n2 Corinthians 4:17 contains one of the most counterintuitive equations in the New Testament: our light and momentary troubles are achieving for us an eternal glory that far outweighs them all. Paul writes this from experience. His troubles included beatings, stonings, shipwrecks, imprisonment, sleeplessness, hunger, and the constant pressure of churches that needed more than he had. Light and momentary.\n\nNot because the pain was trivial — it wasn't. But because of what it was achieving. The word achieving is katergazetai — to work out, to produce, to bring about. The troubles are not just endured; they are productive. They are actively generating something: an eternal glory that far outweighs them all.\n\nFar outweighs — the Greek word is hyperbolen, from which we get hyperbole. Beyond measure. Past exaggeration. The weight of future glory cannot be accurately described by the language available — it exceeds what can be communicated. And it is being set on the scale against your present troubles. Present troubles lose.\n\nBut not automatically. Paul adds the condition: if we fix our eyes not on what is seen, but on what is unseen. The accumulation of glory is connected to the orientation of attention. When you fix your eyes on the trouble, it feels overwhelming. When you fix your eyes on the eternal, the trouble takes its proper proportion.\n\nYour suffering is not wasted. It is being exchanged — at a rate that no investor would believe — for eternal weight.\n\nFather, I fix my eyes on what is unseen. My present troubles are light and momentary compared to what is being achieved through them. I receive that exchange by faith, not by sight. You are weaving glory from what feels like loss. Amen. 💜"
    },
    "18-10": {
        "title": "The Discipline of the Unseen",
        "devotionalText": "The most important realities in your life are invisible — and fixing your eyes on them is not escapism, it is the most clear-eyed thing you can do.\n\n2 Corinthians 4:18 gives the strategic instruction that undergirds everything Paul has said about endurance and hope: we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal.\n\nFix is an intentional word. Eyes don't fix themselves — you direct them. This is a discipline, not a default. The default is to look at what is immediately visible: the problem, the lack, the difficulty, the obstacle. The visible is loud. It presses. It insists on being looked at.\n\nBut Paul says the visible is temporary. However persistent, however loud, however painful — it will pass. Every visible thing that currently presses on you is in the category of things that will end. The eternal is invisible — it operates in the realm that your physical eyes cannot access — but it is the more real of the two.\n\nThe resurrection is the proof. Jesus' body died — fully visibly, publicly, certifiably dead. And then the invisible reality broke through. The power of God, operating in the unseen realm, invaded the visible and produced the resurrection. The invisible was more powerful than the visible reality of death.\n\nWhen you fix your eyes on what is unseen — when you deliberately train your attention on the character of God, the promises of His word, the coming kingdom, the eternal reality — you are not fantasizing. You are aligning your perception with what is most real.\n\nFather, I fix my eyes on what is unseen — Your purposes, Your promises, Your presence, Your coming glory. The visible is loud but temporary. The invisible is quiet but eternal. I choose the eternal today. Amen. 💜"
    },
    "19-10": {
        "title": "The Walk That Has Nothing to Do With Sight",
        "devotionalText": "Faith is not the absence of evidence — it is the capacity to act on a different kind of evidence than what your eyes can see.\n\n2 Corinthians 5:7 is four words in the Greek that have anchored millions of people in moments when visible reality was terrifying: we live by faith, not by sight. It is not a rejection of physical reality. It is a statement about which reality gets to be determinative.\n\nSight is the most immediate sense. It gives you data about the present moment — what is here, what is visible, what can be measured and verified right now. Sight is not wrong. But sight is limited to the visible. And the visible is always partial — it shows you a slice of reality, never the whole.\n\nFaith has access to the whole. Not because it ignores the visible, but because it also holds the invisible in view. When Paul faced imprisonment, he held the visible reality — chains — alongside the invisible reality — the purposes of God. When he faced death, he held the visible — mortal body — alongside the invisible — the resurrection. Living by faith meant he didn't let the visible overrule the invisible.\n\nThis is what Abraham did when he looked at a barren womb and believed the promise of God. This is what the three Hebrew men did when they stood at the door of the furnace and said: our God is able to deliver us. Sight said: fire kills. Faith said: God is present. They walked by faith.\n\nEvery day you have a choice about which data you live from. The visible is real. The invisible is more real. Live from both, but let the invisible have the final word.\n\nFather, I walk by faith today — not ignoring what I see, but not letting it be the final word. The invisible reality of who You are is more determinative than any visible circumstance. I live from that. Amen. 💜"
    },
    "20-10": {
        "title": "Spiritual Weapons for a Spiritual War",
        "devotionalText": "You are in a war — and you have been trying to fight it with the wrong weapons.\n\n2 Corinthians 10:4 names the problem and the solution in a single sentence: the weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds. The weapons we commonly reach for — clever arguments, social pressure, self-improvement strategies, willpower, human persuasion — these are the world's weapons. They have some limited effect in earthly matters. But in the spiritual war, they are impotent.\n\nDivine power is different. The weapons that carry divine power are prayer, the word of God, faith, worship, the spoken name of Jesus. These don't look powerful by worldly measurement. They don't impress people who evaluate by visible impact. But they have power to demolish what human effort cannot touch.\n\nStrongholds — the Greek is ochyrómata, literally a fortified place, a citadel. In Paul's context, he is specifically addressing strongholds of thought — patterns of reasoning that have established themselves in opposition to the knowledge of God. Arguments, pretensions, every high thing that exalts itself against the knowledge of God — these are intellectual and spiritual fortifications.\n\nDemolish — not negotiate with, not politely request the removal of. Divine weapons have demolishing power. When you bring the word of God and genuine faith into a thought pattern that has been established against truth, you are wielding something that has the structural capacity to bring it down.\n\nThe war is real. The weapons are real. Use the ones that actually work.\n\nFather, I pick up the weapons that have divine power — prayer, Your word, faith, the name of Jesus. I don't fight spiritual battles with human strategies. Let Your power demolish every stronghold in my life and in the lives of those I pray for. Amen. 💜"
    },
    "21-10": {
        "title": "Every Thought Brought Into Custody",
        "devotionalText": "The battlefield where most spiritual wars are lost and won is not your behavior — it is your mind, and specifically the thoughts you allow to stay there.\n\n2 Corinthians 10:5 describes the military operation Paul has in mind when he talks about spiritual warfare: we demolish arguments and every pretension that sets itself up against the knowledge of God, and we take captive every thought to make it obedient to Christ.\n\nTake captive every thought. This is an aggressive image — soldiers rounding up prisoners, disarming them, bringing them under authority. Thoughts that are left to roam freely will set up residence and eventually fortify. Thoughts that are captured and examined in the light of Christ — who He is, what He has said, what is actually true — cannot survive long in that light if they are lies.\n\nEvery thought that contradicts who God says He is. Every thought that contradicts who God says you are. Every thought that disputes the reliability of His promises. These are thoughts that have set themselves up against the knowledge of God. They don't belong in the mind of someone who has the mind of Christ. They need to be taken prisoner.\n\nThis is practical work. When a thought arrives — I'm not enough. God doesn't really care about this. This will never change. This is beyond God's reach — you don't have to receive it. You examine it. Does this align with what God has said? If not, you don't entertain it as a legitimate resident. You take it captive. You bring it into obedience to Christ.\n\nYour mind is the territory. Guard it actively.\n\nFather, I take every thought captive — examining what arrives before I allow it to stay. Let my mind be shaped by what is true about You and about me. I refuse to let lies set up strongholds in my thinking. Every thought obedient to Christ. Amen. 💜"
    },
    "22-10": {
        "title": "The Suffering That Doesn't Compare",
        "devotionalText": "Paul says your present suffering is not worth comparing to what is coming — and he says this as someone who suffered more than almost anyone.\n\nRomans 8:18 is not written from an armchair. Paul writes it from the same biography that includes beatings, shipwrecks, imprisonment, and being left for dead after a stoning. When he says our present sufferings are not worth comparing with the glory that will be revealed in us, he is calculating from personal experience with both sides of the equation.\n\nThe present sufferings are real. He doesn't minimize them or pretend they aren't happening. But they are present — temporary, belonging to this age, limited in duration even when they seem endless. And they are not worth comparing — the comparison doesn't even make sense, because the categories are so different in scale.\n\nThe glory that will be revealed in us. In us — not just around us or above us, but in us. The same way that the treasure is in the clay jar, the glory that is coming will be revealed from within the people it is already being developed in. The suffering is not preventing the glory — it is participating in producing it.\n\nAll of creation is on tiptoe, Paul says, waiting for the children of God to be revealed. The natural world itself is straining forward, anticipating the moment when what God is doing in His people becomes fully visible. What you carry — the hope, the Spirit, the new creation nature — will be revealed in its fullness.\n\nYou are not lost in the middle of something meaningless. You are in the middle of something that all of creation is watching for.\n\nFather, I hold my present suffering alongside the glory You are preparing. They don't compare. I keep my eyes on what's coming — and I trust that what You are doing in me is worth the groaning. Amen. 💜"
    },
    "23-10": {
        "title": "The Universe Is Waiting for You",
        "devotionalText": "There is something creation is waiting to see — and it is the full revelation of who you are as a child of God.\n\nRomans 8:19 describes a cosmic anticipation that most people have never considered: the creation waits in eager expectation for the children of God to be revealed. The word for eager expectation is apokaradokia — a compound word that literally means the head stretched out in anticipation, leaning forward, straining to see what is coming.\n\nCreation is doing this. The natural world, groaning in frustration at its own subjection to decay, is craning its neck toward the future moment when the children of God are revealed in their full glory. Not just waiting passively — eagerly expecting. There is anticipation written into the fabric of the natural world for the unveiling of what God is making in you.\n\nThe children of God to be revealed. What is revealed is what was always there but hidden. Your identity as a child of God is real now — but it is not fully visible now. The resurrection body, the full transformation into the image of Christ, the complete expression of what the Spirit has been building in you — this is not yet fully manifest. But it is coming.\n\nThe world you walk through every day is leaning forward. It is in birth pains, Paul says — the specific kind of suffering that is productive, that is pointing toward a new thing rather than simply deteriorating. Something is coming.\n\nYou are not an afterthought in the story of creation. You are the thing creation is waiting to see.\n\nFather, creation is waiting for the children of God to be revealed — and I am one of them. I carry something the world is straining to see. Let me live with the dignity and hope that comes from knowing who I am and what is coming. Amen. 💜"
    },
    "24-10": {
        "title": "When You Don't Know What to Pray",
        "devotionalText": "There is a kind of prayer that bypasses language entirely — and it is the most powerful kind.\n\nRomans 8:26-27 describes a dimension of intercession that most believers have experienced but few have understood. In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans. And he who searches our hearts knows the mind of the Spirit, because the Spirit intercedes for God's people in accordance with the will of God.\n\nWe do not know what we ought to pray for. This is not a failure. It is an honest acknowledgment of the limits of human perception. You see your situation from inside it. You cannot see the full divine purpose. You cannot always know what the best outcome looks like from God's vantage point. Not knowing what to pray is not a spiritual deficiency — it is spiritual honesty.\n\nThe Spirit helps in this weakness. The word for helps — sunantilambanetai — means to take hold together on the opposite side, to lift together with someone. The Spirit doesn't replace your prayer; He comes alongside it and carries what you can't carry. He prays from within you, with a depth and accuracy that language cannot contain — wordless groans that the Father fully understands.\n\nHe who searches hearts knows the mind of the Spirit. The Father and the Spirit are in perfect communication. The Spirit's intercession on your behalf is always in accordance with God's will. Your prayer, through the Spirit, always connects to what the Father intends.\n\nYou are never without a perfect intercessor. The Spirit is praying inside you right now.\n\nHoly Spirit, intercede for me — especially where I don't know what to pray. Take what I cannot articulate and carry it to the Father accurately. I trust that Your groaning on my behalf is always according to His will. Amen. 💜"
    },
    "25-10": {
        "title": "The Pattern Behind Your Purpose",
        "devotionalText": "God is not making you successful — He is making you like someone, and that someone is His Son.\n\nRomans 8:28 is often quoted as comfort in difficulty, but Romans 8:29 explains what the difficulty is actually working toward: those he foreknew he also predestined to be conformed to the image of his Son, that he might be the firstborn among many brothers and sisters.\n\nConformed to the image. This is the goal. Not your comfort, not your success, not the resolution of your difficulties according to your preferred timeline — Christlikeness. The ongoing transformation of your character, your desires, your responses, your capacity for love and suffering and faith — these are being shaped toward the image of Jesus.\n\nThe logic of Romans 8:28 — that all things work for good for those who love Him and are called according to His purpose — only makes full sense when you know what the purpose is. The good that all things are working toward is the good of Christlikeness. Your pain is not random suffering being redeemed after the fact. It is material being worked, in the hands of a craftsman who knows exactly what He's shaping.\n\nFirstborn among many brothers and sisters — Jesus is not the lonely exception. He is the pattern. The goal is a family of people who bear a family resemblance, who carry the character of the firstborn Son in their own lives. You are being made into a sibling of Christ. That is the trajectory of your transformation.\n\nEvery situation you face is either conforming you toward His image or being used by Him to do so. Nothing is outside the purpose.\n\nFather, I submit to the purpose — Christlikeness. I stop asking only for comfort and start asking to be conformed. Use what I'm going through to make me look more like Your Son. That is the good I want. Amen. 💜"
    },
    "26-10": {
        "title": "No Condemnation — Not Some, Not Reduced — None",
        "devotionalText": "The most liberating verdict ever rendered in the history of the universe was spoken over you — and it cannot be appealed.\n\nRomans 8:1 is one of the great declarative sentences in Scripture: there is now no condemnation for those who are in Christ Jesus. Three words carry all the weight: no condemnation. Not reduced condemnation. Not suspended condemnation pending continued good behavior. No condemnation. The verdict is final, complete, and permanent.\n\nNow — present tense. Not once your life is cleaned up, not after you've proven yourself, not when you eventually get it right. Now. Today. This morning, with all of last week still fresh. The condemnation that was your legal due — the full weight of the law's judgment on the life you've actually lived — is gone.\n\nIn Christ Jesus — this is the location that makes the verdict possible. The condemnation was placed on Christ at the cross. It cannot be double-charged. What was laid on Him cannot be charged to those who are in Him. You are inside the same legal reality as the One who already bore the penalty.\n\nPaul will ask later: who will bring a charge against God's elect? It is God who justifies. Who is the one who condemns? It is Christ Jesus who died — who was raised — who is at the right hand of the Father — who also intercedes for us. The One who could condemn is instead interceding. That is the most favorable possible legal position.\n\nThe voice that tells you that you are not forgiven, that God is keeping a record, that you are in a state of divine disapproval — that voice is lying. There is no condemnation.\n\nJesus, there is no condemnation for me because I am in You. I reject every condemning voice that contradicts Your verdict. You bore my condemnation. I receive the no condemnation You secured. Amen. 💜"
    },
    "27-10": {
        "title": "Strength and Salvation in One",
        "devotionalText": "When God is your strength, you don't just survive — you become someone who can sing about it afterward.\n\nPsalm 118:14 is a song that emerged from somewhere on the other side of a devastating threat: the Lord is my strength and my defense; he has become my salvation. The word become is significant — it indicates that the salvation was witnessed. It didn't exist abstractly; it happened. The psalmist went through something where God's saving intervention was visible and real.\n\nStrength and defense — in the Hebrew, oz and zimrat. Strength in the sense of power and might. Defense in the sense of song, praise, melody. These two are paired in a way that is poetically significant: God is both the power that sustains you and the song you sing because of it. He is the reality and the response to the reality, the provision and the praise that provision produces.\n\nThe psalmist goes on: I will not die but live, and will proclaim what the Lord has done. There was a moment when dying seemed like the more likely outcome. The armies had surrounded him — he uses that image in the surrounding verses. He was cut off, hard-pressed, pushed back. And the Lord answered him. The Lord helped him.\n\nThis testimony is yours too. Every moment that should have ended badly but didn't — every survival, every restoration, every place where you found God sufficient when circumstances said you shouldn't — that's the material of this song.\n\nYou are still here. That is evidence of a God who has been your strength and defense. Sing about it.\n\nFather, You are my strength and my defense — I have seen You act on my behalf. I will not be silent about what You've done. Let my life be a song about Your saving power, a testimony that others can point to when they need to believe You'll show up. Amen. 💜"
    },
    "28-10": {
        "title": "Momentum in the Right Direction",
        "devotionalText": "The life of faith is not meant to plateau — it is meant to move in one direction, from strength to strength, until you see God face to face.\n\nPsalm 84:5-7 describes a particular kind of person: blessed are those whose strength is in you, whose hearts are set on pilgrimage. As they pass through the Valley of Baka, they make it a place of springs. They go from strength to strength, till each appears before God in Zion.\n\nFrom strength to strength. The image is cumulative — each gain in strength becoming the foundation for the next. Not oscillating between strong and weak, not losing ground over time, not maintaining a spiritual plateau. Going. Forward. More strength at every stage than the last.\n\nBut the route runs through the Valley of Baka — a valley associated with weeping, with difficulty, with the kind of terrain that depletes. The pilgrims who are going from strength to strength are not avoiding the valley. They are passing through it. And as they pass through it, they make it a place of springs — the desert yields to the presence of people whose strength comes from God.\n\nYour valley is not your destination. It is part of the route. The valleys you walk through are places you pass through on the way to appearing before God — and if your heart is set on that pilgrimage, you don't get stuck in the valley. You transform it as you move through it.\n\nStrength to strength. That is the direction of your life if your strength comes from Him. Every stage builds on the last. Every valley is transitional. You are heading somewhere, and the momentum is forward.\n\nFather, I set my heart on pilgrimage — with You as my strength at every stage. Let me go from strength to strength, not backward. Even when the route runs through valleys, I keep moving forward. I am heading toward seeing You face to face. Amen. 💜"
    },
    "29-10": {
        "title": "Hidden Now, Revealed Then",
        "devotionalText": "What is truest about you is invisible right now — but there is a day coming when it will be fully visible, and it will be glorious.\n\nColossians 3:3-4 contains one of the most hope-filled promises in Paul's letters: you died, and your life is now hidden with Christ in God. When Christ, who is your life, appears, then you also will appear with him in glory.\n\nHidden — the word means tucked away in safekeeping, stored in the most secure possible location. Your real life, your most essential identity, your eternal destiny — these are not out in the open where circumstances can access them or enemies can damage them. They are hidden with Christ in God. Inside the innermost security of the divine life.\n\nThe hiding is temporary. There is a when — a specific moment on the timeline of history when Christ appears. And when He appears, you appear with Him. The glory that has been forming in you invisibly will become visible. The inner transformation, the new creation nature, the family resemblance to the Son — all of it will be revealed in what Paul elsewhere calls the glorification of the children of God.\n\nThis gives the present moment a different quality. When you face something difficult, when you feel misunderstood or overlooked or like your true self isn't visible to the people around you — the hiddenness is not rejection. It is protection. The real you is being kept in the safest possible place until the moment of full revelation.\n\nYou will appear with him in glory. Not as an afterthought. With Him. In His glory.\n\nFather, my real life is hidden with Christ in You — safe, secure, being kept. I trust the hiddenness. The day of revelation is coming, and I will appear with Christ in glory. Until then, I live from what is hidden, not from what is visible. Amen. 💜"
    },
    "30-10": {
        "title": "The Source of All I Can Do",
        "devotionalText": "Philippians 4:13 is one of the most misquoted verses in the Bible — and understanding what it actually means might change how you pray.\n\nI can do all this through him who gives me strength. The all this in context is specific — Paul is talking about contentment in every circumstance: knowing how to be brought low and how to abound, how to be hungry and how to have plenty. The strength he's describing is not the strength to achieve every goal on your vision board. It is the strength to be content, to remain joyful, to not lose your peace regardless of whether circumstances are going your way.\n\nThat kind of strength is actually harder to maintain than physical or emotional strength. Anyone can be content when everything is going well. The person who can maintain genuine contentment in scarcity, who can experience genuine peace in difficulty, who can hold their joy when the bottom falls out — that person has a kind of strength that is not natural. It comes from somewhere else.\n\nThrough him who gives me strength — the giving is continuous in the Greek. Not given once. Continually given, at the moment of need, in the measure required. Christ is the ongoing supplier of the strength needed for the life He has called you to.\n\nThis promise covers everything He has called you to do. Not everything you decide to take on independently. Not the projects you launch without His leading. Everything He has asked of you — parenting, relationships, ministry, work done with integrity, love extended when it costs you — the strength for all of this is supplied by Him, continuously, as needed.\n\nYou can do what He has called you to do. Not because you are strong — because He is.\n\nJesus, I do all things through You who continuously gives me strength. I stop straining in my own capacity and keep coming back to the supply You provide. Everything You've called me to, You've equipped me for. Amen. 💜"
    },
    "31-10": {
        "title": "Perfect Power in the Place of Your Weakness",
        "devotionalText": "The most uncomfortable invitation God ever extends is the invitation to stop hiding your weakness — because He has been waiting to show you something.\n\nPaul had a thorn in his flesh. He doesn't tell us what it was — and that ambiguity is significant, because it means every person can locate their own thorn in his story. Something that hurt, something that limited, something that felt incompatible with the ministry God had called him to. He asked three times for it to be removed. Three times God said no.\n\nBut the no came with an explanation that reframes everything: my grace is sufficient for you, for my power is made perfect in weakness. Two declarations. My grace is sufficient — meaning it is exactly the right amount, it covers what the thorn cost, it is enough. And: my power is made perfect in weakness — the Greek word for made perfect is teleitai, to be completed, to be brought to its full expression. The weakness is the environment in which divine power reaches its full manifestation.\n\nWhen you are strong, you can accomplish things. When God is strong through your weakness, He accomplishes what you could not — and there is no possible confusion about the source. The clay jar that holds the treasure is obviously not the point. The treasure is.\n\nPaul's response is one of the most counterintuitive verses in the New Testament: therefore I will boast all the more gladly about my weaknesses, so that Christ's power may rest on me. He stops managing his image and starts offering his inadequacy as the stage on which Christ can be most visible.\n\nYour weakness is not an obstacle to God's power. It is its preferred location.\n\nJesus, Your power is made perfect in my weakness. I stop hiding what I can't do and offer it as the stage for what You can do. When I am weak, You are strong. That is enough. Amen. 💜"
    }
}

# Load the JSON
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'r') as f:
    data = json.load(f)

# Apply rewrites
updated = 0
for i, d in enumerate(data['devotionals']):
    if d['date'] in OCTOBER_REWRITES:
        data['devotionals'][i]['title'] = OCTOBER_REWRITES[d['date']]['title']
        data['devotionals'][i]['devotionalText'] = OCTOBER_REWRITES[d['date']]['devotionalText']
        updated += 1

print(f"Updated {updated} October devotionals")

# Save back
with open('SpeakLife/SpeakLife/Preview Content/AffirmationData/devotionals.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved successfully")
